#+TITLE:      Org-babel: Uses
#+EMAIL:      tsd at tsdye dot com
#+AUTHOR:     Thomas S. Dye
#+OPTIONS:    H:3 num:nil toc:1 \n:nil ::t |:t ^:{} -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) 
#+LANGUAGE:   en

[[file:../index.org][{Back to Babel's index}]]

* A Standardized Short Report

This example is similar to the previous one, but here the users are
expected to write substantial content.  This type of workflow might
be used by a small organization whose employees regularly produce
standard documents and where the writing tasks for any one document
are divided among the authors.

The HTML export facility of Org-mode is used to produce a guide to
writing the standardized short report.  This HTML file can be used
to train new authors.  The Org-mode content also supplies
substantial direction to experienced authors as they write.
Org-mode keywords and tags are used to keep track of writing
assignments and progress.  Org-babel's literate programming facility
makes it possible to present writing tasks to the authors in an order
different from which they appear in the report.

** Requirement
- A working LaTeX installation.

** Advantages
- The integration of training material with in-file instruction can
  be quite effective.
- Many authors find it easy to work from the bottom up, or from the
  particular to the general, rather than the usual sequence of
  general-particular-general found in reports.

** Disadvantages
- Some features of reftex are not yet integrated into the source
  code block editor, so writing and editing are sometimes less
  convenient than writing to the LaTeX document directly.

** Example
- This report must satisfy the requirements set out in [[http://hawaii.gov/dlnr/hpd/pdfs/revproc_har/275_284/pdfs/278.pdf][the Historic
  Preservation Division rule]].
- Complete each of the TODO items.
- Mark each item DONE when you have completed it.
- =C-c a t= will make an agenda of items left to do in this
  document.
- =C-c a m= YOURNAME will make an agenda of writing tasks assigned
  to you.

*** TODO Field Methods
**** TODO Include the following information: [1/7]
- [X] When the fieldwork was carried out.
- [ ] Who directed the fieldwork.
- [ ] The names and qualifications of crew members.
- [ ] Establishment of site datum and grid.
- [ ] Excavation tools.
- [ ] Assignment of contexts.
- [ ] Bag list.
**** DONE Include a citation to the project plan.
:LOGBOOK:
- State "DONE"       from "TODO"       [2009-11-25 Wed 09:53]
:END:

#+name: field-methods
#+begin_src latex
  \section{Field Methods}
  \label{sec:field-methods}
  
  % Enter text below this line.

  Fieldwork for the project was carried out between December 26, 2008
  and February 3, 2009 following an approved plan \cite{plan}.
#+end_src   

*** TODO Results
- Note the use of Org-mode tags to assign sections to authors Veronica and Eric.
- Discuss the artifacts and midden recovered during excavation.


**** TODO Artifacts						   :Veronica:
:LOGBOOK:
- State "TODO"       from "DONE"       [2009-11-25 Wed 09:44]
- State "DONE"       from "TODO"       [2009-11-25 Wed 09:44]
:END:
- Use Sinoto's classification of one-piece fishhooks.
- Cite Anell when describing two-piece fishhooks.
- Use Emory's classification of adzes when describing
  cross-section.
#+name: artifacts
#+begin_src latex
  \subsection{Description of Artifacts}
  \label{sec:artifact-description}
  
  % Enter text below this line
#+end_src

**** TODO Midden						       :Eric:
- Use Kay for identifying and naming marine shells
- Cite Ziegler for information on fish habitats
#+name: midden
#+begin_src latex
  \subsection{Midden}
  \label{sec:midden}
  
  % Enter text below this line
#+end_src

**** No data entry beyond this line

#+name: results
#+begin_src latex :noweb
  \section{Results}
  \label{sec:results}
  
  This section presents the results of excavation.
  
  <<artifacts>>
  
  <<midden>>
#+end_src


*** TODO Introduction
- Give the reader a brief overview of the project and its results.

#+name: intro
#+begin_src latex
  \section{Introduction}
  \label{sec:introduction}
  
  % Text below this line
#+end_src
*** No data entry beyond this line
- The LaTeX code here sets up the environment and inserts the
  defined source code blocks in their report order.
- A call to =org-babel-tangle= produces the LaTeX report document.

#+begin_src latex :noweb :tangle report.tex
  \documentclass{article}
  \begin{document}
  <<intro>>
  <<field-methods>>
  <<results>>
  \bibliographystyle{apa} 
  \bibliography{mybib}
  \end{document}
#+end_src




