#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org-sync backends
#+AUTHOR:     Aurélien Aptel
#+EMAIL:      aurelien.aptel@gmail.com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    ../../index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

Here are useful information about planned backends. 

* Bugtrackers

** Bugzilla

Bugzilla is a full-featured bugtracker written in Perl. There is a
XML-RPC and a JSON-RPC interface which Org-sync can use.

Since the JSON-RPC interface was added fairly recently in Bugzilla
(v3.6 released April 13, 2010), we should focus on the XML one.

- [[http://www.bugzilla.org][Bugzilla website]]
- [[http://www.bugzilla.org/docs/3.2/en/html/api/Bugzilla/WebService.html][XML-RPC API]]

** GitHub

GitHub hosts open source projects and provides git repositories along
with other things, notably a wiki and a bugtracker (GitHub Issues).

GitHub also provides a REST API for their bugtracker. The output format is JSON.

- [[http://github.com][GitHub website]]
- [[http://develop.github.com/p/issues.html][Bugtracker REST API]]

** Redmine

Redmine is a project management web application written in Ruby. It
has a REST API in both JSON and XML.

- [[http://www.redmine.org/projects/redmine][Redmine website]]
- [[http://www.redmine.org/projects/redmine/wiki/Rest_api][REST API]]

** Google Code

Google has its own open source project hoster. It provides a
bugtracker. I didn't find any API for it but each the bug list can be
exported to CSV.

- [[http://code.google.com/][Google Code website]]
- [[http://code.google.com/p/chromium/issues/csv][Sample project CSV export]]

* TO-DO list manager

** Toodledo

Toodledo is yet another webservice to organize tasks. It features
TO-DO list, folders, calendars and more.

Toodledo has a REST API specifically designed for syncing. The output
format can be JSON or XML.

- [[https://www.toodledo.com/index.php][Toodledo website]]
- [[http://api.toodledo.com/2/tasks/index.php][REST API]]

** Google Task

Google also has its own task manager. It's more simple and
straightforward than Toodledo: TODO-list and dates.

There's a REST API in JSON.

- [[http://mail.google.com/mail/help/tasks/][Google Tasks website]]
- [[https://developers.google.com/google-apps/tasks/v1/reference/][REST API]]



