#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) 
#+TITLE: Hello Worg!
#+AUTHOR:     Worg people
#+EMAIL:      bzg AT altern DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg

This is webpage of Worg.  Worg is Web-Org: a website collectively edited
using [[http://www.orgmode.org][Org]] and maintained as a [[http://git.or.cz][git]] repository.

* But what is it, exactly?

  [[http://www.orgmode.org][Org]] is an [[http://www.gnu.org/software/emacs/][Emacs]] mode for "keeping notes, maintaining to-do lists, and
doing project planning with a fast and effective plain-text system."
(Excerpt from [[http://www.orgmode.org/org.html][Org manual]])

This website is an attempt of *collectively* editing Org files. 

** But... why ?

Because Org makes it easy, fast and effective to edit *well-structured*
files.  Ever wanted to edit a table in a wiki?  Ever wanted to change
the sectioning structure in a wikipage?  Ever wanted to edit lists
quickly?  Now you can.

Because Org-mode makes *beautiful* documents : it support links, font
beautification, examples, etc.  Anything you can really expect from a
text editing tool.

Because Org is also a powerful *task-management system*.  Having such
facilities /inside a document/ make it easier to write together.

Because Org files can be exported to various formats (HTML, LaTeX).
Ever wanted to write LaTeX documents with people not knowing LaTeX?  
Now you can.

** So it's a bit like a wiki, no?

No.  Yes.  Kind of.  Here are a few differences:

- you edit the pages *using Emacs*, not a cheesy web interface;

- the Worg website (repository) is maintained using [[google:git%20cvs][git]] 

- even if people are invited to merge their changes into the [[http://www.cognition.ens.fr/~guerry/worg/][main Worg
  website]], they are free to start a new Worgie of their own.  Using git
  makes Worg a *distributed* community website.

** Who can edit Worg?

Everyone with a minimal knowledge of Org (and Emacs) and git.  See the
page describing how to use [[file:worg_git.org][git for editing Worg]].

** Do I need to register somewhere?  

It's better to register on http://repo.or.cz/m/reguser.cgi/ but you can
also add changes to the Worg repository anonymously.

** So, what will be the content of this website?

Everything related to Org, project planning and Orgers.

** Who are these people?

Worg was started by Bastien in the hope that other Org-ers around will
bite into this and start sharing tutorials, example of codes, etc.

* Ok, I want to start now!

- [[file:worg_git.org][How to use git for Worg?]]
- [[file:editing_worg.org][How to edit Worg files?]]

Can I have this page in PDF?  Yes.

* Org tutorials

In this section, we list links to Org tutorials.  Feel free to start a
new section with a tutorial of your own.

* My life in Org

# FIXME define a column for this section: People

In this section, each Org user is invited to describe the way he's using
Org.  You can also link to webpage of people describing their everyday
life with Org.

# FIXME: find the link to John Wiegley page

** COMMENT Bastien

# FIXME: Start writing

* Who are these people ?

