

Here are some particularly nice quotes Org-mode

#+AUTHOR:    
#+EMAIL:     
#+DATE: 
#+LANGUAGE:  en
#+TEXT:      
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:nil tags:not-in-toc author:nil creator:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+LINK_UP:   
#+LINK_HOME: 



* Random quotes about Org-mode from the web.

#+begin_quote
I'm having the same feeling for org-mode that I did when I first
learned to really program and use emacs.
@<div align="right">@<i>Jeffery Travis on his [[http://twitter.com/travisjeffery][Twitter feed]].@</i>@</div>
#+end_quote

#+begin_quote
This handy system uses a fairly simple, single-file outlining
paradigm, upon which it overlays concepts like due dates and
priorities. I find its method both non-intrusive and easy to edit
by hand, which are absolute necessities for me.
@<div align="right">@<i>John Wiegley in his [[http://www.newartisans.com/blog_files/org.mode.day.planner.php][blog post]].@</i>@</div>
#+end_quote

#+begin_quote
I love Org's timeclocking support, and I think you will too. Because
it's integrated with your task list, you don't have to switch to
separate application or reenter data.
@<div align="right">@<i>Sacha Chua in a [[http://sachachua.com/wp/2007/12/30/clocking-time-with-emacs-org][blog post]].@</i>@</div>
#+end_quote

#+begin_quote
Someone mentioned that org-mode is a bit like perl. I agree. Way back,
someone described perl as "the Swiss army chainsaw of UNIX
programming". Over the last 12 months, I think org mode has evolved into
something akin to the "Swiss army JCB of organisational software" (to
stretch a metaphor until it screams for mercy!).
@<div align="right">@<i>Pete Phillips in a [[http://article.gmane.org/gmane.emacs.orgmode/754][post on emacs-orgmode]].@</i>@</div>
#+end_quote

#+begin_quote
By far my favorite featureset in org-mode that muse lacks is the table
support, which piggybacks on calc to form more of a spreadsheet than
table support. Insanely cool.
@<div align="right">@<i>Patrick Hawkins in a [[http://article.gmane.org/gmane.emacs.wiki.general/5760][post on emacs-wiki-discuss]].@</i>@</div>
#+end_quote

#+begin_quote
Org is a new working experience for me and there is nothing comparable
to working with emacs AND Org-mode.
@<div align="right">@<i>Sebastian Rose in his [[http://orgmode.org/worg/code/org-info-js/][org-info.js documentation]].@</i>@</div>
#+end_quote

