#+TODO: TODO STARTED | DONE

* Dependencies

Certain parts of org-mode have dependencies on external packages. This
file documents these dependencies. Many sections are placeholders,
waiting for input. If you can, please contribute. If you think that
another section should be added, please add it and fill it out. Also,
if you spot any mistakes, omissions or superfluities, please fix
them. If you have an account, you can clone the Worg tree and make the
additions/fixes [[linkTBD]], but a note to the mailing list
[[linktomaillistTBD]] will also do the job. Thanks!

Version: Org-mode version 6.33trans (release_6.33f.192.ge1a1)

** TODO Exporting in general.

** STARTED LaTeX export.
The LaTeX class is selected using the

#+LaTeX_CLASS: <class>

construct. org-latex predefines the treatment of the
following LaTeX classes (but you can of course customize
this treatment to your heart's content): article, report, book
and (in an experimental branch for now) beamer. The LaTeX packages
included by default are as follows:

*** article, book, report
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{longtable}
\usepackage{float}
\usepackage{wrapfig}
\usepackage{soul}
\usepackage{hyperref}
*** beamer (experimental for now)


** STARTED PDF export.

PDF export goes through LaTeX export first, so all the LaTeX dependencies
apply here as well. In addition, PDF export imposes the following dependencies:

   - foo.

   - bar.

** TODO DocBook export.

** TODO HTML export.

** TODO org-plot.

** TODO org-babel.
