
Quotes about Org-mode

#+AUTHOR:    
#+EMAIL:     
#+LANGUAGE:  en
#+TEXT:      
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:nil tags:not-in-toc author:nil creator:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+LINK_UP:   
#+LINK_HOME: 



* Quotes about Org-mode from the mailing list and the web.

#+begin_quote
I'm having the same feeling for org-mode that I did when I first
learned to really program and use emacs.
@<div align="right">@<i>Jeffery Travis on his [[http://twitter.com/travisjeffery][Twitter feed]].@</i>@</div>
#+end_quote

#+begin_quote
This handy system uses a fairly simple, single-file outlining
paradigm, upon which it overlays concepts like due dates and
priorities. I find its method both non-intrusive and easy to edit
by hand, which are absolute necessities for me.
@<div align="right">@<i>John Wiegley in his [[http://www.newartisans.com/blog_files/org.mode.day.planner.php][blog post]].@</i>@</div>
#+end_quote

#+begin_quote
I love Org's timeclocking support, and I think you will too. Because
it's integrated with your task list, you don't have to switch to
separate application or reenter data.
@<div align="right">@<i>Sacha Chua in a [[http://sachachua.com/wp/2007/12/30/clocking-time-with-emacs-org][blog post]].@</i>@</div>
#+end_quote

#+begin_quote
Someone mentioned that org-mode is a bit like perl. I agree. Way back,
someone described perl as "the Swiss army chainsaw of UNIX
programming". Over the last 12 months, I think org mode has evolved into
something akin to the "Swiss army JCB of organisational software" (to
stretch a metaphor until it screams for mercy!).
@<div align="right">@<i>Pete Phillips in a [[http://article.gmane.org/gmane.emacs.orgmode/754][post on emacs-orgmode]].@</i>@</div>
#+end_quote

#+begin_quote
By far my favorite featureset in org-mode that muse lacks is the table
support, which piggybacks on calc to form more of a spreadsheet than
table support. Insanely cool.
@<div align="right">@<i>Patrick Hawkins in a [[http://article.gmane.org/gmane.emacs.wiki.general/5760][post on emacs-wiki-discuss]].@</i>@</div>
#+end_quote

#+begin_quote
Org is a new working experience for me and there is nothing comparable
to working with emacs AND Org-mode.
@<div align="right">@<i>Sebastian Rose in his [[http://orgmode.org/worg/code/org-info-js/][org-info.js documentation]].@</i>@</div>
#+end_quote

#+begin_quote
Org-mode definition:\\
Org-mode is an emacs mode for doing anything you dream of. If it
can't do it yet, post a message on the mailing list at night, go for
a sleep, and grab in the morning a fresh copy with your features
implemented.
@<div align="right">@<i>Paul Rivier in an email message to the
Org-mode author.@</i>@</div>
#+end_quote

#+begin_quote
Thanks for org-mode that continues to amaze me with its power and
utility each and every day.
@<div align="right">@<i>Bernt Hansen in a [[http://thread.gmane.org/gmane.emacs.orgmode/9213][post on emacs-orgmode]].@</i>@</div>
#+end_quote

#+begin_quote
Org-mode has changed my life!
@<div align="right">@<i>Jonathan E. Magen in a [[http://yonkeltron.com/2008/11/10/org-mode-has-changed-my-life/][blog post]]@</i>@</div>
#+end_quote

* Some 24/7 lectures about Org-mode

The famous 24/7 lectures are part of the ceremony for handing out the
[[http://en.wikipedia.org/wiki/Ig_Nobel_Prize][Ig Nobel Prizes]].  All speakers have to give a 24/7 lecture on their
subject. This means, they have to give a /complete technical
description/ of their work in /24 words/ (may be totally cryptic), and
then a /7 word/ explanation that is more or less /understandable for
the public/, and it may be either tongue in cheek or serious.  In
summer 2008, a few people tried to [[http://thread.gmane.org/gmane.emacs.orgmode/7599][formulate]] such lectures about
Org-mode:

** Technical description in 24 words

These was only a single entry in the "24" category:

  - Org-mode does outlining, note-taking, hyperlinks, spreadsheets,
    TODO lists, project planning, GTD, HTML and LaTeX authoring, all
    with plain text files in Emacs (/Carsten Dominik/)


** Simple summary in 7 words

   This is only a selection of the submitted entries.  My loose
   criterion was to use entries that are either a good description or
   are funny - both valid approaches to the "7" part of 24/7 lectures.
   I also left a few entries which are not exactly seven words,
   because I liked them a lot.

   - Organize and track everything in plain text (/Bernt Hansen/)

   - Organize outlines, lists and table in text. (/Eddward DeVilla/)

   - Emacs Org Mode: your life in text (/Matthew Parker/)

   - Do work and play in plain text (/Kene Meniru/)

   - Madness? This is org-mode! [[http://www.youtube.com/watch%3Fv%3DUgrsNBu51nU][*Real Spartans use emacs!*]] (/Russel
     Adams[1]/)
     
   - Plain text with frickin' lasers. [[http://en.wikipedia.org/wiki/Dr._Evil][*pinky to lips*]] (/Russel Adams[1]/)

   - It is the text that binds us. [[http://www.urbandictionary.com/define.php%3Fterm%3Dshikaka][*Shekaka!*]] (/Russel Adams[1]/)
     

   - Org-mode — lifehacker's orgy :-P (/Dmitry Dzhus/)

   - Back to the future for plain text (/Carsten Dominik/)

[1] The linked text is from Adam, but the link itself has been added
by me.
