#+OPTIONS:    H:3 num:nil toc:t \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+TITLE:      Org mailing list
#+AUTHOR:     Worg people
#+EMAIL:      mdl AT imapmail DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+HTML_LINK_UP:    index.html
#+HTML_LINK_HOME:  https://orgmode.org/worg/

# This file is released by its authors and contributors under the GNU
# Free Documentation license v1.3 or later, code examples are released
# under the GNU General Public License v3 or later.

# This file is the default header for new Org files in Worg.  Feel free
# to tailor it to your needs.

The Org mailing list is an English language forum for discussing Org
and related topics. /The list requires a subscription from a confirmed
email address to post./

It is used by the diverse community of Org developers, maintainers,
contributors, experienced users, and new and prospective users both
for discussion and as a repository of information.  It was established
by the creator of Org-mode, Carsten Dominik, who enjoys the different
perspectives and range of interests expressed there.

The list is less formal and more diverse than a site like
[[http://stackoverflow.com/tags/org-mode/info][stackoverflow]], which has an org-mode section.  Subscribers' messages
to the list aren't moderated and there is no formal mechanism to rate
questions, answers, or reputations.

Consider joining [[file:org-irc.org][Org IRC]] for real time help, simple questions, and to
chat with other Org users.

* List archives

You can browse the mailing list archives and search the message
history at:

 - [[https://public-inbox.org][public-inbox]] archive :: https://orgmode.org/list/
 - Mailman list archive :: https://lists.gnu.org/archive/html/emacs-orgmode/

* Subscribe to the Org mailing list

The Org mailing list is a members only mailing list to prevent
spam. Membership is freely available and only requires that you
subscribe to the list and confirm your email address.

You may [[https://lists.gnu.org/mailman/listinfo/emacs-orgmode][subscribe to the list from this webpage]].

Fill in your email address and provide a password. A confirmation
email will be sent to you. When you reply to the confirmation mail,
you will be able to send messages to the mailing list and receive
messages from the list.

Alternatively you can send an email to [[mailto:emacs-orgmode-request@gnu.org?subject=subscribe][emacs-orgmode-request@gnu.org]]
with a subject of "subscribe". A confirmation email will follow. When
you reply to the confirmation email you will be added to the mailing
list.

* "I don't want to subscribe"

Fine.  Simply send your first message to =emacs-orgmode@gnu.org= and a
moderator will let it through.  You will be added to a whitelist so
that your next messages don't need to go through moderation.  Because
you won't be a proper subscriber, people need to CC you to let you
follow the conversations.

* Posting to the Org mailing list

If you are already a list subscriber, you may post directly to the
list by sending an email to: [[mailto:emacs-orgmode@gnu.org][emacs-orgmode@gnu.org]]

You may also reply to messages you are receiving from the list.

** List Etiquette

Posters are encouraged to be precise, concise, and friendly.
[[https://en.wikipedia.org/wiki/Posting_style#Top-posting][Top-posting]] is discouraged.  Lengthy excerpts of quoted material are
probably redundant and they clog certain distribution channels.
Posters should include enough quoted material to establish the context
for their comments and cut away the rest.

Use of [[https://useplaintext.email/][plain text email]] is strongly preferred.

** Feature Requests

Please label feature requests in the subject, perhaps with "[FR] Please add X".

It's good to have a separate email thread per request, then everyone
can discuss the merits of the suggestion.

** Bug Reports

Bug reports may be submitted to the mailing list. Please label them
appropriately with a tag "[BUG]" and include detailed information on
how to reproduce the bug.

Consider including the output of M-x report-emacs-bug in your message.

Please attached a Minimum Working Example that can be used. See these
links for additional ideas regarding MWEs.

 - https://en.wikipedia.org/wiki/Minimal_working_example
 - http://minimalbeispiel.de/mini-en.html
 - https://stackoverflow.com/help/minimal-reproducible-example

Be patient with bug reports. Maintainer time is limited and it is
likely your issue will benefit from discussion in the overall
community.

* The list and [[https://updates.orgmode.org/][updates.orgmode.org]]

[[https://updates.orgmode.org/][updates.orgmode.org]] makes it easier to keep track of important Org
announcements such as new releases, confirmed bugs, help requests and
user-significant changes.

The information on this page only comes from interacting with the Org
mailing list.

To confirm a bug, just add =X-Woof-Bug: confirmed= in the headers of
your reply to the list.

See https://github.com/bzg/woof#usage for detailed usage explanations
and [[https://orgmode.org/list/87y2p6ltlg.fsf@bzg.fr/][Woof announcement]] on the list.

* What to do before posting a question

Please see the following FAQs:

- [[file:org-faq.org::#can-org-do-x][Can Org-mode do "x"? Does org have "x" feature?]]
- [[file:org-faq.org::#when-to-contact-mailing-list][What should I do before contacting the mailing list?]]
- [[file:org-faq.org::#ml-subscription-and-gmane][I read the mailing list through gmane. Should I subscribe?]]
- [[file:org-faq.org::#bug-reporting][I think my Org-mode is broken! How do I report a bug?]]

* What to do if you don't receive an answer
:PROPERTIES:
:CUSTOM_ID: i-didnt-receive-an-answer
:END:

If your email is referenced on [[https://updates.orgmode.org][updates.orgmode.org]], it will get the
attention of the maintainers when they have enough time.  (Remember
they work on a volunteer basis.)

If your email is not referenced there and you think it deserves more
attention, you can do this:

- If it is a bug report, check that you provided enough information,
  especially the Org and Emacs versions and a step-by-step recipe to
  reproduce the bug.

- If it is a question, give more information on what you tried, why
  you still have the question and why the answer may be of interest
  for other subscribers.

If you have nothing special to add to your first message and just want
to "bump" the thread, please wait at least *one month* before doing so.

See [[file:org-contribute.org::#what-can-I-expect][As a contributor, what can I expect?]] for more.

* COMMENT Statistics (as of sept. 19th 2010)

** Scope and method

Here are a few stats that I computed from the [[ftp://lists.gnu.org/emacs-orgmode/][lists.gnu.org]] server
archives.

I concatenated the archives into one single mbox file, then I used a
small utility called [[http://www.emacswiki.org/emacs/GnusStats][gnus-stat.el]].

** Posts

: Total number of posts: 30810
: Average bytes/post: -1.000000
: Total number of posters: 1402
: Average posts/poster: 21.975749

| Posts | Authors          |
|-------+------------------|
|  6325 | Carsten Dominik  |
|  1227 | Bastien          |
|  1169 | Bernt Hansen     |
|   806 | Sebastian Rose   |
|   762 | Eric Schulte     |
|   574 | Nick Dokos       |
|   474 | Eric S Fraga     |
|   431 | Samuel Wales     |
|   426 | Dan Davison      |
|   415 | Manish           |
|   386 | David Maus       |
|   374 | Leo              |
|   363 | Sébastien Vauban |
|   342 | Matthew Lundin   |
|   279 | Matt Lundin      |
|   271 | Adam Spiers      |
|   269 | Richard Riley    |
|   267 | Rainer Stengele  |
|   248 | Russell Adams    |
|   242 | Tassilo Horn     |

: Total number of subjects: 10085
: Average posts/subject: 3.055032

| # posts | Subject                                                             |
|---------+---------------------------------------------------------------------|
|      71 | [Orgmode] Re: Sourceforge community award                           |
|      56 | [Orgmode] Re: [ANN] Org-babel integrated into Org-mode              |
|      51 | [Orgmode] Re: Behavior of Gnus when called from an hyperlink        |
|      46 | [Orgmode] Re: IMPORTANT: (possibly) incompatible Change             |
|      45 | [Orgmode] depending TODOs, scheduling following TODOs automatically |
|      43 | [Orgmode] Beamer support in Org-mode                                |
|      39 | [Orgmode] Re: keys and command name info                            |
|      38 | [Orgmode] POLL: the 40 variables project                            |
|      35 | [Orgmode] Re: Org now fontifies code blocks                         |
|      34 | [Orgmode] Re: New beamer support                                    |
|      33 | [Orgmode] Re: POLL: Change of keys to move agenda through time      |
|      33 | [Orgmode] Re: org-mode on sloooow computer                          |
|      32 | [Orgmode] iPhone ----> org-mode                                     |
|      30 | [Orgmode] Re: Support (or not) for Emacs 21, and XEmacs             |
|      30 | [Orgmode] Re: DocBook exporter for Org-mode                         |
|      29 | [Orgmode] Poll: Who is using these commands                         |
|      29 | [Orgmode] Re: log on state change                                   |
|      28 | [Orgmode] Re: contact management in org-mode?                       |
|      28 | [Orgmode] property searches for #+CATEGORY                          |
|      28 | [Orgmode] XHTML export - &nbsp; etc.                                |
