#+OPTIONS:    H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+TITLE:      Org Glossary: Explanations of Basic Org-Mode Concepts and their Uses
#+AUTHOR:     Worg people
#+EMAIL:      bzg AT altern DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+INFOJS_OPT: view:overview toc:nil ltoc:t mouse:#cccccc buttons:0 path:http://orgmode.org/org-info.js

# This file is the default header for new Org files in Worg.  Feel free
# to tailor it to your needs.

[[file:index.org][{Back to Worg's index}]]

# Please feel free to add items or to complete any of the unfinished items.

* Agenda
  :PROPERTIES:
  :CUSTOM_ID: agenda
  :END: 

The agenda allows you to create filtered views of the items in your
[[#agenda-files][agenda files]]. These include "day-planner" views of your schedule,
lists of your todos, and the results of queries (for tags, words,
regular expressions, etc.). You might think of the agenda as a
combination of a task manager and really powerful search interface.

Within the agenda view, each item is linked to its location in your
files, so you can jump directly to that location from the agenda (by
pressing =TAB= or =RET=).

Provided you have followed the manual's instructions on setting up
org-mode and have designated some [[#agenda-files][agenda files]], simply type =C-c C-a=
(or =M-x org-agenda=) to gain access to the various views available.

Here are brief explanations of the options available

 - a (Agenda) :: Presents a view of today's (or, optionally, this
   week's) scheduled items, appointments, and upcoming deadlines.

 - t (Todo entries) :: Presents a list of all active [[#todo-keywords][todo
   keywords]] in your agenda files.

 - m (Match) :: Allows you to search your agenda files for headines
   with particular metadata (tags, properties, or TOD0s). 

     + The simplest way to query your files is to enter the name of a
       tag, e.g., "@computer".

     + To construct more advanced queries, please [[http://orgmode.org/manual/Matching-tags-and-properties.html][consult the manual]].

 - L (Timeline for current buffer) :: Shows a chronological view of all
   items with dates in the file you are currently visiting.

 - s (Search) :: Allows you to search entries in your agenda files for
   particular words or regular expressions.

 - / (multi-occur) :: Shows all lines in your agenda files matching a
   particular word.

 - < :: Restricts the agenda view to the file you are currently
   visiting.

   - << :: Restricts the agenda view to the subtree you are currently
     visiting.

The agenda is a powerful tool and there are many more possibilities of
[[http://orgmode.org/worg/org-tutorials/org-custom-agenda-commands.php][creating custom agenda commands]].
    
* Agenda files
  :PROPERTIES:
  :CUSTOM_ID: agenda-files
  :END:

These are the files that are used to generate your [[#agenda][agenda]] views. 

There are different ways to designate these files:

  1. Add a file manually with =C-c [= or =M-x
     org-agenda-file-to-front=). 
     
     - (Remove with =C-c ]= or =M-x org-remove-file=)

  2. Type =M-x customize-variable [RET] org-agenda-files= and enter
     the names of your agenda files.

     - If you enter a directory, all org files in that directory will
       be included in your agenda files.

** Tips: Organizing agenda files

One of the most common questions for new (and seasoned) users of
org-mode is how to organize agenda files. Should you put everything in
one big file organized by project? Should you create a new file for
each project? Or should you have separate "containers" for different
types of data: i.e., one file (or subtree) for appointments, one for
reference, one for todos, and so on.

The short answer: it doesn't matter. The agenda will be able to parse
and organize your TODOs, appointments, and deadlines no matter how
they are organized in your files.

Here's one recommendation: 

If you are using org-mode for the first time, the simplest approach
may be to use a single file and to enter projects or todos as the
appear. Then, whenever you review your file, reorganize your
todos and projects into "groupings" (i.e., trees) that make sense to
you. If a tree starts to get to big, then start a new file. Perhaps
you'll discover that you want to keep your "work" and "personal" tasks
in different files.

Perhaps the main consideration in organizing your files is to consider
[[#inheritance][inheritance]]. If you'd like a number of items to belong to the same
category or to have the same tags for easy agenda filtering, then they
probably belong in the same tree and/or file. 

An example:

If you'd like all your appointments to belong to the [[#category][category]] "appts",
then it probably doesn't make sense to scatter them as first level
headings among multiple

* Archive

Archiving is a way of hiding and/or getting rid of old or unwanted
items in your org files without deleting them altogether. 

Archiving works on trees in your org-file by doing the following:

  - Preventing them from opening when you cycle visibility with =TAB=
    or =Shift-TAB=. (They will stay closed unless you explictly open
    them with =Control-TAB=.)

  - Keeping them out of your [[#agenda][agenda]] views. (They will only be included
    if you type =v a= or =v A= in the agenda.)

There are three different ways to archiving an item/tree:

  1. C-c C-x a :: Mark the item as archived (i.e., give it an
     =:ARCHIVE:= tag) but leave it in its current location.

       - The headline remains visible in your org file but its contents
         will not open during cycling and it will not be included in
         the agenda.

  2. C-c C-x A :: Move the item to a separate archive headline within
     the current subtree.

       - This is useful for maintaining a clean org-file, since it
         removes archived headlines from view.

  3. C-c C-x C-s :: Moves the archive to a separate file. The default
     name of the file is =[filename].org_archive=. 

       - This is useful for getting rid of subtrees altogether. You
         might want to use this when you finish a project.

       - Since this is a relatively drastic action, org-mode offers an
         alternate version of the command (=C-u C-c C-x C-s=) that
         checks the subtree to make sure there are no active TODOs
         before archiving it.

** Uses

Archiving is very useful for keeping your org files free of clutter.
But which type of archiving should you use?

Here are a few ideas:

  - Use #1 when you'd like to archive an item but want to be
    reminded of its presence (e.g., to be reminded of a completed
    task) when you view your org file.

  - Use #2 when you want to remove an item from view but want it to
    remain together with its context (i.e., within the subtree). This
    is often useful for archiving TODO items that are part of an
    incomplete project.

  - Use #3 when you are sure you no longer require an item/subtree
    except for reference. This is often useful for archiving completed
    projects.

* Category

The CATEGORY designates the group an item belongs to. 

The CATEGORY is shown in the left hand column of the daily/weekly
agenda view.

: Day-agenda (W38):
: Wednesday  16 September 2009
:   badclient:  Scheduled:  TODO Call angry client to calm him down
:   appts:      Dinner at Julio's 

By default it is the name of the file to which an item belongs (minus
the extension).

You can specify a different CATEGORY for a file by placing the
following line at the top of your org file:

#+begin_src org
  ,#+CATEGORY: CompanyABC
#+end_src

Or, you can set a CATEGORY as the property of a [[#tree][tree]]. All items in
that tree will inherit (i.e., be labeled) with that category.

#+begin_src org
  ,* Birthdays
  ,  :PROPERTIES:
  ,  :CATEGORY: birthdays
  ,  :END:
#+end_src

** Uses

The main purpose of a category is to increase visibility in the agenda
--- i.e., to allow you to see which "group" an item belongs to. Thus,
many people find CATEGORIES useful for classifying their work.

Apart from visibility and compartmentalization, categories do not add
much additional functionality to an item. It is certainly *not*
necessary to set them for every file and/or heading.

You can search for items by CATEGORY in the agenda using the following
key sequence:

: C-c C-a m CATEGORY="birthdays"

In general, categories are *not* an efficient way of searching
for and/or filtering tasks. It is much faster to use tags or filetags
for this.

Here's one way to distinguish between categories and tags: an entry
can belong to only one category but it can have multiple tags.

* Entry
  :PROPERTIES:
  :CUSTOM_ID: entry
  :END:

An entry is the basic unit of data in org-mode. It consists of a
[[#headline][headline]], metadata (tags, todo keyword, properties, priority, etc.),
and whatever other text it contains.

An entry is to be distinguished from a [[#tree][tree]], which consists of all
headlines and entries beneath a particular entry within the outline
structure. Entries nested within other entries form a tree.

* Headline
  :PROPERTIES:
  :CUSTOM_ID: headline
  :END: 

A headline is the name for an outline heading in an org file.

Headlines begin with one or more asterisks. 

#+begin_src org
  ,* A headline
#+end_src

The "level" of a headline corresponds to the number of asterisks. The more asterisks,
the deeper the level in the outline.

#+begin_src org
  ,***** A "level 5" outline heading
#+end_src

As are all outlines, org-files are organized hierarchically. Deeper
headlines are "children" of higher-level "parent" headlines (and can
"inherit" their properties). Headlines on the same level are known as
siblings.

#+begin_src org
  ,* A parent
  ,** A child
  ,*** Sibling one (also a child of "A child")
  ,*** Sibling two
  ,*** Sibling three
#+end_src

You can move headlines (and their corresponding [[#entry][entries]]) by using the
cursor keys in conjunction with the =Meta= key.

 - =M-Left= and =M-Right= move the headline horizontally (i.e., change
   its level).

   - The org documentation often uses the terms "promote" and "demote"
     for this action.

 - =M-Up= and =M-Down= move the headline vertically.

You can easily jump to another headline using =M-x org-goto= (=C-c
C-j=).

You can easily "refile" a headline in a different location using =M-x
org-refile= (=C-c C-w=).

** Uses

The basic use of headings, of course, is to distinguish separate
sections within your outline and to organize them hierarchically.

The other major use of headings is as TODO "items" that appear in your
agenda.

The power of org-mode lies in its treatment of headlines as distinct
units of information to which you can attach all sorts of data ([[#todo-keywords][todo
keywords]], [[tag][tags]], priorities, timestamps, [[#property][properties]], and an unlimited
amount of text). This turns org-mode's deceptively simple outline
structure into a powerful "database" of information, in which units of
data can be nested within one another.


* Tree (subtree)
  :PROPERTIES:
  :CUSTOM_ID: tree
  :END:

A tree is created by the structure of an outline. It consists of a
heading and all subheadings/entries beneath it within the outline
hierarchy.

A tree is to be distinguished from an [[#entry][entry]]. Whereas an entry
indicates only a single headline and its data, a tree consists of
multiple nested entries. And, of course, subtrees are nested within
larger trees.

** TODO Uses

* Todo Keywords
  :PROPERTIES:
  :CUSTOM_ID: todo-keywords
  :END:

A TODO keyword is a small keyword at the beginning of a headline that
defines the TODO state of the entry. 

The default TODO keywords in org-mode are TODO and DONE. They are
automatically given nice colors to make them stand out.

#+begin_src org
  ,* DONE Check cupboard to see if I'm out of bread 
  ,  CLOSED: [2009-09-16 Wed 13:14] 
  ,* TODO Buy bread at the store
#+end_src

Org mode distinguishes between two types of keywords, active and
inactive (corresponding with the default TODO and DONE). By default,
active TODOs will be shown in [[#agenda][agenda views]]. Inactive todos will not.

You can select a TODO keyword by typing =C-c C-t= on an item. Or you
can move sequentially through TODOs by typing =Shift-Left= or
=Shift-Right=.

While the default keywords TODO and DONE will suffice for many users,
you can define your own TODO keywords (such as PROJECT, WAITING,
etc.) by following the instructions in the manual:

- http://orgmode.org/manual/TODO-Items.html

** Uses
   :PROPERTIES:
   :ID:       e0f76b6c-411f-4df1-88f5-445e11d9ca1d
   :END:

Not surprisingly, the most common use of TODO keywords is to indicate
items in your outline files that require action. Where other task
management systems often separate notes and todos, org-mode allows you
to mark items in your notes as todos.

Another common use of TODO keywords is to follow a single item through
an extended workflow. For instance, you might create a special TODO
keyword sequence for invoices by placing the following at the top of
your org file:

#+begin_src org
, #+SEQ_TODO: INVOICE(i) MAIL(m) WAITING(w) FOLLOWUP(f) | RECEIVED(r)
#+end_src

(The "|" separates active from inactive todos.)

You can combine such todo sequences with [[#logging][logging]] in order to keep a
record of when each event in the sequence happened.

* COMMENT Unfinished
** Agenda filtering
** Drawer

** Property

** CLOCK 

** Column view
** Cycling
** DEADLINE 
** Docstring
** Effort estimate
** Filetag
** Inheritance
** Project
** Tree (subtree)
** Note
** List 
  
** Level
** Logging
		     
** SCHEDULED 

** Table 

** Tag
** Timestamp

