#+OPTIONS:    H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) 
#+TITLE:      [No title for now, please update]
#+AUTHOR:     Worg people
#+EMAIL:      bzg AT altern DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg

# This file is the default header for new Org files in Worg.  Feel free
# to tailor it to your needs.

[[file:index.org][{Back to Worg's index}]]

* Contributing to Org

Every contribution to Org is very welcome.  Here is a list of areas where
your contribution will be useful:

- you can submit *bug reports* -- Before sending a bug report, make sure
  you have read this section of Org's manual: [[http://orgmode.org/org.html#Feedback][Feedback]]

- you can submit *feature requests* -- Org is already mature, but new ideas
  keep popping up.  If you want to request a feature, it might be a good
  idea to have a look at the current [[http://orgmode.org/todo.html][TODO list]] of Org, or to digg into the
  mailing list for possible previous discussions about your idea.

- you can submit *patches* -- You can submit patches to the mailing list.

  If your patch is against a file that is part of Emacs, then it won't be
  taken unless it is /less than 10 lines/ or you granted the rights on your
  works to the Free Software Foundation, Inc.
  
  If your patch is against a file that is not part of Emacs, then it might
  be taken without worrying about its length, if the patch is good.

- you can submit Org *add-ons* -- there are many Org add-ons.  The best way
  is to submit your code to the mailing list to discuss it with people.  If
  it is useful, you might consider contributing it to the =CONTRIB/=
  directory in the git repository.

- you can submit material to the *Worg* website -- This website is made of
  Org files that you can contribute to.  Learn what is Worg [[file:worg-about.org][about]] and how
  to contribute to it [[file:worg-git.org][through git]].

* Contributing to Emacs org-mode

Org is made of several files.  Those who are part of GNU Emacs are
copyrighted by the [[http://www.fsf.org][Free Software Foundation, Inc]].  If you consider
contributing to these files, your first need to grant the right to include
your works in GNU Emacs to the FSF.  For this you need to complete [[http://www.cognition.ens.fr/~guerry/u/request-assign-future.txt][this
form]] and send it to [[mailto:assign@gnu.org][assign@gnu.org]].

If you want to understand /why/, please read this: [[http://www.gnu.org/licenses/why-assign.html][Why the FSF gets
copyright assignments from contributors?]]

* Current contributors

Here is the list of people who signed the papers with the Free Software
Foundation and can now freely submit code to Org files that are included
within GNU Emacs:

- C. Dominik
- B. Guerry
- D. O'Toole
- P. Zielinski
- C. League
- J. Wiegley
- M. Figueroa

#+BEGIN: timestamp :string "Last update: " :format "%Y-%m-%d @ %H:%M"
Last update: 2008-02-10 @ 16:10
#+END:

#- Phil Jackson (will have FSF papers soon)
#- Sacha Chua (check about assignment, investigating....

