#+OPTIONS:    H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) 
#+TITLE:      How to contribute to Org?
#+AUTHOR:     Worg people
#+EMAIL:      bzg AT altern DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg

# This file is the default header for new Org files in Worg.  Feel free
# to tailor it to your needs.

[[file:index.org][{Back to Worg's index}]]

* Types of contributions

Every contribution to Org is very welcome.  Here is a list of areas where
your contribution will be useful:

- you can submit *bug reports* -- Before sending a bug report, make sure
  you have read this section of Org's manual: [[http://orgmode.org/org.html#Feedback][Feedback]]

- you can submit *feature requests* -- Org is already mature, but new
  ideas keep popping up.  If you want to request a feature, it might
  be a good idea to have a look at the current [[http://orgmode.org/worg/org-issues.php][Issue tracking file]]
  which captures both bug reports and feature requests.  Or dig into
  the mailing list for possible previous discussions about your idea.
  If you cannot find back your idea, formulate it as detailed as
  possible, if possible with examples, and send it to the mailing
  list.

- you can submit *patches* -- You can submit patches to the mailing list.

  If your patch is against a file that is part of Emacs, then your
  total contribution (all patches you submit) should change /less than
  20 lines/.  If you contribute more, you have to assign the copyright
  of your contribution to the Free Software Foundation (see below).
  
- you can submit Org *add-ons* -- there are many Org add-ons.  The best way
  is to submit your code to the mailing list to discuss it with people.  If
  it is useful, you might consider contributing it to the =CONTRIB/=
  directory in the git repository.

- you can submit material to the *Worg* website -- This website is made of
  Org files that you can contribute to.  Learn what Worg is [[file:worg-about.org][about]] and how
  to contribute to it [[file:worg-git.org][through git]].

* Copyright issues when contributing to Emacs org-mode

Org is made of many files.  Most of them are also distributed as part
of GNU Emacs.  These files are called the /Org core/, and they are all
copyrighted by the [[http://www.fsf.org][Free Software Foundation, Inc]].  If you consider
contributing to these files, your first need to grant the right to
include your works in GNU Emacs to the FSF.  For this you need to
complete [[http://orgmode.org/request-assign-future.txt][this form]] and send it to [[mailto:assign@gnu.org][assign@gnu.org]].  Some people
consider this a hassle.  I don't want to discuss this in detail here -
but by playing according to the Emacs rules, we gain the fantastic
advantage that every version of Emacs ships with Org-mode already
fully built in.  So please consider doing this - it makes our work as
maintainers so much easier, because we can then take your patches
without any additional work.

If you want to understand /why/ copyright assignments are collected,
read this: [[http://www.gnu.org/licenses/why-assign.html][Why the FSF gets copyright assignments from contributors?]]

* Preferred way of submitting patches

Org-mode is developed using /git/ as the version control system.  Git
provides an amazing framework to collaborate on a project.  Git can be
used to make patches and send them via email - this is fine for minor
changes.  These patches will be automatically registered at
[[http://patchwork.newartisans.com/project/org-mode][John Wiegley's patchwork server]] and will then be accepted, rejected,
or sent back to the author with a request for modification.

For more significant contributions, the best way to submit patches is
through public branches of your repository clone.

1. Clone our git repository at =http://repo.or.cz/w/org-mode.git=

2. Create a repository that can be publicly accessed, for example on
   /GitHub/, /repo.or.cz/, or on your own server.

3. Push your topic branches (and optionally the master branch) to your
   public repository.

   Define a remote for your public repository you push topics to.

   : git remote add REMOTE URL-GOES-HERE

   Push branches to the remote

   : git push REMOTE BRANCH1 [BRANCH2 BRANCH3 ...]

   e.g.

   : git remote add github ssh://.../     # Done once to define the remote 'github'
   : git push github my-topic

4. Do your work on topic-specific branches, using a branch name that
   relates to what you are working on.

5. Often do

   : git remote update

   to pull commits from all defined remote repositories, in particular
   the org-mode master at /repo.or.cz/.

6. When you have something workable, publish the git path and branch
   name on the mailing list, so that people can test it and review
   your work.

7. After your topic has been merged to the project master branch you
   can delete the topic on your local and remote repositories.

   : git branch -d NEWTOPIC
   : git push REMOTE :NEWTOPIC

* Current contributors
  :PROPERTIES:
  :CUSTOM_ID: contributors_with_fsf_papers
  :END:

Here is the list of people who signed the papers with the Free Software
Foundation and can now freely submit code to Org files that are included
within GNU Emacs:

1. Benjamin Andresen
2. Konstantin Antipin
3. Ian Barton
4. Thomas Baumann
5. Jan Böker
6. Lennart Borgman
7. Tom Breton
8. Baoqiu Cui
9. Sacha Chua
10. Dan Davison
11. Carsten Dominik
12. Adam Elliott
13. Miguel A. Figueroa-Villanueva
14. Mikael Fornius
15. Eric S. Fraga
16. Daniel M German
17. Bastien Guerry
18. Bernt Hansen
19. Magnus Henoch
20. Tomas Hlavaty
21. Tassilo Horn
22. Phil Jackson
23. Peter Jones
24. Tokuya Kameshima
25. Richard Klinda
26. Anthony Lander
27. Christopher League
28. David Maus
29. Ross Patterson
30. Martin Pohlack
31. Jason Riedy
32. Richard Riley
33. Philip Rooke
34. Sebastian Rose
35. Eric Schulte
36. Charles Sebold
37. Paul Sexton
38. James TD Smith
39. Ulf Stegemann
40. Lukasz Stelmach
41. Andy Steward
42. Christopher Suckling
43. David O'Toole
44. John Wiegley
45. Piotr Zielinski


#+BEGIN: timestamp :string "Last update: " :format "%Y-%m-%d @ %H:%M"
Last update: 06-04-2010 16:29
#+END:
