#+TITLE:      How to contribute to Org?
#+AUTHOR:     Worg people
#+EMAIL:      mdl AT imapmail DOT org
#+OPTIONS:    H:3 num:nil toc:t \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg

# This file is the default header for new Org files in Worg.  Feel free
# to tailor it to your needs.

[[file:index.org][{Back to Worg's index}]]

* Types of contributions

Every contribution to Org is very welcome.  Here is a list of areas
where your contribution will be useful:

- you can submit *bug reports* -- Before sending a bug report, make
  sure you have read this section of Org's manual: [[http://orgmode.org/org.html#Feedback][Feedback]] You can
  also read this great text: "[[http://www.chiark.greenend.org.uk/~sgtatham/bugs.html][How to Send Bug Reports Effectively]]"

- you can submit *feature requests* -- Org is already mature, but new
  ideas keep popping up.  If you want to request a feature, it might
  be a good idea to have a look at the current [[http://orgmode.org/worg/org-issues.html][Issue tracking file]]
  which captures both bug reports and feature requests.  Or dig into
  the mailing list for possible previous discussions about your idea.
  If you cannot find back your idea, formulate it as detailed as
  possible, if possible with examples, and send it to the mailing
  list.

- you can submit *patches* -- You can submit patches to the mailing
  list.  See the [[For Org contributors: preferred way of submitting patches][Preferred way of submitting patches]] section for
  details.  You can run =make test= to check that your patch does
  not introduce new bugs.

  If your patch is against a file that is part of Emacs, then your
  total contribution (all patches you submit) should change /less than
  15 lines/ (See the [[http://git.savannah.gnu.org/cgit/emacs.git/tree/CONTRIBUTE][CONTRIBUTE file in GNU Emacs]].)  If you
  contribute more, you have to assign the copyright of your
  contribution to the Free Software Foundation (see below).

- you can submit Org *add-ons* -- there are many Org add-ons.
  - The best way is to submit your code to [[file:org-mailing-list.org][the mailing list]] to discuss
    it with people.
  - If it is useful, you might consider contributing it to the
    =lisp/contrib/= directory in the git repository. It will be
    reviewed, and if it passes, it will be included. Ask help from
    [[file:org-people.org][Eric Schulte]] for this step. The =lisp/contrib/= directory is
    somehow relaxed: it is not distributed with Emacs, and does not
    require a formal copyright assignment.
  - If you decide to sign the [[*Copyright issues when contributing to
    Emacs Org mode][assignment contract with the FSF]], we
    might include your contribution in the distribution, and then in
    GNU Emacs.

- you can submit material to the *Worg* website -- This website is
  made of Org files that you can contribute to.  Learn what Worg is
  [[file:worg-about.org][about]] and how to contribute to it [[file:worg-git.org][through git]].

* Copyright issues when contributing to Emacs Org mode

Org is made of many files.  Most of them are also distributed as part
of GNU Emacs.  These files are called the /Org core/, and they are all
copyrighted by the [[http://www.fsf.org][Free Software Foundation, Inc]].  If you consider
contributing to these files, your first need to grant the right to
include your works in GNU Emacs to the FSF.  For this you need to
complete [[http://orgmode.org/request-assign-future.txt][this form]], and send it to [[mailto:assign@gnu.org][assign@gnu.org]].  The FSF will send
you the assignment contract that both you and the FSF will sign.
Please let the Org-mode maintainer know when this process is complete.
Some people consider this assignment process a hassle.  I don't want
to discuss this in detail here - there are some good reasons for
getting the copyright registered, an example is discussed in this
[[http://twit.tv/floss117][FLOSS weekly podcast]].  Furthermore, by playing according to the Emacs
rules, we gain the fantastic advantage that every version of Emacs
ships with Org-mode already fully built in.  So please consider doing
this - it makes our work as maintainers so much easier, because we can
then take your patches without any additional work.

If you want to learn more about /why/ copyright assignments are
collected, read this: [[http://www.gnu.org/licenses/why-assign.html][Why the FSF gets copyright assignments from
contributors?]]

By submitting patches to emacs-orgmode@gnu.org, or by pushing changes
to the Org-mode repository, you are placing these changes under the
same licensing terms as those under which GNU Emacs is published.

#+begin_example
 ;; GNU Emacs is free software: you can redistribute it and/or modify
 ;; it under the terms of the GNU General Public License as published by
 ;; the Free Software Foundation, either version 3 of the License, or
 ;; (at your option) any later version.
#+end_example

If at the time you submit or push these changes you do have active
copyright assignment papers with the FSF, for future changes to either
Org-mode or to Emacs, this means that copyright to these changes is
automatically transferred to the FSF.  The Org-mode repository is seen
as upstream repository for Emacs, anything contained in it can
potentially end up in Emacs.  If you do not have signed papers with
the FSF, only changes to files in the =contrib/= part of the
repository will be accepted, as well as very minor changes (so-called
/tiny changes/) to core files.  We will ask you to sign FSF papers at
the moment we attempt to move a =contrib/= file into the Org core, or
into Emacs.

* For Org developers
  :PROPERTIES:
  :CUSTOM_ID: devs
  :END:

1. Send your public key to [[mailto:bzgATgnuDOTorg][Bastien]]

2. Wait for confirmation that your public key has been added to the
   server.

3. Clone =org-mode.git= repository like this:
   : ~$ git clone orgmode@orgmode.org:org-mode.git

4. Commit your changes.

5. Run =make test=

6. If the tests pass, push your changes.

If you are undertaking big changes, please create a dedicated branch for
them.

* For Org contributors: preferred way of submitting patches
:PROPERTIES:
:CUSTOM_ID: patches
:END:

** Coding conventions

Org is part of Emacs, so any contribution should follow the [[http://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html][GNU Emacs
Lisp coding conventions]] described in Emacs manual.

** Sending patch with git

Org-mode is developed using /git/ as the version control system.  Git
provides an amazing framework to collaborate on a project.  Git can be
used to make patches and send them via email -- this is perfectly fine
for major and minor changes.

When sending a patch (either using =git diff= or =git format-patch=)
please *always add a properly formatted Emacs ChangeLog entry*.  See
[[id:c526dfd7-2b0c-4b66-9deb-6e442e48708c][this section]] for details on how to create such a ChangeLog.

** Sending commits

For every patch you send, we suggest to use =git format-patch=.

This is easy for small patches and more consequent ones.  Sometimes,
you might even want to work in several steps and send each commit
separately.  Here is the suggested workflow:

#+begin_quote
:   ~$ git pull                 # make sure your repo is up to date
:   ~$ git branch my-changes    # create a new branch from master
:   ~$ git checkout my-changes  # switch to this new branch

  ... make some changes (1) ...

:   ~$ git commit -a -m "This is change (1)"  # Commit your change

  ... make another change (2) ...

:   ~$ git commit -a -m "This is change (2)"  # Commit your change
:   ~$ git format-patch master                # Creates two patches

  ... Then two patches for your two commits are ready to be sent to the
  list.
#+end_quote

Write useful commit messages: please provide 1) a reason for it in
your email and 2) a ChangeLog entry in the commit message (see [[id:c526dfd7-2b0c-4b66-9deb-6e442e48708c][this
section]] on how to format a ChangeLog entry.)

** Sending quick fixes for testing purpose

If you want to send a quick fix that needs to be further tested by
other people (before you submit a real patch), here is how you can do:

#+begin_quote
  This command will make a patch between the staging area (in your
  computer), and the file you modified:

  : git diff -p org-whatever.el > org-whatever.el.diff

  If you already committed your changes to your index (staging area), then
  you should compare against a particular branch (in this example,
  origin/master):

  : git diff -p origin/master org-whatever.el > org-whatever.el.diff

  You email the output to the mailing list, adding =[PATCH]= to the
  subject, and description of what you fixed or changed.
#+end_quote

Note that small patches sent like this still need to have a ChangeLog
entry to be applied.  If your patch looks good to you, it's always
better to send a patch through =git format-patch=.

** Sharing changes from a public branch

For more significant contributions, the best way to submit patches is
through public branches of your repository clone.

1. Clone our git repository at =http://orgmode.org/w/org-mode.git=.
   You can clone using any of the commands below.

   : git clone git://orgmode.org/org-mode.git
   : git clone http://orgmode.org/org-mode.git

   The url using the git protocol is preferred. If you are behind a
   firewall that blocks ~git://~, you can use the http url.

2. Create a repository that can be publicly accessed, for example on
   /GitHub/, /repo.or.cz/, or on your own server.

3. Push your topic branches (and optionally the master branch) to your
   public repository.

   Define a remote for your public repository you push topics to.

   : git remote add REMOTE URL-GOES-HERE

   Push branches to the remote

   : git push REMOTE BRANCH1 [BRANCH2 BRANCH3 ...]

   e.g.

   : git remote add github ssh://.../     # Done once to define the remote 'github'
   : git push github my-topic

4. Do your work on topic-specific branches, using a branch name that
   relates to what you are working on.

5. Often do

   : git remote update

   to pull commits from all defined remote repositories, in particular
   the org-mode master at /repo.or.cz/.

6. When you have something workable, publish the git path and branch
   name on the mailing list, so that people can test it and review
   your work.

7. After your topic has been merged to the project master branch you
   can delete the topic on your local and remote repositories.

   : git branch -d NEWTOPIC
   : git push REMOTE :NEWTOPIC

The instructions above are generally useful to let people test new
features before sending the patch series to the mailing list, but the
patches remain the preferred way of receiving contributions.

* Commit messages and ChangeLog entries
  :PROPERTIES:
  :ID:       c526dfd7-2b0c-4b66-9deb-6e442e48708c
  :END:

We have decided to no longer keep a ChangeLog file to record changes
to individual functions.

A commit message should be constructed in the following way:

- Line 1 of the commit message should always be a short description of
  the overall change.  Line 1 does /not/ get a dot at the end and does
  not start with a star.  Generally, it starts with the filename that
  has been changed, followed by a colon.

- Line 2 is an empty line.

- In line 3, the ChangeLog entry should start.  A ChangeLog entry
  looks like [[http://orgmode.org/cgit.cgi/org-mode.git/commit/?id%3Dd49957ef021e256f19092c907d127390d39ec1ed][this]]:

  : * org-timer.el (org-timer-cancel-timer, org-timer-stop): Enhance
  : message.
  : (org-timer-set-timer): Use the number of minutes in the Effort
  : property as the default timer value. Three prefix arguments will
  : ignore the Effort value property.

- After the changelog, another empty line should come before any
  additional information that the committer wishes to provide in order
  to explain the patch.

- If the change is a minor change made by a committer without
  copyright assignment to the FSF, the commit message should also
  contain the cookie =TINYCHANGE= (anywhere in the message).  When we
  later produce the ChangeLog file for Emacs, the change will be
  marked appropriately.

- Variables and functions names are quoted like `this' (backquote and
  single quote).

- Sentences should be separated by two spaces.

- Sentences should start with an uppercase letter.

- Avoid the passive form: i.e., use "change" instead of "changed".

Here is an example for such a message:

#+begin_example
  org-capture.el: Fix the case of using a template file

  ,* lisp/org-capture.el (org-capture-set-plist): Make sure txt is a
  string before calling `string-match'.
  (org-capture-templates): Fix customization type.

  ,* doc/org.texi (Capture): Document using a file for a template.

  The problem here was that a wrong keyword was given in the
  customization type.  This let to a string-match against a list value.

  Modified from a patch proposal by Johan Friis.

  TINYCHANGE
#+end_example

If you are using /magit.el/ in Emacs, the ChangeLog for such entries
are easily produced by pressing =C= in the diff listing.

Another option to produce the entries is to use `C-x 4 a' in the
changed function or in the diff listing.  This will create entries in
the ChangeLog file, and you can then cut and paste these to the commit
message and remove the indentation.

* Copyrighted contributors to Org mode

Here is the list of people who have contributed actual code to the
Org-mode core.  Note that the manual contains a more extensive list
with acknowledgments, including contributed ideas!  The lists below
are mostly for house keeping, to help the maintainers keep track of
copyright issues.

** Current contributors
  :PROPERTIES:
  :CUSTOM_ID: contributors_with_fsf_papers
  :END:

Here is the list of people who signed the papers with the Free Software
Foundation and can now freely submit code to Org files that are included
within GNU Emacs:

1. Aaron Ecay
2. Abdó Roig-Maranges
3. Achim Gratz
4. Adam Elliott
5. Adam Spiers
6. Alan Schmitt
7. Alexey Lebedeff
8. Andreas Burtzlaff
9. Andreas Leha
10. Andrew Hyatt
11. Andrzej Lichnerowicz
12. Andy Steward
13. Anthony John Day
14. Anthony Lander
15. Arni Magnusson
16. Arun Isaac
17. Baoqiu Cui
18. Barry Leonard Gidden
19. Bastien Guerry
20. Benjamin Andresen
21. Bernd Grobauer
22. Bernt Hansen
23. Brian James Gough
24. Brice Waegenire
25. Carsten Dominik
26. Charles Berry
27. Charles Sebold
28. Christian Egli
29. Christian Moe
30. Christopher League
31. Christopher Miles Gray
32. Christopher Schmidt
33. Christopher Suckling
34. Clément Pit--Claudel
35. Dan Davison
36. Daniel M German
37. Daniel M. Hackney
38. David Arroyo Menéndez
39. David Maus
40. David O'Toole
41. Dieter Schoen
42. Dima Kogan
43. Dmitry Antipov
44. Don March
45. Eric Abrahamsen
46. Eric S. Fraga
47. Eric Schulte
48. Erik Hetzner
49. Erik Iverson
50. Ethan Ligon
51. Feng Shu
52. Francesco Pizzolante
53. Frederick Giasson
54. Gary Oberbrunner
55. Georg Lehner
56. George Kettleborough
57. Giovanni Ridolfi
58. Grégoire Jadi (aka Daimrod)
59. Gustav Wikström
60. Henning Dietmar Weiss
61. Ian Barton
62. Ian Kelling
63. Ilya Shlyakhter
64. Ippei Furuhashi
65. Jake Romer
66. James TD Smith
67. Jan Böcker
68. Jan Malakhovski
69. Jarmo Hurri
70. Jason Riedy
71. Jay Kerns
72. Jeffrey Ryan Horn
73. Joe Corneli
74. Joel Boehland
75. John Kitchin
76. John Wiegley
77. Jon Snader
78. Jonas Bernoulli
79. Jonathan Leech-Pepin
80. Juan Pechiar
81. Julian Gehring
82. Julien Barnier
83. Julien Danjou
84. Justin Gordon
85. Justus Piater
86. Karl Fogel
87. Kaushal Modi
88. Kodi Arfer
89. Konstantin Antipin
90. Kyle Meyer
91. Lambda Coder
92. Lawrence Mitchell
93. Le Wang
94. Lele Gaifax
95. Lennart Borgman
96. Leonard Avery Randall
97. Luis Anaya
98. Lukasz Stelmach
99. Madan Ramakrishnan
100. Magnus Henoch
101. Manuel Giraud
102. Marcin Borkowski
103. Marco Wahl
104. Martin Pohlack
105. Martyn Jago
106. Matt Lundin
107. Max Mikhanosha
108. Michael Albinus
109. Michael Brand
110. Michael Gauland
111. Michael Sperber
112. Miguel A. Figueroa-Villanueva
113. Mikael Fornius
114. Moritz Ulrich
115. Nathan Neff
116. Nicholas Dokos
117. Nicolas Berthier
118. Nicolas Goaziou
119. Nicolas Richard
120. Niels Giessen
121. Nikolai Weibull
122. Noorul Islam K M
123. Oleh Krehel
124. Paul Sexton
125. Pedro Alexandre Marcelino Costa da Silva
126. Peter Jones
127. Phil Hudson
128. Phil Jackson
129. Philip Rooke
130. Pieter Praet
131. Piotr Zielinski
132. Puneeth Chaganti
133. Rafael Laboissière
134. Rainer M Krug
135. Rasmus Pank Roulund
136. Richard Kim
137. Richard Klinda
138. Richard Riley
139. Rick Frankel
140. Russel Adams
141. Ryo Takaishi
142. Rüdiger Sonderfeld
143. Sacha Chua
144. Samuel Loury
145. Sebastian Rose
146. Sebastien Vauban
147. Sergey Litvinov
148. Seweryn Kokot
149. Simon Michael
150. Stephen Eglen
151. Steven Rémot
152. Suvayu Ali
153. T.F. Torrey
154. Tassilo Horn
155. Thibault Marin
156. Thierry Banel
157. Thomas Baumann
158. Thomas Holst
159. Thomas S. Dye
160. Thorsten Jolitz
161. Tim Burt
162. Titus von der Malsburg
163. Toby Cubitt
164. Tokuya Kameshima
165. Tom Breton
166. Tomas Hlavaty
167. Tony Day
168. Trevor Murphy
169. Ulf Stegemann
170. Vitalie Spinu
171. Yann Hodique
172. Yasushi Shoji
173. Yoshinari Nomura
174. Yuri D. Lensky
175. Zhang Weize
176. Zhuo Qingliang (Killy Draw)

** Processing

These people have been asked to sign the papers, and they are
currently considering it or a request is being processed by the FSF.

- Brian Carlson [2016-05-24 Tue]
- Bill Wishon
- Mats Kindahl (as of 2013-04-06) for [[http://mid.gmane.org/513BAB7D.1000603@oracle.com][this patch]]
- Georg Lehner (as of 2013-06-27)
- Kodi Arfer (as of 2013-06-29)

** Tiny Changes

These people have submitted tiny change patches that made it into Org
without FSF papers.  When they submit more, we need to get papers
eventually.  The limit is a cumulative change of 20 non-repetitive
change lines.  Details are given in [[http://www.gnu.org/prep/maintain/maintain.html#Legally-Significant ][this document]].

1. Aaron Jensen
2. Aman Yang
3. Andrew Burgess
4. Andy Lutomirski
5. Anthony Cowley
6. Arun Persaud
7. Aurélien Aptel
8. Austin Walker
9. Axel Kielhorn
10. Brian Carlson
11. Chunyang Xu
12. Craig Tanis
13. Derek Feichtinger
14. Eduardo Bellani
15. Eric Danan
16. Federico Beffa
17. Feng Zhou
18. Fernando Varesi
19. Florian Beck
20. Greg Tucker-Kellogg
21. Gregor Zattler
22. Hiroshi Saito
23. Ivan Vilata i Balaguer
24. Jacob Gerlach
25. Jacob Matthews
26. Jakob Lombacher
27. Jan Seeger
28. Jason Furtney
29. Joe Hirn
30. John Foerch
31. Jon Miller
32. Jonas Hörsch
33. Joost Diepenmaat
34. Kodi Arfer
35. Konstantin Kliakhandler
36. Leslie Harlley Watter
37. Lixin Chin
38. Luke Amdor
39. Mario Frasca
40. Martin Vuk
41. Matt Price
42. Matthew Gidden
43. Matthew MacLean
44. Michael O'Connor
45. Michael Strey
46. Michael Welle
47. Michael Weylandt
48. Mike McLean
49. Miro Bezjak
50. Moritz Kiefer
51. Muchenxuan Tong
52. Myles English
53. Myq Larson
54. Nathaniel Flath
55. Nick Gunn
56. Peter Feigl
57. Peter Moresi
58. Philip (Pip Cet)
59. Renato Ferreira
60. Richard Hansen
61. Richard Lawrence
62. Richard Y. Kim (Kim)
63. Robert P. Goldman
64. Roberto Huelga
65. Ruben Maher
66. Sami Airaksinen
67. Saulius Menkevičius
68. Sebastien Le Maguer
69. Sergey Gordienko
70. Stardiviner
71. Stefan-W. Hahn
72. Sylvain Chouleur
73. Teika Kazura
74. Thierry Pellé
75. Thomas Alexander Gerds
76. Thomas Rikl
77. Tom Hinton
78. Vicente Vera Parra
79. Viktor Rosenfeld
80. Vladimir Lomov
81. Wojciech Gac
82. Xi Shen
83. York Zhao
84. Zane D. Purvis

(This list may be incomplete - please help completing it.)

** No FSF assignment

These people cannot or prefer to not sign the FSF copyright papers,
and we can only accept patches that do not change the core files (the
ones that are also in Emacs).

Luckily, this list is still empty.

#+BEGIN: timestamp :string "Last update: " :format "%Y-%m-%d @ %H:%M"

#+END:
