#+TITLE:      Org Blogs and Wikis
#+AUTHOR:     Worg people
#+EMAIL:      mdl AT imapmail DOT org
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+OPTIONS:    H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc

[[file:index.org][{Back to Worg's index}]]

There is a strong desire to use Org-mode to manage both blogs and
wikis.  There are a number of tools which address parts of this need, this
page will serve as a collecting of the names of these tools with links and
brief descriptions.  I'm sure I've forgotten many relevant tools so *please
contribute*!

* Blogging tools

- [[http://renard.github.com/o-blog][o-blog]] :: Standalone blogging system that does not require any external
            software ([[http://renard.github.com/o-blog/features.html][features]], [[https://github.com/renard/o-blog][Github source]]).

- [[http://jekyllrb.com/][Jekyll]] :: a simple, blog aware, static site generator.  There are
            instructions for combining Org-mode with jekyll at [[file:org-tutorials/org-jekyll.org][Org-Jekyll]].

- [[http://orgmode.org/manual/Publishing.html][Projects]] :: In most cases using [[http://orgmode.org/manual/Publishing.html][Org-mode publishing projects]] with
     its many options should be sufficient for publishing a blog.

- [[file:blorgit.org][Blorgit]] :: publish an interactive website based on Org-mode
             documents.  While blorgit has many nice features including the
             fact that Org-mode documents can be edited through the web
             interface with automatic commits to a git or svn repository
             however it is fairly complicated to set up.  Blorgit is one or
             two small changes from being a full-fledged Org-mode based
             wiki.

- [[https://github.com/punchagan/blog-files][blog-files]] :: A simple system based on ideas and code from org-jekyll and
                reprise.py to publish a blog using simple static html
                pages. Used for publishing [[http://punchagan.muse-amuse.in/][this blog]] py Puneeth Chaganti.

- [[https://github.com/punchagan/org2blog][org2blog]] :: allows publishing directly from Org-mode to WordPress

- [[http://jaderholm.com/blog/blogging-with-org-mode-and-octopress][Org-mode and Octopress]] :: Instructions for blogging With Org-mode and
     Octopress.  There is also this [[https://github.com/craftkiller/orgmode-octopress][dedicated exporter]] by Tom Alexander
     (instructions [[http://blog.paphus.com/blog/2012/08/01/introducing-octopress-blogging-for-org-mode/][here]].)

- [[http://www.emacswiki.org/emacs/Blorg][Blorg]] :: the original Org-mode blogging engine (but it's not maintained
           anymore).  Roland Kaufmann is maintaining a fork [[https://github.com/RolKau/blorg][here]].

- [[http://comments.gmane.org/gmane.emacs.orgmode/45360][a blog-like sitemap for org-publish]] :: see [[http://comments.gmane.org/gmane.emacs.orgmode/45360][this post]] by Jon Anders
     Skorpen.

* Wiki tools

- [[http://ikiwiki.info/][ikiwiki]] is a web site compiler written in Perl.  In many ways it is
  similar to Jekyll, but has closer integration with version control
  systems.  It supports blogging and has many plugins.

  There is an org mode plugin by [[http://www.golden-gryphon.com/blog/manoj/blog/2008/06/08/Using_org-mode_with_Ikiwiki/][Manoj]], which lets you write your posts in
  org and converts them to html suitable for processing by ikiwiki.

  There is [[https://github.com/chrismgray/ikiwiki-org-plugin][another plugin]] by Chris Gray that interprets org files.  It
  is still under intermittent development, but is stable enough for
  general use.

* Other tools

- [[file:org-tutorials/org-ruby.org][org-ruby]] is a Ruby gem for converting org-mode files to HTML. The goal is
  to make it easier to use org-mode files in website tools like [[http://webby.rubyforge.org/][Webby]],
  [[http://jekyllrb.com/][Jekyll]], or [[http://webgen.rubyforge.org/][webgen]].

* More links

- [[http://emacs-fu.blogspot.com/2009/05/writing-and-blogging-with-org-mode.html][Writing and blogging with org-mode]]
- [[http://blog.herraiz.org/archives/241][Using Emacs org-mode for web publishing]]
