#+OPTIONS:    H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+TITLE:      Org Glossary -- list of Org terms and definitions
#+AUTHOR:     Worg people
#+EMAIL:      bzg AT altern DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg

# This file is the default header for new Org files in Worg.  Feel free
# to tailor it to your needs.

[[file:index.org][{Back to Worg's index}]]

# Please improve this very rough draft!
    
* Agenda
  :PROPERTIES:
  :CUSTOM_ID: agenda
  :END: 

* Todo Keywords
  :PROPERTIES:
  :CUSTOM_ID: todo-keywords
  :END:

A TODO keyword is a small keyword at the beginning of a headline that
defines the TODO state of the entry. 

The default TODO keywords in org-mode are TODO and DONE. They are
automatically given nice colors to make them stand out.

#+begin_src org
  ,* DONE Check cupboard to see if I'm out of bread 
  ,  CLOSED: [2009-09-16 Wed 13:14] 
  ,* TODO Buy bread at the store
#+end_src

Org mode distinguishes between two types of keywords, active and
inactive (corresponding with the default TODO and DONE). By default,
active TODOs will be shown in [[#agenda][agenda views]]. Inactive todos will not.

You can select a TODO keyword by typing =C-c C-t= on an item. Or you
can move sequentially through TODOs by typing =Shift-Left= or
=Shift-Right=.

While the default keywords TODO and DONE will suffice for many users,
you can define your own TODO keywords (such as PROJECT, WAITING,
etc.) by following the instructions in the manual:

- http://orgmode.org/manual/TODO-Items.html

** Uses

Not surprisingly, the most common use of TODO keywords is to indicate
items in your outline files that require action. Where other task
management systems often separate notes and todos, org-mode allows you
to mark items in your notes as todos.

Another common use of TODO keywords is to follow a single item through
an extended workflow. For instance, you might create a special TODO
keyword sequence for invoices by placing the following at the top of
your org file:

#+SEQ_TODO: INVOICE(i) MAIL(m) WAITING(w) FOLLOWUP(f) | RECEIVED(r)

(The "|" separates active from inactive todos.)

You can combine such todo sequences with LOGGING in order to keep a
record of when each event in the sequence happened.

* COMMENT Unfinished
** Archive

** Drawer

** Property

** Category

** CLOCK 

** Column view

** DEADLINE 

** Entry

** Project
   
** Note

** Headline 

** List 
  
** Logging
		     
** SCHEDULED 

** Table 

** Tag 

** Timestamp

