#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+TITLE:      Org Blogs and Wikis
#+AUTHOR:     Worg people
#+EMAIL:      bzg AT altern DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+OPTIONS:    H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc

[[file:index.org][{Back to Worg's index}]]

There is a strong desire to use Org-mode to manage both blogs and
wikis.  There are a number of tools which address parts of this need,
this page will serve as a collecting of the names of these tools with
links and brief descriptions.  I'm sure I've forgotten many relevant
tools so *please contribute*!

Blogging tools

- [[http://www.emacswiki.org/emacs/Blorg][Blorg]] is the original Org-mode blogging engine (but it's not
  maintained anymore).

- [[http://jekyllrb.com/][Jekyll]] is a simple, blog aware, static site generator.  There are
  instructions for combining Org-mode with jekyll at [[file:org-tutorials/org-jekyll.org][Org-Jekyll]].
- [[file:blorgit.org][Blorgit]] publishes an interactive website based on Org-mode
  documents.  While blorgit has many nice features including the fact
  that Org-mode documents can be edited through the web interface with
  automatic commits to a git or svn repository however it is fairly
  complicated to set up.  Blorgit is one or two small changes from
  being a full-fledged Org-mode based wiki.

Wiki tools
- [[http://ikiwiki.info/][ikiwiki]] is a web site compiler written in Perl. In many ways it is
  similar to Jekyll, but has closer integration with version control
  systems. It supports blogging and has many plugins.

  There is an org mode plugin by [[http://www.golden-gryphon.com/blog/manoj/blog/2008/06/08/Using_org-mode_with_Ikiwiki/][Manoj]], which lets you write your
  posts in org and converts them to html suitable for processing by
  ikiwiki.

Other tools
- [[file:org-tutorials/org-ruby.org][org-ruby]] is a Ruby gem for converting org-mode files to HTML. The
  goal is to make it easier to use org-mode files in website tools
  like [[http://webby.rubyforge.org/][Webby]], [[http://jekyllrb.com/][Jekyll]], or [[http://webgen.rubyforge.org/][webgen]].
