#+OPTIONS:    H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+TITLE:      Org Glossary: Explanations of Basic Org-Mode Features and their Uses
#+AUTHOR:     Worg people
#+EMAIL:      bzg AT altern DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg

# This file is the default header for new Org files in Worg.  Feel free
# to tailor it to your needs.

[[file:index.org][{Back to Worg's index}]]

# Please feel free to add items.

* Agenda
  :PROPERTIES:
  :CUSTOM_ID: agenda
  :END: 

The agenda allows you to create filtered views of the items in your
[[#agenda-files][agenda files]]. These include "day-planner" views of your schedule,
lists of your todos, and the results of queries (for tags, words,
regular expressions, etc.). You might think of the agenda as a
combination of a task manager and really powerful search interface.

Within the agenda view, each item is linked to its location in your
files, so you can jump directly to that location from the agenda (by
pressing =TAB= or =RET=).

Provided you have followed the manual's instructions on setting up
org-mode and have designated some [[#agenda-files][agenda files]], simply type =C-c C-a=
(or =M-x org-agenda=) to gain access to the various views available.

Here are brief explanations of the options available

 - a (Agenda) :: Presents a view of today's (or, optionally, this
   week's) scheduled items, appointments, and upcoming deadlines.

 - t (Todo entries) :: Presents a list of all active [[#todo-keywords][todo
   keywords]] in your agenda files.

 - m (Match) :: Allows you to search your agenda files for headines
   with particular metadata (tags, properties, or TOD0s). 

     + The simplest way to query your files is to enter the name of a
       tag, e.g., "@computer".

     + To construct more advanced queries, please [[http://orgmode.org/manual/Matching-tags-and-properties.html][consult the manual]].

 - L (Timeline for current buffer) :: Shows a chronological view of all
   items with dates in the file you are currently visiting.

 - s (Search) :: Allows you to search entries in your agenda files for
   particular words or regular expressions.

 - / (multi-occur) :: Shows all lines in your agenda files matching a
   particular word.

 - < :: Restricts the agenda view to the file you are currently
   visiting.

   - << :: Restricts the agenda view to the subtree you are currently
     visiting.

The agenda is a powerful tool and there are many more possibilities of
[[http://orgmode.org/worg/org-tutorials/org-custom-agenda-commands.php][creating custom agenda commands]].
    
* Agenda files
  :PROPERTIES:
  :CUSTOM_ID: agenda-files
  :END:

These are the files that are used to generate your [[#agenda][agenda]] views. 

There are different ways to designate these files:

  1. Add a file manually with =C-c [= or =M-x
     org-agenda-file-to-front=). 
     
     - (Remove with =C-c ]= or =M-x org-remove-file=)

  2. Type =M-x customize-variable [RET] org-agenda-files= and enter
     the names of your agenda files.

     - If you enter a directory, all org files in that directory will
       be included in your agenda files.

* Archive
* Category

The CATEGORY designates the group an item belongs to. 

The CATEGORY is shown in the left hand column of the daily/weekly
agenda view.

: Day-agenda (W38):
: Wednesday  16 September 2009
:   badclient:  Scheduled:  TODO Call angry client to calm him down
:   appts:      Dinner at Julio's 

By default it is the name of the file to which an item belongs (minus
the extension).

You can specify a different CATEGORY for a file by placing the
following line at the top of your org file:

#+begin_src org
  ,#+CATEGORY: CompanyABC
#+end_src

Or, you can set a CATEGORY as a property of a subtree. All items in
that subtree will inherit (i.e., be labeled) with that category.

#+begin_src org
  ,* Birthdays
  ,  :PROPERTIES:
  ,  :CATEGORY: birthdays
  ,  :END:
#+end_src

** Uses

The main purpose of a category is to increase visibility in the agenda
--- i.e., to allow you to see which "group" an item belongs to. Thus,
many people find CATEGORIES useful for classifying their work.

Apart from visibility and compartmentalization, categories do not add
much additional functionality to an item. It is certainly *not*
necessary to set them for every file and/or heading.

You can search for items by CATEGORY in the agenda using the following
key sequence:

: C-c C-a m CATEGORY="birthdays"

In general, categories are *not* an efficient way of searching
for and/or filtering tasks. It is much faster to use tags or filetags
for this.

* Headline 

A headline is the name for an outline heading in an org file.

Headlines begin with one or more asterisks. 

#+begin_src org
  ,* A headline
#+end_src

The more asterisks, the deeper the level in the outline.

#+begin_src org
  ,***** A "level 5" outline heading
#+end_src

As are all outlines, org-files are organized hierarchically. Deeper
headlines are "children" of higher-level "parent" headlines (and can
"inherit" their properties). Headlines on the same level are known as
siblings.

#+begin_src org
  ,* A parent
  ,** A child
  ,*** Sibling one (also a child of "A child")
  ,*** Sibling two
  ,*** Sibling three
#+end_src

* Todo Keywords
  :PROPERTIES:
  :CUSTOM_ID: todo-keywords
  :END:

A TODO keyword is a small keyword at the beginning of a headline that
defines the TODO state of the entry. 

The default TODO keywords in org-mode are TODO and DONE. They are
automatically given nice colors to make them stand out.

#+begin_src org
  ,* DONE Check cupboard to see if I'm out of bread 
  ,  CLOSED: [2009-09-16 Wed 13:14] 
  ,* TODO Buy bread at the store
#+end_src

Org mode distinguishes between two types of keywords, active and
inactive (corresponding with the default TODO and DONE). By default,
active TODOs will be shown in [[#agenda][agenda views]]. Inactive todos will not.

You can select a TODO keyword by typing =C-c C-t= on an item. Or you
can move sequentially through TODOs by typing =Shift-Left= or
=Shift-Right=.

While the default keywords TODO and DONE will suffice for many users,
you can define your own TODO keywords (such as PROJECT, WAITING,
etc.) by following the instructions in the manual:

- http://orgmode.org/manual/TODO-Items.html

** Uses

Not surprisingly, the most common use of TODO keywords is to indicate
items in your outline files that require action. Where other task
management systems often separate notes and todos, org-mode allows you
to mark items in your notes as todos.

Another common use of TODO keywords is to follow a single item through
an extended workflow. For instance, you might create a special TODO
keyword sequence for invoices by placing the following at the top of
your org file:

#+begin_src org
, #+SEQ_TODO: INVOICE(i) MAIL(m) WAITING(w) FOLLOWUP(f) | RECEIVED(r)
#+end_src

(The "|" separates active from inactive todos.)

You can combine such todo sequences with LOGGING in order to keep a
record of when each event in the sequence happened.

* COMMENT Unfinished
** Agenda filtering
** Drawer

** Property

** CLOCK 

** Column view
** DEADLINE 
** Docstring
** Effort inheritance
** Entry

** Inheritance
** Project
** Tree (subtree)
** Note
** List 
  
** Logging
		     
** SCHEDULED 

** Table 

** Tag 

** Timestamp

