#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+TITLE:      bbb:OrgMeetup
#+AUTHOR:     Ihor Radchenko
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+OPTIONS:    H:3 num:nil toc:nil \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc

# This file is released by its authors and contributors under the GNU
# Free Documentation license v1.3 or later, code examples are released
# under the GNU General Public License v3 or later.

* bbb:OrgMeetup: online meetup for all Org people

bbb:OrgMeetup is a monthly virtual meetup where you can talk with
Org mode developers and users.

- *URL* :: [[https://meet.jit.si/OrgMeetup][Jitsi]] +([[https://bbb.emacsverse.org/b/iho-h7r-qg8-led][BigBlueButton]])+
- *Next date* :: =<2025-01-08 Wed 19:00-21:00 @+03,Europe/Istanbul>=

- *Regular dates* :: Monthly, every second Wednesday of the month

  <%%(diary-float t 3 2)> in Org mode

- *Regular time* :: 7pm, Istanbul time

During the meetup, we:

- Give advice to new users
- Showcase Org configs or workflows
- Demo/discuss interesting packages
- Troubleshoot each-other's issues
- Discuss Org mode development
- Discuss "Org mode" section of Emacs news (https://sachachua.com/blog/)
- Discuss anything else Org-related

Everyone is free to join the discussion/chat or lurk around silently,
listening.

We do _not_ do any recording by default.

* Past meetup notes

- [[https://list.orgmode.org/877c7myc4v.fsf@localhost/T/#u][[[bbb:OrgMeetup]​] #14 on Wed, Dec 11, 2024, 19:00 UTC+3]]
  - rewriting =org-pcomplete= to provide documentation in completions,
    Babel redesign, linking between personal notes, =org-mouse=
    refactoring, automatic tangling/detangling as minor mode (WIP
    patch), searching Org heading (advanced) - =org-ql= + custom
    =helm= command, NYXT browser, getting magit into Emacs core,
    Awesome WM, displaying clocked in item in WM, envelope budgeting,
    customizing =C-c C-c=, capturing current context in capture
    templates, WIP Emacs feature: child frames in terminal Emacs,
    completion UIs; embark, transient, and designing new system for
    Org menus, concurrency in Elisp (past discussions and WIP async
    garbage collector)
- [[https://list.orgmode.org/875xnsem1e.fsf@localhost/T/#u][[[bbb:OrgMeetup]​] #13 on Wed, Nov 13, 2024, 19:00 UTC+3]]
  - contributing to Org, displaying todo keywords as UTF symbols,
    organizing notes in one large file, P.A.R.A., someday lists,
    dynamic blocks, different ways to search headings in Org, upcoming
    timezone syntax for timestamps, getting marker to link target, Org
    mode bug "tracker" (with RSS feeds), fancy Unicode symbols as
    modeline indicators, version-controlling Org files, mouse support
    when entering Org table formulas, problems with Org tables, ways
    to get multi-line table cells, live debugging of an Org bug, ODT
    rendering in MS Word vs. LibreOffice, exporting to proprietary
    formats, Org in corporate setting
- [[https://list.orgmode.org/878qubw5uo.fsf@localhost/T/#u][[[bbb:OrgMeetup]​] #12 on Wed, Oct  9, 2024, 19:00 UTC+3]]
  - live bug fixing, using stashes in magit workflows,
    =highlight-parentheses=, LaTeX previews outside Org mode, Emacs
    APAC meetup (more suitable Asia Pacific timezone), =org-persist=
    performance, URL link previews, Org mode and translation
    workflows, =org-transclusion=, update on Org refactoring project
    (paused), using transient in Org (and everywhere), mouse support
    for table formulas, inserting from clipboard into Org
- [[https://list.orgmode.org/87h69pttii.fsf@localhost][[[bbb:OrgMeetup]​] #11 on Wed, Sep 11, 2024, 19:00 UTC+3]]
  - diary style timestamps (for arbitrary repetition logic), table
    formulas inside dynamic block output, WIP feature branch
    implementing async garbage collector for Emacs (=scratch/igc=),
    =org-contrib=, WIP Org feature for async babel evaluation
    (=org-pending=), managing Org mailing list (and why mailing list
    and now bug tracker), Org capture templates, why =org-edna= don't
    need to be upstreamed, =calfw=, timezone support in Org,
    =emacs.ch= closure, search string support in id: links, managing
    PDFs in Emacs and Org, managing screenshots, =dired-filter= (part
    of =dired-hacks=)
- [[https://list.orgmode.org/orgmode/874j6zlhpu.fsf@localhost/][[[bbb:OrgMeetup]​] #10 on Wed, Aug 14, 2024, 19:00 UTC+3]]
  - status of LaTeX preview (how to help), DnD in Org, Org
    maintainer's Emacs config, update on Org mode refactoring project,
    what to do when Emacs is getting slower over time, Emacs memory
    usage, about =org-macs.el=, attachments in Org, automatically
    adding IDs to headings, backlinking, =casual= UI and various UI
    models in Emacs, Org tables and line wrapping, writing a custom
    plot type for =org-plot=, donations to support Org development and
    how they are set
- [[https://list.orgmode.org/87ed7tcphi.fsf@localhost/][[[bbb:OrgMeetup]​]  #9 on Wed, Jul 10, 2024, 19:00 UTC+3]]
  - bug reports, exporting to =docx=, differences between stable and
    development versions of Org, keynote export, WIP refactoring of
    =org-crypt=, calling a function from Library of Babel
- [[https://list.orgmode.org/87h6dlidhz.fsf@localhost/T/#u][[[bbb:OrgMeetup]​]  #8 on Wed, Jun 12, 2024, 19:00 UTC+3]]
  - status of some bug reports, more bug reports, =org-ql=
    vs. =helm-org-rifle=, automatic link description, update of WIP
    major changes in Org (large refactoring project), =org-agenda=
    speed, Org tables to use parser API (in the future), details on
    how asynchronous Org parser is implemented, extending Org syntax
    (and planned new features), preview capabilities beyond LaTeX
- [[https://list.orgmode.org/87edanyzme.fsf@localhost/][[[bbb:OrgMeetup]​]  #7 on Wed, Apr 24, 2024, 19:00 UTC+3]]
  - bug reports, status of async LaTeX preview, executing all src
    blocks in buffer for a given language, workflow for merging Org
    feature requests, =orderless=
- [[https://list.orgmode.org/87ttk9hbhv.fsf@localhost/T/#u][[[bbb:OrgMeetup]​]  #6 on Wed, Feb 14, 2024, 19:00 UTC+3]]
  - demo of extensions to Org export menu, more bug reports, dual
    keyword syntax, ~org-occur~
- [[https://list.orgmode.org/87fryho22t.fsf@localhost/T/#u][[[bbb:OrgMeetup]​]  #5 on Wed, Jan 17, 2024, 19:00 UTC+3]]
  - Org bug reports and a feature requests (with demo), timeline for
    next major Org release, crazy things done with Org, on the
    prospects of using (abusing?) SVG in Emacs and Org, markdown
    export, better completions in Org, Org-related talks in EmacsConf
    2023, Org mode testing workflow, Org + Guix for reproducible
    research, portability of ELC and ELN files (and mixed Org
    installs)
- [[https://list.orgmode.org/orgmode/87bkanr76o.fsf@localhost/][[[bbb:OrgMeetup]​]  #4 on Wed, Dec 13, 2023, 19:00 UTC+3]]
  - =ob-shell= development plans, PIM debt, Org mode on mobile,
    ncurses interface for Org mode (outside Emacs), Org mode support
    outside Emacs, =elfeed= (RSS) + Org mode
- [[https://list.orgmode.org/87edhtfpal.fsf@localhost/T/#m91207643ac9dd7bdb6f6374281f19d70a94893db][[[bbb:OrgMeetup]​]  #3 on Wed, Oct 11, 2023, 19:00 UTC+3]]
  - Khoj (Org mode + AI), configs for neovim users, =org-rich-yank=,
    tree-sitter and Org, highlighting code in texinfo export, Org mode
    as replacement for texinfo manuals (RMS), Karl Voit's podcast,
    customizing LaTeX export, Org mode on Android (via native Emacs),
    searching Emacs and Org mode mailing lists, on the meetup schedule
- [[https://list.orgmode.org/orgmode/878r97bzs4.fsf@localhost/][[[bbb:OrgMeetup]​]  #2 on Wed, Sep 13, 2023, 19:00 UTC+3]]
  - publishing cache, Org resources for beginners, Org use cases,
    submitting bug reports about Org, how Org mode is maintained using
    Org mode, knowledge base, storing bookmarks in Org, GTD in Org,
    email management in Org, displaying Org keywords as Unicode
    symbols, large vs. small Org files, synchronizing Org files across
    devices, HTML to org, alternative HTML export, reStructured text
    inside Org, Org mode + distraction-free browsing, managing large
    Emacs config, using hydra
- [[https://list.orgmode.org/877cq38gdt.fsf@localhost/][[[bbb:OrgMeetup]​]  #1 on Wed, Aug  9, 2023, 19:00 UTC+3]]
  - =ankifier=, =org-timeblock=, =clj-org-analyzer=, =calfw-blocks=,
    Elisp introduction, Awesome WM, WORG, LaTeX export, async LaTeX
    preview, completion in Org, collaborative editing, thesis in Org
    (in Arabic), right-to-left input methods, fringe indicators,
    =org-ql=
