#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+TITLE:      Worg maintainance
#+AUTHOR:     Worg people
#+EMAIL:      mdl AT imapmail DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+OPTIONS:    H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc

* Worg maintainer

[[file:users/bzg.org][Bastien]] set up Worg.

[[file:users/mlundin.org][Matt Lundin]] is the current maintainer.

** Maintainer role

- give push access to new contributors in [[http://orgmode.org/w/worg.git][worg.git]]
- access to the server and fix possible publishing issues from there

* Worg gardners

« Gardners » are people who take special care of directories, pages or
sections in Worg.

- Matt Lundin is taking special care of [[file:org-faq.org][Worg's FAQ]].
- David Maus is taking care of [[file:org-issues.org][org-issues.org]]
- [Adopt a directory/page here]

* Worg doesn't publish correctly - what to do?
  
** What need to be taken care of?

/Do we have to avoid certain constructs in the Org files to avoid the bug
to come back?/

Yes, when quoting examples (in org-issues.org or elsewhere), we need to be
careful about not including syntactic elements at the wrong place.

Also, exporting Worg is made using the last Org release, not the latest
Org version from git: so anything that is exportable with bleeding-edge
Org is not always exportable with the Org version on the server.

** How to track down a publishing problem?

From [[http://lists.gnu.org/archive/html/emacs-orgmode/2010-12/msg01181.html][Bastien's email]] (on 2010-12-24 Fri):

#+begin_quote
Here is how I tracked down the problem if it helps :

- I tried to export locally with latest Org (from git) to see where the
  export process stops: I found org-issues.org was the culprit

- I took a quick look at org-issues.org be couldn't spot the problem

- I then tried to export by first commenting out the 1st-level trees in
  org-issues.org except one: reiterated this till I found the ill-formed
  tree. 

- Then focus on this tree to find the problem.

Quick long and a bit too manual - but effective.
#+end_quote
* Preventing publishing errors

Locally export any document you edit as HTML (=C-c C-e H=) prior to
committing it to Worg and ensure the export process doesn't fail.  This
will be more reliable if you're running the latest version of Org.

You may also want to check the formatting in a browser before committing
your change (=C-c C-e b=).

* Troubleshooting publishing errors

If you notice Worg isn't updating, visit
http://orgmode.org/worg/publishing.txt and look for the export error
near the bottom to find the file where publishing stopped.  Locally
update to the latest version of Org, open that file, and try reproducing
the export error (=C-c C-e H=).  If it's not obvious where the problem is,
look at the most recent changes to the file in question:

: cd Worg
: git log -p org-quotes.org

Try reverting some of those changes and then re-test exporting (=C-c 
C-e H=).
