#+TITLE:      Worg maintenance
#+AUTHOR:     Worg people
#+EMAIL:      mdl AT imapmail DOT org
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+OPTIONS:    H:3 num:nil toc:nil \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc ':t
#+HTML_LINK_UP:    index.html
#+HTML_LINK_HOME:  https://orgmode.org/worg/

# This file is released by its authors and contributors under the GNU
# Free Documentation license v1.3 or later, code examples are released
# under the GNU General Public License v3 or later.

* Worg maintainers

Worg is currently maintained by Krupal and Corwin Brust.

Their role is to take care of [[https://code.orgmode.org/bzg/worg/][the Worg repository]] and to empower new
maintainers and contributors.

* How to contribute?

You can contribute by sending patches against the Worg repository to
the [[file:org-mailing-list.org][Org mailing list]].

: ~$ git clone https://code.orgmode.org/bzg/worg.git

If you want to contribute regularily, you can ask for commit access.
When you get it, you can clone the repository like this:

: ~$ git clone git@code.orgmode.org:bzg/worg.git

and push commits directly.

* Something went wrong

** Preventing publishing errors

Locally export any document you edit as HTML (=C-c C-e h H=) prior to
committing it to Worg and ensure the export process doesn't fail.
This will be more reliable if you're running the latest version of
Org.

You may also want to check the formatting in a browser before
committing your change (=C-c C-e h o=).

** Troubleshooting publishing errors

If you notice Worg isn't updating, visit [[https://orgmode.org/worg/publishing.txt][publishing.txt]] and look for
the export error near the bottom to find the file where publishing
stopped.  Locally update to the latest version of Org, open that file,
and try reproducing the export error (=C-c C-e h H=).  If it's not
obvious where the problem is, look at the most recent changes to the
file in question:

: cd Worg
: git log -p org-quotes.org

Try reverting some of those changes and then re-test exporting (=C-c
C-e h H=).
