#+TITLE:      Worg maintenance
#+AUTHOR:     Worg people
#+EMAIL:      mdl AT imapmail DOT org
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+OPTIONS:    H:3 num:nil toc:nil \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc ':t
#+HTML_LINK_UP:    index.html
#+HTML_LINK_HOME:  https://orgmode.org/worg/

# This file is released by its authors and contributors under the GNU
# Free Documentation license v1.3 or later, code examples are released
# under the GNU General Public License v3 or later.

* Worg maintainer

[[file:users/bzg.org][Bastien]] set up Worg but new maintainers are welcome!

The role of the maintainers is to allow new users and to monitor
commits made on [[https://code.orgmode.org/bzg/worg/][the Worg repository]].

* Worg doesn't publish correctly - what to do?

** What need to be taken care of?

/Do we have to avoid certain constructs in the Org files to avoid the
bug to come back?/

Yes, when quoting examples (in org-issues.org or elsewhere), we need
to be careful about not including syntactic elements at the wrong
place.

Also, exporting Worg is made using the last Org release, not the
latest Org version from git: so anything that is exportable with
bleeding-edge Org is not always exportable with the Org version on the
server.

** How to track down a publishing problem?

From [[http://lists.gnu.org/archive/html/emacs-orgmode/2010-12/msg01181.html][Bastien's email]] (on 2010-12-24 Fri):

#+begin_quote
Here is how I tracked down the problem if it helps :

- I tried to export locally with latest Org (from git) to see where
  the export process stops: I found org-issues.org was the culprit

- I took a quick look at org-issues.org be couldn't spot the problem

- I then tried to export by first commenting out the 1st-level trees
  in org-issues.org except one: reiterated this till I found the
  ill-formed tree.

- Then focus on this tree to find the problem.

Quick long and a bit too manual - but effective.
#+end_quote
* Preventing publishing errors

Locally export any document you edit as HTML (=C-c C-e h H=) prior to
committing it to Worg and ensure the export process doesn't fail.
This will be more reliable if you're running the latest version of
Org.

You may also want to check the formatting in a browser before
committing your change (=C-c C-e h o=).

* Troubleshooting publishing errors

If you notice Worg isn't updating, visit [[https://orgmode.org/worg/publishing.txt][publishing.txt]] and look for
the export error near the bottom to find the file where publishing
stopped.  Locally update to the latest version of Org, open that file,
and try reproducing the export error (=C-c C-e h H=).  If it's not
obvious where the problem is, look at the most recent changes to the
file in question:

: cd Worg
: git log -p org-quotes.org

Try reverting some of those changes and then re-test exporting (=C-c
C-e h H=).
