#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) 
#+TITLE:      I said: « Hello Worg! »
#+AUTHOR:     Worg people
#+EMAIL:      bzg AT altern DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+OPTIONS:   H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc

This is index page of Worg.  Worg is =Web-Org=: a website collectively
edited using [[http://www.orgmode.org][Org]] and maintained as a [[http://git.or.cz][git]] repository.

* But what is it, exactly?

[[http://www.orgmode.org][Org]] is an [[http://www.gnu.org/software/emacs/][Emacs]] mode for /keeping notes, maintaining to-do lists, and
doing project planning with a fast and effective plain-text system./ (as
the [[http://www.orgmode.org/org.html][Org manual]] says.)

Worg is an attempt to /collectively/ built a knowledge database about
[[http://orgmode.org][Org]], planning in plain text and other related topics.

* But... why?

Because Org makes it easy, fast and effective to edit *well-structured*
files.  Ever wanted to edit a table in a wiki?  Ever wanted to change
the sectioning structure in a wikipage?  Ever wanted to edit lists
quickly?  Now you can.

Because Org-mode makes *beautiful* documents : it support links, font
beautification, examples, etc.  Anything you can really expect from a
text editing tool.

Because Org is also a powerful *task-management system*.  Having such
facilities /inside a document/ make it easier to write together.

Because Org files can be exported to various formats (HTML, LaTeX).
Ever wanted to write LaTeX documents with people not knowing LaTeX?  
Now you can.

* So it's a bit like a wiki, no?

No.  Yes.  Kind of.  Here are a few differences:

- you edit the pages *using Emacs*, not a cheesy web interface;

- the Worg website (repository) is maintained using [[google:git%20cvs][git]];

- even if people are invited to merge their changes into the [[http://www.cognition.ens.fr/~guerry/worg/][main Worg
  website]], they are free to start a new Worgie of their own.  Using git
  makes Worg a *distributed* community website.

- there is important difference: Org is a very fast and effective plain
  text task-management system.  Meaning that you can add the Worg todo
  file (=worg-todo.org= in the Worg directory) to your =org-agenda-files= and
  see your list of task populated by tasks added by other people... 

* Who can participate?

Everyone with a minimal knowledge of Org (and Emacs) and git.  See the
page describing how to use [[file:worg-git.org][git for editing Worg]] for details.

* Do I need to register somewhere?

It's better to register on http://repo.or.cz/m/reguser.cgi/ but you can
also add changes to the Worg repository anonymously.

* So, what will be the content of this website?

Everything related to Org, project planning in plain text and the Org
community.

* Who are these people?

Worg was started by [[http://www.cognition.ens.fr/~guerry/][Bastien]] in the hope that other Org-ers around will
bite into this and start sharing tutorials, example of codes, etc.

* Ok, I want to start now!

The first thing you need to know is [[file:worg-git.org][how to use git for Worg]].  The second
thing you might be interested in are general advices and conventions on
how to [[file:worg_editing.org][let Worg grow]].




