#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+EMAIL:      bzg AT altern DOT org
#+TITLE:      How to edit Worg files?
#+AUTHOR:     Worg people
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+OPTIONS:    H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc

[[file:index.org][{Back to Worg's index}]]

Since Worg is just starting now, these conventions are just suggestions,
not recommendations.  Please improve this.

* Conventions
** To-do keywords

Here is a table with default to-do keywords and their meaning.

| To-do keyword | Meaning                                  |
|---------------+------------------------------------------|
| TODO(t)       | Things to do                             |
| INPROGRESS(i) | Thing being in the process of being done |
| WAITING(w@)   | Tasks stuck at some point                |
| DONE(d)       | Done task                                |
| CANCELED(c@)  | Canceled task                            |

Feel free to discuss the relevance of these keywords and propose
changes.

** Tags

: Write(w) Update(u) Fix(f) Check(c)

** Encoding
** Properties
** Link abbrevations
** Conventions about content?
** How rigit are these conventions?

(Suggestion: the farther from the index page you are, the more flexible
the conventions should perhaps be.)

* What is the default header for new files?

You can find a default header here: [[file:worg-header.org][worg-header.org]]

* How do I create a file?

Just create it.  Before committing changes in Worg, make sure you add
the file to the repository index with =git add *.org=

* What about dynamic blocks

If you are using dynamic blocks in Worg, please don't forget to add the
relevant code in the =elisp/worg.el= file.  See for example the dynamic
block for the timestamp in the [[file:index.org][index]] page.

* What about macros

If you are using macros, please add them to =macros.setupfile=.

** COMMENT Defined macros explained

*** Environments

    - BeginMiniPage ... EndMiniPage :: creates a mini page with a border. Used to
         demonstrate layouts (see: [[file:./org-tutorials/images-and-xhtml-export.org]] for
         an example).

    - BeginInfoBox ... EndInfoBox :: inserts a box with a little info icon on the
         left. The text inside flows around the icon. Both, info and warning boxes,
         use the styles for =.org-info-box= in [[file:worg.css::org-info-box][worg.css]].

    - BeginWarningBox ... EndWarningBox :: Like =BeginInfoBox= and =EndInfoBox=. The
         icon used is different.

    - BeginBlindText ... EndBlindText :: creates a =<span></span>= element, that
         greys out the text. Used for text, that is just there to fill paragraphs
         to demonstrate text flow (see:
         [[file:./org-tutorials/images-and-xhtml-export.org]] for an example).

* How do I link to the Org version of the file?
  The raw Org versions of the files are published [[http://orgmode.org/worg/sources/][here]].
* COMMENT How do I rename a file?
* COMMENT Can I create a directory?
* COMMENT What about non-org files in the repository?

.el files ?
.pdf files
