#+OPTIONS:    H:3 num:nil toc:t \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+TITLE:      Org configuration(s)
#+AUTHOR:     Worg people
#+EMAIL:      bzg AT altern DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg

# This file is released by its authors and contributors under the GNU
# Free Documentation license v1.3 or later, code examples are released
# under the GNU General Public License v3 or later.

# This file is the default header for new Org files in Worg.  Feel free
# to tailor it to your needs.

* GTD setups

#+index: GTD!Setup

- David O'Toole [[https://orgmode.org/worg/code/elisp/dto-org-gtd.el][GTD configuration file]]

* General Configuration/Customization

** Some useful keybindings

#+index: Keybindings

Here is a subset of my personal org-mode key-bindings that others may find
useful.

# please anyone else should feel free to edit/change/remove parts of
# this example

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 
            (lambda ()
              (local-set-key "\M-n" 'outline-next-visible-heading)
              (local-set-key "\M-p" 'outline-previous-visible-heading)
              ;; table
              (local-set-key "\C-\M-w" 'org-table-copy-region)
              (local-set-key "\C-\M-y" 'org-table-paste-rectangle)
              (local-set-key "\C-\M-l" 'org-table-sort-lines)
              ;; display images
              (local-set-key "\M-I" 'org-toggle-iimage-in-org)
              ;; fix tab
              (local-set-key "\C-y" 'yank)))
#+end_src

References and explanations of the above:

- see [[*iimage%20in%20org%20(display%20images%20in%20org%20files)][*iimage in org (display images in org files)]] for an explanation of
  the =org-toggle-iimage-in-org= function (inline images in org-mode
  files).

** iimage in org (display images in org files)

Thanks to many on the mailing list for this great addition to
Org-Mode.  See [[http://www.netlaputa.ne.jp/~kose/Emacs/iimage.html][iimage]] for information on =iimage-minor-mode=.

#+begin_src emacs-lisp
  (add-to-list 'iimage-mode-image-regex-alist
               (cons (concat "\\[\\[file:\\(~?" iimage-mode-image-filename-regex
                             "\\)\\]")  1))
  
  (defun org-toggle-iimage-in-org ()
    "display images in your org file"
    (interactive)
    (if (face-underline-p 'org-link)
        (set-face-underline-p 'org-link nil)
        (set-face-underline-p 'org-link t))
    (iimage-mode ‘toggle))
#+end_src
** Capture templates
*** Capture a TODO task to make a [[https://gist.github.com/PhilHudson/a6dd1b7e0b606799cc5d][phone call to a BBDB contact]] 

