#+TITLE:      Org-mode for developers
#+AUTHOR:     Worg people
#+EMAIL:      mdl AT imapmail DOT org
#+STARTUP:    align fold nodlcheck hidestars oddeven intestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+OPTIONS:    H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc

* Org-mode for developers

This page gather links to reference documentation and (forthcoming)
tutorials on how to extend Org.

* Git workflow

As of March 20th (see [[http://article.gmane.org/gmane.emacs.orgmode/53608/match%3Dnew%2Bgit%2Bworkflow][this email]]), Org development uses a three-branches
git workflow.

- master :: This branch contains latest development for Org.  Temporary
            feature branch (either local or remote) should branch out from
            this branch.  This branch is merged to the =maint= branch when
            there is a major release.

- maint :: This branch is the "production" branch for Org.  It contains
           only releases.  No branch should branch out from it, and it is
           *never* merged into another branch.  The Org version on this
           branch is the one regularily sync'ed with Emacs repository.

- hotfix-7.8.06 :: This branch is the hotfix branch for the latest release.

** Future changes

In the near future, the =maint= branch will probably be renamed =release=
and the =hotfix-7.8.06= will probably be renamed =hotfix=.  The role of the
branches won't change.

** Git repositories

The git repository for Org is on =orgmode.org=: 

- http://orgmode.org/w/org-mode.git

This repository is cloned on =repo.or.cz=:

- http://repo.or.cz/w/org-mode.git

You can display a graphic representation of the branches here:

- http://repo.or.cz/git-browser/by-commit.html?r=org-mode.git

# * TODO Merging into Emacs repository

# We try to merge Org with Emacs regularily.

* Reference documentation

- [[file:org-export-reference.org][reference documentation]] for the new export engine (=org-export.el=)
  written by Nicolas Goaziou.
