#+TITLE:      Org-mode for developers
#+AUTHOR:     Worg people
#+EMAIL:      mdl AT imapmail DOT org
#+STARTUP:    align fold nodlcheck hidestars oddeven intestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+OPTIONS:    H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc

* Org-mode for developers

This page gather links to reference documentation and (forthcoming)
tutorials on how to extend Org.

* Git workflow

Org development uses a two-branches git workflow.

- master :: This branch contains latest development for Org.  Temporary
            feature branch (either local or remote) should branch out from
            this branch.  This branch is merged to the =maint= branch when
            there is a major release.

- maint :: This branch is the "production" branch for Org.  It contains
           stable releases and bug fixes against them.  This branch is
           merged into master when bug are fixed there first.  The Org
           version on this branch is the one regularily sync'ed with Emacs
           repository.

** Git repositories

The git repository for Org is on =orgmode.org=:

- http://orgmode.org/w/org-mode.git

If you are a developer, you can clone this branch like this:

: ~$ git clone orgsync@orgmode.org:org-sync.git

This repository is cloned on =repo.or.cz=:

- http://repo.or.cz/w/org-mode.git

You can display a graphic representation of the branches here:

- http://repo.or.cz/git-browser/by-commit.html?r=org-mode.git

# * TODO Merging into Emacs repository

# We try to merge Org with Emacs regularily.

* Reference documentation

- [[file:org-export-reference.org][Reference documentation]] for the new export engine (=org-export.el=)
  written by Nicolas Goaziou.

- [[../org-api/index.org][Org-mode API]] with signatures and docstrings for all public functions of
  all Org-mode libraries.
  
