#+OPTIONS:    H:3 num:nil toc:1 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:nil skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) 
#+TITLE:      Org-babel: Uses
#+AUTHOR:     Thomas S. Dye
#+EMAIL:      tsd at tsdye dot com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:  index.php
#+LINK_HOME: http://orgmode.org/worg/

* Introduction
  This page collects examples of using Org-babel in a variety of
  contexts. Contributions of further examples from Org-babel users are
  very welcome.

* [[file:examples/data-collection-analysis.org][Data Collection and Analysis]]
  This example uses Org-babel to automate a repeated data-collection
  and analysis task.  A Ruby code block is used to scrape data from
  the output of a computational experiment.  This data is then written
  to an Org-mode table.  A block of R code reads from this table and
  calculates lines of fit.  Finally a block of gnuplot code is used to
  graph the results of both the raw data and the R analysis.  By
  performing all of these steps within an Org-mode document working
  notes, discussion, and TODOs can be naturally interspersed with the
  code, and the results can easily be published to HTML or PDF for
  distribution.
* [[file:examples/research-project.org][A Research Project]]
  
  A research project typically produces one or more documents that
  describe or rely upon:
  - a data collection
  - computations and code used in data analysis or simulation
  - methodological conventions and assumptions
  - decisions among alternate analytic paths

  The documents produced by a research project typically stand apart
  from the things they describe and rely upon, which makes it
  difficult for other researchers to understand fully or to reproduce
  the results of the research project.
 
  A software solution to this problem was proposed by Gentleman and
  Temple Lang, who "introduce the concept of a /compendium/ as both a
  container for the different elements that make up the document and
  its computations (i.e. text, code, data, ...), and as a means for
  distributing, managing and updating the collection."

  Org-babel and Org-mode provide the tools needed to create a
  compendium in one Org-mode file.  This example is taken from a work
  in progress, one that has seen many changes in structure and
  organization.  No claim is made that it is the best way to do
  things.  But it works and is proving extremely useful in the conduct
  of the research project.

* [[http://www.stats.ox.ac.uk/~davison/software/org-babel/drift.org.html][Teaching evolution using R]]
  This example is a tutorial on simulating evolution in R. It contains
  examples of diagrams generated with =ditaa=, LaTeX, and graphics
  generated with R.

  A good way to see how org-babel functions to create the tutorial is
  to view the [[http://www.stats.ox.ac.uk/~davison/software/org-babel/drift.org.html][htmlized org buffer]]. This also provides an example of
  how images and latex-generated mathematical notation can be viewed
  inline in emacs. The HTML export version is [[file:examples/drift.org][here]].
* [[file:examples/latex-form.org][A LaTeX Form]]
  This example uses Org-babel as a user interface for a LaTeX form
  that might be used by the members of an organization.  It uses the
  literate programming facility of Org-babel to isolate the user from
  the sometimes arcane LaTeX constructs needed to create a
  highly-structured form.  Org-babel can tangle multiple documents in
  a single Org-mode file, and this ability is used to create a
  distribution version of the form separate from one designed for the
  file cabinet.
* [[file:examples/short-report.org][A Standardized Short Report]]
  This example is similar to the previous one, but here the users are
  expected to write substantial content.  This type of workflow might
  be used by a small organization whose employees regularly produce
  standard documents and where the writing tasks for any one document
  are divided among the authors.  

  The HTML export facility of Org-mode is used to produce a guide to
  writing the standardized short report.  This HTML file can be used
  to train new authors.  The Org-mode content also supplies
  substantial direction to experienced authors as they write.
  Org-mode keywords and tags are used to keep track of writing
  assignments and progress.  Org-babel's literate programming facility
  makes it possible to present writing tasks to the authors in an order
  different from which they appear in the report.
