#+OPTIONS:    H:3 num:nil toc:1 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:nil skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) 
#+TITLE:      Org-babel: Uses
#+AUTHOR:     Thomas S. Dye
#+EMAIL:      tsd at tsdye dot com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:  index.php
#+LINK_HOME: http://orgmode.org/worg/

* Introduction
  This page collects examples of using Org-babel in a variety of
  contexts. Contributions of further examples from Org-babel users are
  very welcome.

* [[file:examples/data-collection-analysis.org][Data Collection and Analysis]]
  This example uses Org-babel to automate a repeated data-collection
  and analysis task.  A Ruby code block is used to scrape data from
  the output of a computational experiment.  This data is then written
  to an Org-mode table.  A block of R code reads from this table and
  calculates lines of fit.  Finally a block of gnuplot code is used to
  graph the results of both the raw data and the R analysis.  By
  performing all of these steps within an Org-mode document working
  notes, discussion, and TODOs can be naturally interspersed with the
  code, and the results can easily be published to HTML or PDF for
  distribution.

* [[http://www.stats.ox.ac.uk/~davison/software/org-babel/drift.org.html][Teaching evolution using R]]
  This example is a tutorial on simulating evolution in R. It contains
  examples of diagrams generated with =ditaa=, LaTeX, and graphics
  generated with R.

  A good way to see how org-babel functions to create the tutorial is
  to view the [[http://www.stats.ox.ac.uk/~davison/software/org-babel/drift.org.html][htmlized org buffer]]. This also provides an example of
  how images and latex-generated mathematical notation can be viewed
  inline in emacs. The HTML export version is [[file:examples/drift.org][here]].

* [[file:examples/latex-form.org][A LaTeX Form]]
  This example uses Org-babel as a user interface for a LaTeX form
  that might be used by the members of an organization.  It uses the
  literate programming facility of Org-babel to isolate the user from
  the sometimes arcane LaTeX constructs needed to create a
  highly-structured form.  Org-babel can tangle multiple documents in
  a single Org-mode file, and this ability is used to create a
  distribution version of the form separate from one designed for the
  file cabinet.

* [[file:examples/short-report.org][A Standardized Short Report]]
  This example is similar to the previous one, but here the users are
  expected to write substantial content.  This type of workflow might
  be used by a small organization whose employees regularly produce
  standard documents and where the writing tasks for any one document
  are divided among the authors.  

  The HTML export facility of Org-mode is used to produce a guide to
  writing the standardized short report.  This HTML file can be used
  to train new authors.  The Org-mode content also supplies
  substantial direction to experienced authors as they write.
  Org-mode keywords and tags are used to keep track of writing
  assignments and progress.  Org-babel's literate programming facility
  makes it possible to present writing tasks to the authors in an order
  different from which they appear in the report.

** Requirement
   - A working LaTeX installation.

** Advantages
   - The integration of training material with in-file instruction can
     be quite effective.
   - Many authors find it easy to work from the bottom up, or from the
     particular to the general, rather than the usual sequence of
     general-particular-general found in reports.

** Disadvantages
   - None?

** Example
   - This report must satisfy the requirements set out in [[http://hawaii.gov/dlnr/hpd/pdfs/revproc_har/275_284/pdfs/278.pdf][the Historic
     Preservation Division rule]].
   - Complete each of the TODO items.
   - Mark each item DONE when you have completed it.
   - =C-c a t= will make an agenda of items left to do in this
     document.
   - =C-c a m= YOURNAME will make an agenda of writing tasks assigned
     to you.
   
*** TODO Field Methods
**** TODO Include the following information: [1/7]
      - [X] When the fieldwork was carried out.
      - [ ] Who directed the fieldwork.
      - [ ] The names and qualifications of crew members.
      - [ ] Establishment of site datum and grid.
      - [ ] Excavation tools.
      - [ ] Assignment of contexts.
      - [ ] Bag list.
**** DONE Include a citation to the project plan.
     :LOGBOOK:
     - State "DONE"       from "TODO"       [2009-11-25 Wed 09:53]
     :END:

#+srcname: field-methods
#+begin_src latex
  \section{Field Methods}
  \label{sec:field-methods}
  
  % Enter text below this line.

  Fieldwork for the project was carried out between December 26, 2008
  and February 3, 2009 following an approved plan \cite{plan}.
#+end_src   

*** TODO Results
    - Note the use of Org-mode tags to assign sections to authors Veronica and Eric.
    - Discuss the artifacts and midden recovered during excavation.


**** TODO Artifacts						   :Veronica:
     :LOGBOOK:
     - State "TODO"       from "DONE"       [2009-11-25 Wed 09:44]
     - State "DONE"       from "TODO"       [2009-11-25 Wed 09:44]
     :END:
     - Use Sinoto's classification of one-piece fishhooks.
     - Cite Anell when describing two-piece fishhooks.
     - Use Emory's classification of adzes when describing
       cross-section.
#+srcname: artifacts
#+begin_src latex
  \subsection{Description of Artifacts}
  \label{sec:artifact-description}
  
  % Enter text below this line
#+end_src

**** TODO Midden						       :Eric:
     - Use Kay for identifying and naming marine shells
     - Cite Ziegler for information on fish habitats
#+srcname: midden
#+begin_src latex
  \subsection{Midden}
  \label{sec:midden}
  
  % Enter text below this line
#+end_src

**** No data entry beyond this line

#+srcname: results
#+begin_src latex :noweb
  \section{Results}
  \label{sec:results}
  
  This section presents the results of excavation.
  
  <<artifacts>>
  
  <<midden>>
#+end_src


*** TODO Introduction
    - Give the reader a brief overview of the project and its results.

#+srcname: intro
#+begin_src latex
  \section{Introduction}
  \label{sec:introduction}
  
  % Text below this line
#+end_src
*** No data entry beyond this line
    - The LaTeX code here sets up the environment and inserts the
      defined source code blocks in their report order.
    - A call to =org-babel-tangle= produces the LaTeX report document.

#+begin_src latex :noweb :tangle report.tex
  \documentclass{article}
  \begin{document}
  <<intro>>
  <<field-methods>>
  <<results>>
  \bibliographystyle{apa} 
  \bibliography{mybib}
  \end{document}
#+end_src



* [[file:examples/research-project.org][A Research Project]]
  
  A research project typically produces one or more documents that
  describe or rely upon:
  - a data collection
  - computations and code used in data analysis or simulation
  - methodological conventions and assumptions
  - decisions among alternate analytic paths

  The documents produced by a research project typically stand apart
  from the things they describe and rely upon, which makes it
  difficult for other researchers to understand fully or to reproduce
  the results of the research project.
 
  A software solution to this problem was proposed by Gentleman and
Temple Lang, who "introduce the concept of a /compendium/ as both a
container for the different elements that make up the document and its
computations (i.e. text, code, data, ...), and as a means for
distributing, managing and updating the collection."

Org-babel and Org-mode provide the tools needed to create a compendium
in one Org-mode file.  This example is taken from a work in progress,
one that has seen many changes in structure and organization.  No
claim is made that it is the best way to do things.  But it works and
is proving extremely useful in the conduct of the research project.
