#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

* Org-Toc API functions 8org-toc.el)
** org-toc-before-first-heading-p  

Before first heading?


** org-toc-columns  

Toggle columns view in the Org buffer from Org TOC.


** org-toc-cycle-base-buffer  

Call /org-cycle/ with a prefix argument in the base buffer.


** org-toc-cycle-subtree  

Locally cycle a headline through two states: 'children and
'folded


** org-toc-follow-mode  

Toggle follow mode in a /org-toc-mode/ buffer.


** org-toc-get-headlines-status  

Return an alist of headlines and their associated folding
status.


** org-toc-goto =&optional jump cycle=

From Org TOC buffer, follow the targeted subtree in the Org window.
If =jump= is non-nil, go to the base buffer.
If =jump= is 'delete, go to the base buffer and delete other windows.
If =cycle= is non-nil, cycle the targeted subtree in the Org window.


** org-toc-help  

Display a quick help message in the echo-area for /org-toc-mode/.


** org-toc-info  

Show properties of current subtree in the echo-area.


** org-toc-info-mode  

Toggle info mode in a /org-toc-mode/ buffer.


** org-toc-jump =&optional delete=

From Org TOC buffer, jump to the targeted subtree in the Org window.
If =delete= is non-nil, delete other windows when in the Org buffer.


** org-toc-mode  

A major mode for browsing the table of contents of an Org buffer.

key             binding
---             -------

C-c             Prefix Command
SPC             org-toc-goto
1               ??
2               ??
3               ??
4               ??
:               org-toc-cycle-subtree
?               org-toc-help
S               org-toc-show-subtree-mode
c               org-toc-columns
f               org-toc-follow-mode
g               org-toc-restore-config
i               org-toc-info-mode
n               org-toc-next
p               org-toc-previous
q               org-toc-quit
r               org-toc-recenter-mode
s               org-toc-store-config
v               org-toc-jump
x               org-toc-quit
<C-S-iso-lefttab>               org-toc-cycle-base-buffer
<C-tab>         ??
<down>          org-toc-next
<left>          org-toc-previous
<return>        ??
<right>         org-toc-next
<tab>           org-toc-jump
<up>            org-toc-previous

C-c C-o         org-open-at-point



** org-toc-next  

Go to the next headline of the TOC.


** org-toc-previous  

Go to the previous headline of the TOC.


** org-toc-quit  

Quit the current Org TOC buffer.


** org-toc-recenter-mode =&optional line=

Toggle recenter mode in a /org-toc-mode/ buffer. If =line= is
specified, then make /org-toc-recenter/ use this value.


** org-toc-restore-config  

Get the stored status in /org-toc-config-alist/ and set the
current table of contents to it.


** org-toc-show =&optional depth position=

Show the table of contents of the current Org-mode buffer.


** org-toc-show-subtree-mode  

Toggle show subtree mode in a /org-toc-mode/ buffer.


** org-toc-store-config  

Store the current status of the tables of contents in
/org-toc-config-alist/.
