#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

* Org-Inline-Task API functions (org-inlinetask.el)
** org-inlinetask-at-task-p  

Return true if point is at beginning of an inline task.


** org-inlinetask-demote  

Demote the inline task at point.
If the task has an end part, also demote it.


** org-inlinetask-export-handler  

Handle headlines with level larger or equal to /org-inlinetask-min-level/.
Either remove headline and meta data, or do special formatting.


** org-inlinetask-fontify =limit=

Fontify the inline tasks down to =limit=.


** org-inlinetask-get-current-indentation  

Get the indentation of the last non-while line above this one.


** org-inlinetask-get-task-level  

Get the level of the inline task around.
This assumes the point is inside an inline task.


** org-inlinetask-goto-beginning  

Go to the beginning of the inline task at point.


** org-inlinetask-goto-end  

Go to the end of the inline task at point.
Return point.


** org-inlinetask-in-task-p  

Return true if point is inside an inline task.


** org-inlinetask-insert-task =&optional no-state=

Insert an inline task.
If prefix arg =no-state= is set, ignore /org-inlinetask-default-state/.


** org-inlinetask-outline-regexp  

Return string matching an inline task heading.
The number of levels is controlled by /org-inlinetask-min-level/.


** org-inlinetask-promote  

Promote the inline task at point.
If the task has an end part, promote it.  Also, prevents level from
going below /org-inlinetask-min-level/.


** org-inlinetask-remove-END-maybe  

Remove an END line when present.


** org-inlinetask-toggle-visibility  

Toggle visibility of inline task at point.

