#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

* Org-MHE API functions (org-mhe.el)
** org-mhe-follow-link =folder article=

Follow an MH-E link to =folder= and =article=.
If =article= is nil =folder= is shown.  If the configuration variable
/org-mhe-search-all-folders/ is t and /mh-searcher/ is pick,
=article= is searched in all folders.  Indexed searches (swish++,
namazu, and others supported by MH-E) will always search in all
folders.


** org-mhe-get-header =header=

Return the field for =header= of the message in folder mode.
This will create a show buffer for the corresponding message.  If
you have a better idea of how to do this then please let us know.


** org-mhe-get-message-folder  

Return the name of the current message folder.
Be careful if you use sequences.


** org-mhe-get-message-folder-from-index  

Return the name of the message folder in an index folder buffer.


** org-mhe-get-message-num  

Return the number of the current message.
Be careful if you use sequences.


** org-mhe-get-message-real-folder  

Return the name of the real folder for the current message.
So if you use sequences, it will now work.


** org-mhe-open =path=

Follow an MH-E message link specified by =path=.


** org-mhe-store-link  

Store a link to an MH-E folder or message.

