#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

* Org-Mime API functions (org-mime.el)
** org-mime-change-class-style =class style=

Set new default htlm style for objects with classs==lass= in
exported html.


** org-mime-change-element-style =element style=

Set new default htlm style for <=element=> elements in exported html.


** org-mime-file =ext path id=

Markup a file for attachment.


** org-mime-htmlize =arg=

Export a portion of an email body composed using /mml-mode/ to
html using /org-mode/.  If called with an active region only
export that region, otherwise export the entire body.


** org-mime-multipart =plain html &optional images=

Markup a multipart/alternative with text/plain and text/html alternatives.
If the html portion of the message includes images wrap the html
and images in a multipart/related part.


** org-mime-org-buffer-htmlize  

Create an email buffer containing the current org-mode file
#+begin_src emacs-lisp
  exported to html and encoded in both html and in org formats as
  mime alternatives.
#+end_src



** org-mime-replace-images =str current-file=

Replace images in html files with cid links.


** org-mime-subtree  

Create an email buffer containing the current org-mode subtree
#+begin_src emacs-lisp
  exported to a org format or to the format specified by the
  MAIL_FMT property of the subtree.
#+end_src

