#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

* Org-E-Latex API functions (org-e-latex.el)
** org-e-latex-bold =bold contents info=

Transcode =bold= from Org to LaTeX.
=contents= is the text with bold markup.  =info= is a plist holding
contextual information.


** org-e-latex-center-block =center-block contents info=

Transcode a =center-block= element from Org to LaTeX.
=contents= holds the contents of the center block.  =info= is a plist
holding contextual information.


** org-e-latex-clock =clock contents info=

Transcode a =clock= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual
information.


** org-e-latex-code =code contents info=

Transcode a =code= object from Org to LaTeX.
=contents= is nil.  =info= is a plist used as a communication
channel.


** org-e-latex-collect-errors =buffer=

Collect some kind of errors from "pdflatex" command output.

=buffer= is the buffer containing output.

Return collected error types as a string, or nil if there was
none.


** org-e-latex-compile =texfile=

Compile a TeX file.

=texfile= is the name of the file being compiled.  Processing is
done through the command specified in /org-e-latex-pdf-process/.

Return PDF file name or an error if it couldn't be produced.


** org-e-latex-drawer =drawer contents info=

Transcode a =drawer= element from Org to LaTeX.
=contents= holds the contents of the block.  =info= is a plist
holding contextual information.


** org-e-latex-dynamic-block =dynamic-block contents info=

Transcode a =dynamic-block= element from Org to LaTeX.
=contents= holds the contents of the block.  =info= is a plist
holding contextual information.  See /org-export-data/.


** org-e-latex-entity =entity contents info=

Transcode an =entity= object from Org to LaTeX.
=contents= are the definition itself.  =info= is a plist holding
contextual information.


** org-e-latex-example-block =example-block contents info=

Transcode an =example-block= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual
information.


** org-e-latex-export-block =export-block contents info=

Transcode a =export-block= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-export-snippet =export-snippet contents info=

Transcode a =export-snippet= object from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-export-to-latex =&optional subtreep visible-only body-only ext-plist pub-dir=

Export current buffer to a LaTeX file.

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

When optional argument =subtreep= is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument =visible-only= is non-nil, don't export
contents of hidden elements.

When optional argument =body-only= is non-nil, only write code
between "\begin{document}" and "\end{document}".

=ext-plist=, when provided, is a property list with external
parameters overriding Org default settings, but still inferior to
file-local settings.

When optional argument =pub-dir= is set, use it as the publishing
directory.

Return output file's name.


** org-e-latex-export-to-pdf =&optional subtreep visible-only body-only ext-plist pub-dir=

Export current buffer to LaTeX then process through to PDF.

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

When optional argument =subtreep= is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument =visible-only= is non-nil, don't export
contents of hidden elements.

When optional argument =body-only= is non-nil, only write code
between "\begin{document}" and "\end{document}".

=ext-plist=, when provided, is a property list with external
parameters overriding Org default settings, but still inferior to
file-local settings.

When optional argument =pub-dir= is set, use it as the publishing
directory.

Return PDF file's name.


** org-e-latex-fixed-width =fixed-width contents info=

Transcode a =fixed-width= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-footnote-reference =footnote-reference contents info=

Transcode a =footnote-reference= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-headline =headline contents info=

Transcode an =headline= element from Org to LaTeX.
=contents= holds the contents of the headline.  =info= is a plist
holding contextual information.


** org-e-latex-horizontal-rule =horizontal-rule contents info=

Transcode an =horizontal-rule=  object from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-inline-src-block =inline-src-block contents info=

Transcode an =inline-src-block= element from Org to LaTeX.
=contents= holds the contents of the item.  =info= is a plist holding
contextual information.


** org-e-latex-inlinetask =inlinetask contents info=

Transcode an =inlinetask= element from Org to LaTeX.
=contents= holds the contents of the block.  =info= is a plist
holding contextual information.


** org-e-latex-italic =italic contents info=

Transcode =italic= from Org to LaTeX.
=contents= is the text with italic markup.  =info= is a plist holding
contextual information.


** org-e-latex-item =item contents info=

Transcode an =item= element from Org to LaTeX.
=contents= holds the contents of the item.  =info= is a plist holding
contextual information.


** org-e-latex-keyword =keyword contents info=

Transcode a =keyword= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-latex-environment =latex-environment contents info=

Transcode a =latex-environment= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-latex-fragment =latex-fragment contents info=

Transcode a =latex-fragment= object from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-line-break =line-break contents info=

Transcode a =line-break= object from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-link =link desc info=

Transcode a =link= object from Org to LaTeX.

=desc= is the description part of the link, or the empty string.
=info= is a plist holding contextual information.  See
/org-export-data/.


** org-e-latex-macro =macro contents info=

Transcode a =macro= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-paragraph =paragraph contents info=

Transcode a =paragraph= element from Org to LaTeX.
=contents= is the contents of the paragraph, as a string.  =info= is
the plist used as a communication channel.


** org-e-latex-plain-list =plain-list contents info=

Transcode a =plain-list= element from Org to LaTeX.
=contents= is the contents of the list.  =info= is a plist holding
contextual information.


** org-e-latex-plain-text =text info=

Transcode a =text= string from Org to LaTeX.
=text= is the string to transcode.  =info= is a plist holding
contextual information.


** org-e-latex-planning =planning contents info=

Transcode a =planning= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual
information.


** org-e-latex-property-drawer =property-drawer contents info=

Transcode a =property-drawer= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual
information.


** org-e-latex-quote-block =quote-block contents info=

Transcode a =quote-block= element from Org to LaTeX.
=contents= holds the contents of the block.  =info= is a plist
holding contextual information.


** org-e-latex-quote-section =quote-section contents info=

Transcode a =quote-section= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-radio-target =radio-target text info=

Transcode a =radio-target= object from Org to LaTeX.
=text= is the text of the target.  =info= is a plist holding
contextual information.


** org-e-latex-section =section contents info=

Transcode a =section= element from Org to LaTeX.
=contents= holds the contents of the section.  =info= is a plist
holding contextual information.


** org-e-latex-special-block =special-block contents info=

Transcode a =special-block= element from Org to LaTeX.
=contents= holds the contents of the block.  =info= is a plist
holding contextual information.


** org-e-latex-src-block =src-block contents info=

Transcode a =src-block= element from Org to LaTeX.
=contents= holds the contents of the item.  =info= is a plist holding
contextual information.


** org-e-latex-statistics-cookie =statistics-cookie contents info=

Transcode a =statistics-cookie= object from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-strike-through =strike-through contents info=

Transcode =strike-through= from Org to LaTeX.
=contents= is the text with strike-through markup.  =info= is a plist
holding contextual information.


** org-e-latex-subscript =subscript contents info=

Transcode a =subscript= object from Org to LaTeX.
=contents= is the contents of the object.  =info= is a plist holding
contextual information.


** org-e-latex-superscript =superscript contents info=

Transcode a =superscript= object from Org to LaTeX.
=contents= is the contents of the object.  =info= is a plist holding
contextual information.


** org-e-latex-table =table contents info=

Transcode a =table= element from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-latex-table-cell =table-cell contents info=

Transcode a =table-cell= element from Org to LaTeX.
=contents= is the cell contents.  =info= is a plist used as
a communication channel.


** org-e-latex-table-row =table-row contents info=

Transcode a =table-row= element from Org to LaTeX.
=contents= is the contents of the row.  =info= is a plist used as
a communication channel.


** org-e-latex-target =target contents info=

Transcode a =target= object from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual
information.


** org-e-latex-template =contents info=

Return complete document string after LaTeX conversion.
=contents= is the transcoded contents string.  =info= is a plist
holding export options.


** org-e-latex-timestamp =timestamp contents info=

Transcode a =timestamp= object from Org to LaTeX.
=contents= is nil.  =info= is a plist holding contextual
information.


** org-e-latex-underline =underline contents info=

Transcode =underline= from Org to LaTeX.
=contents= is the text with underline markup.  =info= is a plist
holding contextual information.


** org-e-latex-verbatim =verbatim contents info=

Transcode a =verbatim= object from Org to LaTeX.
=contents= is nil.  =info= is a plist used as a communication
channel.


** org-e-latex-verse-block =verse-block contents info=

Transcode a =verse-block= element from Org to LaTeX.
=contents= is verse block contents. =info= is a plist holding
contextual information.
