#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

* Org-Beamer API functions (org-beamer.el)
** org-beamer-after-initial-vars  

Find special settings for beamer and store them.
The effect is that these values will be accessible during export.


** org-beamer-allowed-property-values =property=

Supply allowed values for BEAMER properties.


** org-beamer-amend-header  

Add /org-beamer-header-extra/ to the LaTeX header.
If the file contains the string BEAMER-HEADER-EXTRA-HERE on a line
by itself, it will be replaced with /org-beamer-header-extra/.  If not,
the value will be inserted right after the documentclass statement.


** org-beamer-auto-fragile-frames  

Mark any frames containing verbatim environments as fragile.
This function will run in the final LaTeX document.


** org-beamer-cleanup-column-width =width=

Make sure the width is not empty, and that it has a unit.


** org-beamer-fix-toc  

Fix the table of contents by removing the vspace line.


** org-beamer-get-special =props=

Extract an option, action, and default action string from text.
The variables org-beamer-option, org-beamer-action, org-beamer-defaction,
org-beamer-extra are all scoped into this function dynamically.


** org-beamer-initialize-open-trackers  

Reset variables that track if certain environments are open during export.


** org-beamer-mode =&optional arg=

Special support for editing Org-mode files made to export to beamer.


** org-beamer-place-default-actions-for-lists  

Find default overlay specifications in items, and move them.
The need to be after the begin statement of the environment.


** org-beamer-property-changed =property value=

Track the BEAMER_env property with tags.


** org-beamer-sectioning =level text=

Return the sectioning entry for the current headline.
=level= is the reduced level of the headline.
=text= is the text of the headline, everything except the leading stars.
The return value is a cons cell.  The car is the headline text, usually
just =text=, but possibly modified if options have been extracted from the
text.  The cdr is the sectioning entry, similar to what is given
in org-export-latex-classes.


** org-beamer-select-beamer-code  

Take code marked for BEAMER and turn it into marked for LaTeX.


** org-beamer-select-environment  

Select the environment to be used by beamer for this entry.
While this uses (for convenience) a tag selection interface, the result
of this command will be that the BEAMER_env *property* of the entry is set.

In addition to this, the command will also set a tag as a visual aid, but
the tag does not have any semantic meaning.

