#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

* Org-BBDB API functions (org-bbdb.el)
** org-bbdb-anniv-export-ical  

Extract anniversaries from BBDB and convert them to icalendar format.


** org-bbdb-anniv-extract-date =time-str=

Convert YYYY-MM-DD to (month date year).
Argument =time-str= is the value retrieved from BBDB.  If YYYY- is omitted
it will be considered unknown.


** org-bbdb-anniv-split =str=

Split multiple entries in the BBDB anniversary field.
Argument =str= is the anniversary field in BBDB.


** org-bbdb-anniversaries  

Extract anniversaries from BBDB for display in the agenda.


** org-bbdb-complete-link  

Read a bbdb link with name completion.


** org-bbdb-export =path desc format=

Create the export version of a BBDB link specified by =path= or =desc=.
If exporting to either HTML or LaTeX =format= the link will be
italicized, in all other cases it is left unchanged.


** org-bbdb-make-anniv-hash  

Create a hash with anniversaries extracted from BBDB, for fast access.
The anniversaries are assumed to be stored /org-bbdb-anniversary-field/.


** org-bbdb-open =name=

Follow a BBDB link to =name=.


** org-bbdb-store-link  

Store a link to a BBDB database entry.


** org-bbdb-updated =rec=

Record the fact that BBDB has been updated.
This is used by Org to re-create the anniversary hash table.

