#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

* Org-Babel-Comint API Functions (ob-comint.el)
** org-babel-comint-buffer-livep =buffer=

Check if =buffer= is a comint buffer with a live process.


** org-babel-comint-eval-invisibly-and-wait-for-file =buffer file string &optional period=

Evaluate =string= in =buffer= invisibly.
Don't return until =file= exists. Code in =string= must ensure that
=file= exists at end of evaluation.


** org-babel-comint-in-buffer =buffer &rest body=

Check =buffer= and execute =body=.
=buffer= is checked with /org-babel-comint-buffer-livep/.  =body= is
executed inside the protection of /save-excursion/ and
/save-match-data/.


** org-babel-comint-input-command =buffer cmd=

Pass =cmd= to =buffer=.
The input will not be echoed.


** org-babel-comint-wait-for-output =buffer=

Wait until output arrives from =buffer=.
Note: this is only safe when waiting for the result of a single
statement (not large blocks of code).


** org-babel-comint-with-output =meta &rest body=

Evaluate =body= in BUFFER and return process output.
Will wait until EOE-INDICATOR appears in the output, then return
all process output.  If REMOVE-ECHO and FULL-=body= are present and
non-nil, then strip echo'd body from the returned output.  =meta=
should be a list containing the following where the last two
elements are optional.

#+begin_src emacs-lisp
 (BUFFER EOE-INDICATOR REMOVE-ECHO FULL-=body=)
#+end_src

This macro ensures that the filter is removed in case of an error
or user /keyboard-quit/ during execution of body.


