#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

* Org-Wikinodes API functions (org-wikinodes.el)
** org-wikinodes-activate-links =limit=

Activate CamelCase words as links to Wiki targets.


** org-wikinodes-add-to-font-lock-keywords  

Add wikinode CamelCase highlighting to /org-font-lock-extra-keywords/.


** org-wikinodes-clear-cache-when-on-target  

When on a headline that is a Wiki target, clear the cache.


** org-wikinodes-clear-direcory-targets-cache  

Clear the cache where to find wiki targets.


** org-wikinodes-follow-link =target=

Follow a wiki link to =target=.

This need to be found as an exact headline match, either in the current
buffer, or in any .org file in the current directory, depending on the
variable /org-wikinodes-scope/.

If a target headline is not found, it may be created according to the
setting of /org-wikinodes-create-targets/.


** org-wikinodes-get-links-for-directory =dir=

Return an alist that connects wiki links to files in directory =dir=.


** org-wikinodes-get-targets  

Return a list of all wiki targets in the current buffer.


** org-wikinodes-open-at-point  

Check if the cursor is on a Wiki link and follow the link.

This function goes into /org-open-at-point-functions/.


** org-wikinodes-process-links-for-export  

Process Wiki links in the export preprocess buffer.

Try to find target matches in the wiki scope and replace CamelCase words
with working links.


** org-wikinodes-which-file =target &optional directory=

Return the file for wiki headline =target= =directory=.
If there is no such wiki target, return nil.
