#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport


* Org-Bibtex API functions (org-bibtex.el)
** org-bibtex =&optional filename=

Export each headline in the current file to a bibtex entry.
Headlines are exported using /org-bibtex-export-headline/.


** org-bibtex-autokey  

Generate an autokey for the current headline


** org-bibtex-check =&optional optional=

Check the current headline for required fields.
With prefix argument =optional= also prompt for optional fields.


** org-bibtex-check-all =&optional optional=

Check all headlines in the current file.
With prefix argument =optional= also prompt for optional fields.


** org-bibtex-create =&optional arg nonew=

Create a new entry at the given level.
With a prefix arg, query for optional fields as well.
If nonew is t, add data to the headline of the entry at point.


** org-bibtex-create-in-current-entry =&optional arg=

Add bibliographical data to the current entry.
With a prefix arg, query for optional fields.


** org-bibtex-export-to-kill-ring  

Export current headline to kill ring as bibtex entry.


** org-bibtex-fleshout =type &optional optional=

Fleshout the current heading, ensuring that all required fields are present.
With optional argument =optional=, also prompt for optional fields.


** org-bibtex-headline  

Return a bibtex entry of the given headline as a string.


** org-bibtex-open =path=

Visit the bibliography entry on =path=.


** org-bibtex-read  

Read a bibtex entry and save to /*org-bibtex-entries*/.
This uses /bibtex-parse-entry/.


** org-bibtex-search =string=

Search for bibliographical entries in agenda files.
This function relies /org-search-view/ to locate results.


** org-bibtex-store-link  

Store a link to a BibTeX entry.


** org-bibtex-write  

Insert a heading built from the first element of /*org-bibtex-entries*/.


** org-bibtex-yank  

If kill ring holds a bibtex entry yank it as an Org-mode headline.

