#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport


* Org-Choose API functions (org-choose.el)
** org-choose-conform-after-demotion =entry-pos keywords raise-to-ix old-highest-ok-ix=

Conform the current item after another item was demoted.


** org-choose-conform-after-promotion =entry-pos keywords highest-ok-ix=

Conform the current item after another item was promoted


** org-choose-filter-one =i=

Return a list of
#+begin_src emacs-lisp
 * a canonized version of the string
 * optionally one symbol
#+end_src



** org-choose-filter-tail =raw=

Return a translation of =raw= to vanilla and set appropriate
buffer-local variables.

=raw= is a list of strings representing the input text of a choose
interpretation.


** org-choose-get-default-mark =new-mark old-mark=

Get the default mark IFF in a choose interpretation.
=new-mark= and =old-mark= are the text of the new and old marks.


** org-choose-get-default-mark-index =data=

Return the index of the default mark in a choose interpretation.

=data= must be a /org-choose-mark-data./.


** org-choose-get-entry-index =all-keywords=

Return index of current entry.


** org-choose-get-fn-map-group  

Return a function to map over the group


** org-choose-get-highest-mark-index =keywords=

Get the index of the highest current mark in the group.
If there is none, return 0


** org-choose-get-index-in-keywords =ix all-keywords=

Return the index of the current entry.


** org-choose-get-mark-N =n data=

Get the text of the nth mark in a choose interpretation.


** org-choose-highest-other-ok =ix data=

Return the highest index that any choose mark can sensibly have,
given that another mark has index =ix=.
=data= must be a /org-choose-mark-data./.


** org-choose-keep-sensible =change-plist=

Bring the other items back into a sensible state after an item's
setting was changed.


** org-choose-setup-filter =raw=

A setup filter for choose interpretations.


** org-choose-setup-vars =bot-lower-range top-upper-range static-default num-items all-mark-texts=

Add to org-choose-mark-data according to arguments

