#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

* Org-E-ODT API functions (org-e-odt.el)
** org-e-odt-add-automatic-style =object-type &optional object-props=

Create an automatic style of type =object-type= with param =object-props=.
=object-props= is (typically) a plist created by passing
"#+ATTR_ODT: " option of the object in question to
/org-e-odt-parse-block-attributes/.

Use /org-e-odt-object-counters/ to generate an automatic
OBJECT-NAME and STYLE-NAME.  If =object-props= is non-nil, add a
new entry in /org-e-odt-automatic-styles/.  Return (OBJECT-NAME
. STYLE-NAME).


** org-e-odt-bibliography  

Find bibliography, cut it out and return it.


** org-e-odt-bold =bold contents info=

Transcode =bold= from Org to HTML.
=contents= is the text with bold markup.  =info= is a plist holding
contextual information.


** org-e-odt-center-block =center-block contents info=

Transcode a =center-block= element from Org to HTML.
=contents= holds the contents of the center block.  =info= is a plist
holding contextual information.


** org-e-odt-clock =clock contents info=

Transcode a =clock= element from Org to HTML.
=contents= is nil.  =info= is a plist used as a communication
channel.


** org-e-odt-code =code contents info=

Transcode a =code= object from Org to HTML.
=contents= is nil.  =info= is a plist used as a communication
channel.


** org-e-odt-configure-outline-numbering  

Outline numbering is retained only upto LEVEL.
To disable outline numbering pass a LEVEL of 0.


** org-e-odt-convert =&optional in-file out-fmt prefix-arg=

Convert =in-file= to format =out-fmt= using a command line converter.
=in-file= is the file to be converted.  If unspecified, it defaults
to variable /buffer-file-name/.  =out-fmt= is the desired output
format.  Use /org-e-odt-convert-process/ as the converter.
If =prefix-arg= is non-nil then the newly converted file is opened
using /org-open-file/.


** org-e-odt-convert-read-params  

Return IN-FILE and OUT-FMT params for /org-e-odt-do-convert/.
This is a helper routine for interactive use.


** org-e-odt-convert-special-strings =string=

Convert special characters in =string= to ODT.


** org-e-odt-copy-formula-file =path=

Returns the internal name of the file


** org-e-odt-copy-image-file =path=

Returns the internal name of the file


** org-e-odt-do-convert =in-file out-fmt &optional prefix-arg=

Workhorse routine for /org-e-odt-convert/.


** org-e-odt-do-preprocess-latex-fragments  

Convert LaTeX fragments to images.


** org-e-odt-do-reachable-formats =in-fmt=

Return verbose info about formats to which =in-fmt= can be converted.
Return a list where each element is of the
form (CONVERTER-PROCESS . OUTPUT-FMT-ALIST).  See
/org-e-odt-convert-processes/ for CONVERTER-PROCESS and see
/org-e-odt-convert-capabilities/ for OUTPUT-FMT-ALIST.


** org-e-odt-drawer =drawer contents info=

Transcode a =drawer= element from Org to HTML.
=contents= holds the contents of the block.  =info= is a plist
holding contextual information.


** org-e-odt-dynamic-block =dynamic-block contents info=

Transcode a =dynamic-block= element from Org to HTML.
=contents= holds the contents of the block.  =info= is a plist
holding contextual information.  See /org-export-data/.


** org-e-odt-end-annotation  

</office:annotation>


** org-e-odt-end-paragraph  

</text:p>


** org-e-odt-end-section  

</text:section>


** org-e-odt-entity =entity contents info=

Transcode an =entity= object from Org to HTML.
=contents= are the definition itself.  =info= is a plist holding
contextual information.


** org-e-odt-example-block =example-block contents info=

Transcode a =example-block= element from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-export-block =export-block contents info=

Transcode a =export-block= element from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-export-snippet =export-snippet contents info=

Transcode a =export-snippet= object from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-export-to-odt =&optional subtreep visible-only body-only ext-plist pub-dir=

Export current buffer to a HTML file.

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

When optional argument =subtreep= is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument =visible-only= is non-nil, don't export
contents of hidden elements.

When optional argument =body-only= is non-nil, only write code
between "\begin{document}" and "\end{document}".

=ext-plist=, when provided, is a property list with external
parameters overriding Org default settings, but still inferior to
file-local settings.

When optional argument =pub-dir= is set, use it as the publishing
directory.

Return output file's name.


** org-e-odt-fix-class-name =kwd=

Turn todo keyword into a valid class name.
Replaces invalid characters with "_".


** org-e-odt-fixed-width =fixed-width contents info=

Transcode a =fixed-width= element from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-footnote-reference =footnote-reference contents info=

Transcode a =footnote-reference= element from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-format-org-link =opt-plist type-1 path fragment desc attr descp=

Make a OpenDocument link.
=opt-plist= is an options list.
=type-1= is the device-type of the link (THIS://foo.html).
=path= is the path of the link (http://THIS#location).
=fragment= is the fragment part of the link, if any (foo.html#THIS).
=desc= is the link description, if any.
=attr= is a string of other attributes of the a element.


** org-e-odt-get-table-cell-styles =table-cell info=

Retrieve styles applicable to a table cell.
R and C are (zero-based) row and column numbers of the table
cell.  STYLE-SPEC is an entry in /org-e-odt-table-styles/
applicable to the current table.  It is /nil/ if the table is not
associated with any style attributes.

Return a cons of (=table-cell=-STYLE-NAME . PARAGRAPH-STYLE-NAME).

When STYLE-SPEC is nil, style the table cell the conventional way
- choose cell borders based on row and column groupings and
choose paragraph alignment based on /org-col-cookies/ text
property.  See also
/org-e-odt-get-paragraph-style-cookie-for-table-cell/.

When STYLE-SPEC is non-nil, ignore the above cookie and return
styles congruent with the ODF-1.2 specification.


** org-e-odt-headline =headline contents info=

Transcode an =headline= element from Org to HTML.
=contents= holds the contents of the headline.  =info= is a plist
holding contextual information.


** org-e-odt-hfy-face-to-css =fn=

Create custom style for face =fn=.
When =fn= is the default face, use it's foreground and background
properties to create "OrgSrcBlock" paragraph style.  Otherwise
use it's color attribute to create a character style whose name
is obtained from =fn=.  Currently all attributes of =fn= other than
color are ignored.

The style name for a face =fn= is derived using the following
operations on the face name in that order - de-dash, CamelCase
and prefix with "OrgSrc".  For example,
/font-lock-function-name-face/ is associated with
"OrgSrcFontLockFunctionNameFace".


** org-e-odt-horizontal-rule =horizontal-rule contents info=

Transcode an =horizontal-rule=  object from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-inline-src-block =inline-src-block contents info=

Transcode an =inline-src-block= element from Org to HTML.
=contents= holds the contents of the item.  =info= is a plist holding
contextual information.


** org-e-odt-inlinetask =inlinetask contents info=

Transcode an =inlinetask= element from Org to ODT.
=contents= holds the contents of the block.  =info= is a plist
holding contextual information.


** org-e-odt-insert-custom-styles-for-srcblocks =styles=

Save =styles= used for colorizing of source blocks.
Update styles.xml with styles that were collected as part of
/org-e-odt-hfy-face-to-css/ callbacks.


** org-e-odt-italic =italic contents info=

Transcode =italic= from Org to HTML.
=contents= is the text with italic markup.  =info= is a plist holding
contextual information.


** org-e-odt-item =item contents info=

Transcode an =item= element from Org to HTML.
=contents= holds the contents of the item.  =info= is a plist holding
contextual information.


** org-e-odt-keyword =keyword contents info=

Transcode a =keyword= element from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-latex-environment =latex-environment contents info=

Transcode a =latex-environment= element from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-latex-fragment =latex-fragment contents info=

Transcode a =latex-fragment= object from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-line-break =line-break contents info=

Transcode a =line-break= object from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-link =link desc info=

Transcode a =link= object from Org to HTML.

=desc= is the description part of the link, or the empty string.
=info= is a plist holding contextual information.  See
/org-export-data/.


** org-e-odt-macro =macro contents info=

Transcode a =macro= element from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-paragraph =paragraph contents info=

Transcode a =paragraph= element from Org to HTML.
=contents= is the contents of the paragraph, as a string.  =info= is
the plist used as a communication channel.


** org-e-odt-plain-list =plain-list contents info=

Transcode a =plain-list= element from Org to HTML.
=contents= is the contents of the list.  =info= is a plist holding
contextual information.


** org-e-odt-plain-text =text info=

Transcode a =text= string from Org to HTML.
=text= is the string to transcode.  =info= is a plist holding
contextual information.


** org-e-odt-planning =planning contents info=

Transcode a =planning= element from Org to HTML.
=contents= is nil.  =info= is a plist used as a communication
channel.


** org-e-odt-property-drawer =property-drawer contents info=

Transcode a =property-drawer= element from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual
information.


** org-e-odt-quote-block =quote-block contents info=

Transcode a =quote-block= element from Org to HTML.
=contents= holds the contents of the block.  =info= is a plist
holding contextual information.


** org-e-odt-quote-section =quote-section contents info=

Transcode a =quote-section= element from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-radio-target =radio-target text info=

Transcode a =radio-target= object from Org to HTML.
=text= is the text of the target.  =info= is a plist holding
contextual information.


** org-e-odt-reachable-formats =in-fmt=

Return list of formats to which =in-fmt= can be converted.
The list of the form (OUTPUT-FMT-1 OUTPUT-FMT-2 ...).


** org-e-odt-reachable-p =in-fmt out-fmt=

Return non-nil if =in-fmt= can be converted to =out-fmt=.


** org-e-odt-section =section contents info=

Transcode a =section= element from Org to HTML.
=contents= holds the contents of the section.  =info= is a plist
holding contextual information.


** org-e-odt-special-block =special-block contents info=

Transcode a =special-block= element from Org to HTML.
=contents= holds the contents of the block.  =info= is a plist
holding contextual information.


** org-e-odt-splice-attributes =tag attributes=

Read attributes in string =attributes=, add and replace in HTML tag =tag=.


** org-e-odt-src-block =src-block contents info=

Transcode a =src-block= element from Org to HTML.
=contents= holds the contents of the item.  =info= is a plist holding
contextual information.


** org-e-odt-standalone-image-p =element info &optional predicate=

Test if =element= is a standalone image for the purpose ODT export.
=info= is a plist holding contextual information.

Return non-nil, if =element= is of type paragraph and it's sole
content, save for whitespaces, is a link that qualifies as an
inline image.

Return non-nil, if =element= is of type link and it's containing
paragraph has no other content save for leading and trailing
whitespaces.

Return nil, otherwise.

Bind /org-e-odt-standalone-image-predicate/ to constrain
paragraph further.  For example, to check for only captioned
standalone images, do the following.

#+begin_src emacs-lisp
  (setq org-e-odt-standalone-image-predicate
#+end_src
	(lambda (paragraph)
	  (org-element-property :caption paragraph)))



** org-e-odt-statistics-cookie =statistics-cookie contents info=

Transcode a =statistics-cookie= object from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-strike-through =strike-through contents info=

Transcode =strike-through= from Org to HTML.
=contents= is the text with strike-through markup.  =info= is a plist
holding contextual information.


** org-e-odt-subscript =subscript contents info=

Transcode a =subscript= object from Org to HTML.
=contents= is the contents of the object.  =info= is a plist holding
contextual information.


** org-e-odt-superscript =superscript contents info=

Transcode a =superscript= object from Org to HTML.
=contents= is the contents of the object.  =info= is a plist holding
contextual information.


** org-e-odt-table =table contents info=

Transcode a =table= element from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual information.


** org-e-odt-table-cell =table-cell contents info=

Transcode a =table-cell= element from Org to ODT.
=contents= is nil.  =info= is a plist used as a communication
channel.


** org-e-odt-table-row =table-row contents info=

Transcode a =table-row= element from Org to ODT.
=contents= is the contents of the row.  =info= is a plist used as a
communication channel.


** org-e-odt-target =target contents info=

Transcode a =target= object from Org to HTML.
=contents= is nil.  =info= is a plist holding contextual
information.


** org-e-odt-template =contents info=

Return complete document string after HTML conversion.
=contents= is the transcoded contents string.  RAW-DATA is the
original parsed data.  =info= is a plist holding export options.


** org-e-odt-timestamp =timestamp contents info=

Transcode a =timestamp= object from Org to HTML.
=contents= is nil.  =info= is a plist used as a communication
channel.


** org-e-odt-underline =underline contents info=

Transcode =underline= from Org to HTML.
=contents= is the text with underline markup.  =info= is a plist
holding contextual information.


** org-e-odt-verbatim =verbatim contents info=

Transcode a =verbatim= object from Org to HTML.
=contents= is nil.  =info= is a plist used as a communication
channel.


** org-e-odt-verse-block =verse-block contents info=

Transcode a =verse-block= element from Org to HTML.
=contents= is verse block contents.  =info= is a plist holding
contextual information.


** org-e-odt-write-automatic-styles  

Write automatic styles to "content.xml".
