#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Org API
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tjolitz [at] gmail [dot] com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport

* Org-Gnus API functions (org-gnus.el)
** org-gnus-article-link =group newsgroups message-id x-no-archive=

Create a link to a Gnus article.
The article is specified by its =message-id=.  Additional
parameters are the Gnus =group=, the =newsgroups= the article was
posted to and the =x-no-archive= header value of that article.

If =group= is a newsgroup and /org-gnus-prefer-web-links/ is
non-nil, create a link to groups.google.com or gmane.org.
Otherwise create a link to the article inside Gnus.

If /org-store-link/ was called with a prefix arg the meaning of
/org-gnus-prefer-web-links/ is reversed.


** org-gnus-follow-link =&optional group article=

Follow a Gnus link to =group= and =article=.


** org-gnus-group-link =group=

Create a link to the Gnus group =group=.
If =group= is a newsgroup and /org-gnus-prefer-web-links/ is
non-nil, create a link to groups.google.com or gmane.org.
Otherwise create a link to the group inside Gnus.

If /org-store-link/ was called with a prefix arg the meaning of
/org-gnus-prefer-web-links/ is reversed.


** org-gnus-nnimap-cached-article-number =group server message-id=

Return cached article number (uid) of message in =group= on =server=.
=message-id= is the message-id header field that identifies the
message.  If the uid is not cached, return nil.


** org-gnus-no-new-news  

Like /M-x gnus/ but doesn't check for new news.


** org-gnus-open =path=

Follow the Gnus message or folder link specified by =path=.


** org-gnus-open-nntp =path=

Follow the nntp: link specified by =path=.


** org-gnus-store-link  

Store a link to a Gnus folder or message.
