function OrgNode(a,d,c,b,h,f){this.div=a;this.base_id=f;this.idx=-1;this.heading=d;
this.link=c;this.hasHighlight=false;this.parent=h;this.dirty=false;this.state=OrgNode.STATE_FOLDED;
this.depth=b;this.folder=null;this.children=new Array();this.info_navigation="";this.buttons=null;
if(null!=this.parent){this.parent.addChild(this);this.hide();}var e=document.getElementById("text-"+this.base_id);
if(null==e&&f){var g=f.substring(4);e=document.getElementById("text-"+g);}if(null!=e){e.isOrgNodeFolder=true;
this.folder=e;}this.isTargetFor=new Object();this.isTargetFor["#"+this.base_id]=2;
OrgNode.findTargetsIn(this.isTargetFor,this.heading,1);OrgNode.findTargetsIn(this.isTargetFor,this.folder,3);
}OrgNode.STATE_FOLDED=0;OrgNode.STATE_HEADLINES=1;OrgNode.STATE_UNFOLDED=2;OrgNode.findTargetsIn=function(f,c,e){if(c){var b=c.getElementsByTagName("a");
if(b){for(var d=0;d<b.length;++d){var g=b[d].getAttribute("id");if(g){f["#"+g]=e;
}else{g=b[d].getAttribute("name");if(g){f["#"+g]=e;}}}}}};OrgNode.hideElement=function(a){if(a&&a.style){a.style.display="none";
a.style.visibility="hidden";}};OrgNode.showElement=function(a){if(a&&a.style){a.style.display="block";
a.style.visibility="visible";}};OrgNode.unhideElement=function(a){a.style.display="";
a.style.visibility="";};OrgNode.isHidden=function(a){if(a.style.display=="none"||a.style.visibility=="hidden"){return true;
}return false;};OrgNode.toggleElement=function(a){if(a.style.display=="none"){a.style.display="block";
a.style.visibility="visible";}else{a.style.display="none";a.style.visibility="hidden";
}};OrgNode.textNodeToIdx=function(b,c){while(b.nodeType!=1||-1==b.attributes.id.value.indexOf("outline-container-")){b=b.parentNode;
}var a=b.attributes.id.value.substr(18);return OrgNode.idxForBaseId(a,c);};OrgNode.idxForBaseId=function(b,d){if(d.base_id==b){return d;
}for(var a=0;a<d.children.length;++a){var c=OrgNode.idxForBaseId(idx,d.children[a]);
if(null!=c){return c;}}return null;};OrgNode.prototype.addChild=function(a){this.children.push(a);
return this.parent;};OrgNode.prototype.getParent=function(){return this.parent;};
OrgNode.prototype.hide=function(){OrgNode.hideElement(this.div);if(this.parent){this.parent.hide();
}};OrgNode.prototype.show=function(){OrgNode.showElement(this.div);if(this.depth>2){this.parent.show();
}};OrgNode.prototype.showAllChildren=function(){for(var a=0;a<this.children.length;
++a){this.children[a].showAllChildren();}this.show();};OrgNode.prototype.hideAllChildren=function(){for(var a=0;
a<this.children.length;++a){this.children[a].hideAllChildren();}this.hide();};OrgNode.prototype.fold=function(b){if(this.parent){this.parent.dirty=true;
}if(this.dirty){this.dirty=false;this.state=OrgNode.STATE_UNFOLDED;}if(null!=this.folder){if(this.state==OrgNode.STATE_FOLDED){if(this.children.length){this.state=OrgNode.STATE_HEADLINES;
OrgNode.hideElement(this.folder);for(var a=0;a<this.children.length;++a){this.children[a].setState(OrgNode.STATE_HEADLINES);
}}else{if(!b){this.state=OrgNode.STATE_UNFOLDED;OrgNode.showElement(this.folder);
}}}else{if(this.state==OrgNode.STATE_HEADLINES){this.state=OrgNode.STATE_UNFOLDED;
OrgNode.showElement(this.folder);for(var a=0;a<this.children.length;++a){this.children[a].setState(OrgNode.STATE_UNFOLDED);
}}else{this.state=OrgNode.STATE_FOLDED;OrgNode.hideElement(this.folder);for(var a=0;
a<this.children.length;++a){this.children[a].setState(OrgNode.STATE_FOLDED);}}}}};
OrgNode.prototype.setState=function(b){for(var a=0;a<this.children.length;++a){this.children[a].setState(b);
}switch(b){case OrgNode.STATE_FOLDED:OrgNode.hideElement(this.folder);OrgNode.hideElement(this.div);
break;case OrgNode.STATE_HEADLINES:OrgNode.hideElement(this.folder);OrgNode.showElement(this.div);
break;default:OrgNode.showElement(this.folder);OrgNode.showElement(this.div);}this.state=b;
};var org_html_manager={MOUSE_HINT:0,BODY:null,PLAIN_VIEW:0,CONTENT_VIEW:1,ALL_VIEW:2,INFO_VIEW:3,SLIDE_VIEW:4,VIEW:this.OVER_VIEW,LOCAL_TOC:false,LINK_HOME:0,LINK_UP:0,LINKS:"",RUN_MAX:1200,RUN_INTERVAL:100,DEBUG:0,WINDOW_BORDER:false,HIDE_TOC:false,TOC_DEPTH:0,STARTUP_MESSAGE:0,POSTAMBLE:null,BASE_URL:document.URL,START_SECTION:0,ROOT:null,NODE:null,TITLE:null,INNER_TITLE:false,LOAD_CHECK:null,WINDOW:null,SECS:new Array(),REGEX:/(#)(.*$)/,UNTAG_REGEX:/<[^>]+>/i,TRIMMER:/^(\s*)([^\s].*)(\s*)$/,FNREF_REGEX:/(fnr\.*)/,TOC:null,runs:0,HISTORY:new Array(50),HIST_INDEX:0,SKIP_HISTORY:false,FIXED_TOC:false,debug:"",DEBUG_FATAL:1,DEBUG_BUILD:1<<5,DEBUG_TREE:1<<10,WINDOW_BORDER:false,CONSOLE:null,CONSOLE_INPUT:null,CONSOLE_LABEL:null,CONSOLE_OFFSET:"50px",OCCUR:"",SEARCH_REGEX:"",SEARCH_HL_REG:new RegExp('(<span class="org-info-js_search-highlight">)([^<]*?)(</span>)',"gi"),console_first_time:true,MESSAGING:0,MESSAGING_INPLACE:1,MESSAGING_TOP:2,HELPING:false,READING:false,READ_COMMAND:"",READ_COMMAND_NULL:"_0",READ_COMMAND_HTML_LINK:"_1",READ_COMMAND_ORG_LINK:"_2",READ_COMMAND_PLAIN_URL_LINK:"_03",LAST_WAS_SEARCH:false,last_view_mode:0,TAB_INDEX:1000,SEARCH_HIGHLIGHT_ON:false,TAGS:{},SORTED_TAGS:new Array(),TAGS_INDEX:null,CLICK_TIMEOUT:null,SECNUM_MAP:{},SECNUM_REGEX:/^section-number-(\d)+/,setup:function(){if(location.search){var d=location.search.substring(1).split("&");
for(var c=0;c<d.length;++c){var e=d[c].indexOf("=");if(-1!=e){var b=d[c].substring(e+1);
var a=d[c].substring(0,e);switch(a){case"TOC":case"TOC_DEPTH":case"MOUSE_HINT":case"HELP":case"VIEW":case"HIDE_TOC":case"LOCAL_TOC":case"VIEW":case"OCCUR":this.set(a,decodeURIComponent(b));
break;default:break;}}}}this.VIEW=this.VIEW?this.VIEW:this.PLAIN_VIEW;this.VIEW_BUTTONS=(this.VIEW_BUTTONS&&this.VIEW_BUTTONS!="0")?true:false;
this.STARTUP_MESSAGE=(this.STARTUP_MESSAGE&&this.STARTUP_MESSAGE!="0")?true:false;
this.LOCAL_TOC=(this.LOCAL_TOC&&this.LOCAL_TOC!="0")?this.LOCAL_TOC:false;this.HIDE_TOC=(this.TOC&&this.TOC!="0")?false:true;
this.INNER_TITLE=(this.INNER_TITLE&&this.INNER_TITLE!="title_above")?false:true;if(this.FIXED_TOC&&this.FIXED_TOC!="0"){this.FIXED_TOC=true;
this.HIDE_TOC=false;}else{this.FIXED_TOC=false;}this.LINKS+=((this.LINK_UP&&this.LINK_UP!=document.URL)?'<a href="'+this.LINK_UP+'">Up</a> / ':"")+((this.LINK_HOME&&this.LINK_HOME!=document.URL)?'<a href="'+this.LINK_HOME+'">HOME</a> / ':"")+'<a href="javascript:org_html_manager.showHelp();">HELP</a> / ';
this.LOAD_CHECK=window.setTimeout("OrgHtmlManagerLoadCheck()",50);},trim:function(a){var b=this.TRIMMER.exec(a);
return RegExp.$2;},removeTags:function(a){if(a){while(a.match(this.UNTAG_REGEX)){a=a.substr(0,a.indexOf("<"))+a.substr(a.indexOf(">")+1);
if(this.DEBUG>5){this.debug+=a+"\n";}}}return a;},init:function(){this.runs++;this.BODY=document.getElementById("content");
if(null==this.BODY){if(5>this.runs){this.LOAD_CHECK=window.setTimeout("OrgHtmlManagerLoadCheck()",this.RUN_INTERVAL);
return;}else{this.BODY=document.getElementsByTagName("body")[0];}}if(!this.WINDOW){this.WINDOW=document.createElement("div");
if(this.WINDOW_BORDER){this.WINDOW.style.border="1px dashed black";}}this.WINDOW.style.marginBottom="40px";
this.WINDOW.id="org-info-js-window";var l=document.getElementById("table-of-contents");
var j=false;if(null!=l){if(this.initFromTOC()){j=true;}}if(j){if(-1!=this.BASE_URL.indexOf("?")){this.BASE_URL=this.BASE_URL.substring(0,this.BASE_URL.indexOf("?"));
}var k=0;if(-1!=this.BASE_URL.indexOf("#")){this.START_SECTION=this.BASE_URL.substring(this.BASE_URL.indexOf("#"));
this.BASE_URL=this.BASE_URL.substring(0,this.BASE_URL.indexOf("#"));for(var d=0;d<this.SECS.length;
++d){if(this.SECS[d].isTargetFor[this.START_SECTION]){this.START_SECTION=d;k=1;break;
}}}if(!k){this.START_SECTION=0;}this.convertLinks();var g=document.getElementById("postamble");
if(g){this.POSTAMBLE=g;}var f=this.BODY;var c=f.firstChild;if(3==c.nodeType){var e=c.cloneNode(true);
var a=document.createElement("p");a.id="text-before-first-headline";a.appendChild(e);
f.replaceChild(a,c);}if(this.VIEW==this.INFO_VIEW){this.infoView(this.START_SECTION);
}else{if(this.VIEW==this.SLIDE_VIEW){this.slideView(this.START_SECTION);}else{var h=this.VIEW;
this.plainView(this.START_SECTION);this.ROOT.dirty=true;this.ROOT_STATE=OrgNode.STATE_UNFOLDED;
this.toggleGlobaly();if(h>this.PLAIN_VIEW){this.toggleGlobaly();}if(h==this.ALL_VIEW){this.toggleGlobaly();
}}}if(this.START_SECTION){this.showSection(this.START_SECTION);}else{window.scrollTo(0,0);
}}else{if(this.runs<this.RUN_MAX){this.LOAD_CHECK=window.setTimeout("OrgHtmlManagerLoadCheck()",this.RUN_INTERVAL);
return;}}this.CONSOLE=document.createElement("div");this.CONSOLE.innerHTML='<form action="" style="margin:0px;padding:0px;" onsubmit="org_html_manager.evalReadCommand(); return false;"><table id="org-info-js_console" style="width:100%;margin:0px 0px 0px 0px;border-style:none;" cellpadding="0" cellspacing="0" summary="minibuffer"><tbody><tr><td id="org-info-js_console-icon" style="padding:0px 0px 0px 0px;border-style:none;">&#160;</td><td style="width:100%;vertical-align:middle;padding:0px 0px 0px 0px;border-style:none;"><table style="width:100%;margin:0px 0px 0px 0px;border-style:none;" cellpadding="0" cellspacing="2"><tbody><tr><td id="org-info-js_console-label" style="white-space:nowrap;padding:0px 0px 0px 0px;border-style:none;"></td></tr><tr><td style="width:100%;vertical-align:middle;padding:0px 0px 0px 0px;border-style:none;"><input type="text" id="org-info-js_console-input" onkeydown="org_html_manager.getKey();" onclick="this.select();" maxlength="150" style="width:100%;padding:0px;margin:0px 0px 0px 0px;border-style:none;" value=""/></td></tr></tbody></table></td><td style="padding:0px 0px 0px 0px;border-style:none;">&#160;</td></tr></tbody></table></form>';
this.CONSOLE.style.position="relative";this.CONSOLE.style.marginTop="-"+this.CONSOLE_OFFSET;
this.CONSOLE.style.top="-"+this.CONSOLE_OFFSET;this.CONSOLE.style.left="0px";this.CONSOLE.style.width="100%";
this.CONSOLE.style.height="40px";this.CONSOLE.style.overflow="hidden";this.CONSOLE.style.verticalAlign="middle";
this.CONSOLE.style.zIndex="9";this.CONSOLE.style.border="1px solid #cccccc";this.CONSOLE.id="org-info-js_console-container";
this.BODY.insertBefore(this.CONSOLE,this.BODY.firstChild);this.MESSAGING=false;this.CONSOLE_LABEL=document.getElementById("org-info-js_console-label");
this.CONSOLE_INPUT=document.getElementById("org-info-js_console-input");document.onkeypress=OrgHtmlManagerKeyEvent;
if(""!=this.OCCUR){this.CONSOLE_INPUT.value=this.OCCUR;this.READ_COMMAND="o";this.evalReadCommand();
}if(0!=this.DEBUG&&this.debug.length){alert(this.debug);}if(this.STARTUP_MESSAGE){this.warn("This page uses org-info.js. Press '?' for more information.",true);
}},initFromTOC:function(){if(this.runs==1||!this.ROOT){var b=document.getElementById("table-of-contents");
if(null!=b){var l=null;var d=0;for(d;l==null&&d<7;++d){l=b.getElementsByTagName("h"+d)[0];
}l.onclick=function(){org_html_manager.fold(0);};l.style.cursor="pointer";if(this.MOUSE_HINT){l.onmouseover=function(){org_html_manager.highlight_headline(0);
};l.onmouseout=function(){org_html_manager.unhighlight_headline(0);};}if(this.FIXED_TOC){l.setAttribute("onclick","org_html_manager.toggleGlobaly();");
this.ROOT=new OrgNode(null,this.BODY.getElementsByTagName("h1")[0],"javascript:org_html_manager.navigateTo(0);",0,null);
this.TOC=new OrgNode(b,l,"javascript:org_html_manager.navigateTo(0);",d,null);this.NODE=this.ROOT;
}else{this.ROOT=new OrgNode(null,this.BODY.getElementsByTagName("h1")[0],"javascript:org_html_manager.navigateTo(0);",0,null);
if(this.HIDE_TOC){this.TOC=new OrgNode(b,"","javascript:org_html_manager.navigateTo(0);",d,null);
this.NODE=this.ROOT;OrgNode.hideElement(b);}else{this.TOC=new OrgNode(b,l,"javascript:org_html_manager.navigateTo(0);",d,this.ROOT);
this.TOC.idx=0;this.NODE=this.TOC;this.SECS.push(this.TOC);}}if(this.TOC){this.TOC.folder=document.getElementById("text-table-of-contents");
}}else{return false;}}var j=document.getElementsByTagName("ul")[0];if(!this.ulToOutlines(j)){return false;
}var h=document.getElementById("footnotes");if(h){var a=null;var f=h.childNodes;for(var d=0;
d<f.length;++d){if("footnotes"==f[d].className){a=f[d];break;}}var e=this.SECS.length;
a.onclick=function(){org_html_manager.fold(""+e);};a.style.cursor="pointer";if(this.MOUSE_HINT){a.onmouseover=function(){org_html_manager.highlight_headline(""+e);
};a.onmouseout=function(){org_html_manager.unhighlight_headline(""+e);};}var g="javascript:org_html_manager.navigateTo("+e+")";
var k=new OrgNode(h,a,g,1,this.ROOT,"footnotes");this.SECS.push(k);}if(this.TOC_DEPTH){this.cutToc(j,1);
}this.TITLE=document.getElementsByTagName("h1")[0];if(this.INNER_TITLE&&!this.FIXED_TOC&&this.VIEW!=this.SLIDE_VIEW){this.INNER_TITLE=this.TITLE.cloneNode(true);
this.SECS[0].div.insertBefore(this.INNER_TITLE,this.SECS[0].div.firstChild);OrgNode.hideElement(this.TITLE);
}this.build();this.NODE=this.SECS[0];this.BODY.insertBefore(this.WINDOW,this.NODE.div);
return true;},ulToOutlines:function(b){if(b.hasChildNodes()&&!b.scanned_for_org){for(var a=0;
a<b.childNodes.length;++a){if(false==this.liToOutlines(b.childNodes[a])){return false;
}}b.scanned_for_org=1;}return true;},liToOutlines:function(b){if(!b.scanned_for_org){for(var d=0;
d<b.childNodes.length;++d){var e=b.childNodes[d];switch(e.nodeName){case"A":var a=this.mkNodeFromHref(e.href);
if(false==a){this.debug+="liToOutlines: stopped\n";return false;}else{e.href=a;e.tabIndex=this.TAB_INDEX;
this.TAB_INDEX++;}break;case"UL":return this.ulToOutlines(e);break;}}b.scanned_for_org=1;
}return true;},cutToc:function(e,f){f++;if(e.hasChildNodes()){for(var d=0;d<e.childNodes.length;
++d){var a=e.childNodes[d];for(var b=0;b<a.childNodes.length;++b){var g=a.childNodes[b];
if(g.nodeName=="UL"){if(f>this.TOC_DEPTH){a.removeChild(g);}else{this.cutToc(g,f);
}}}}}},mkNodeFromHref:function(o){if(o.match(this.REGEX)){var g=this.REGEX.exec(o);
this.debug+=g[1]+" + "+g[2]+"\n";var c=g[2];var n=document.getElementById(c);if(null==n){this.debug+=("heading is null. Scanning stopped.\n");
return(false);}var a=n.parentNode;var h=this.SECS.length;var f=a.className.substr(8);
n.onclick=function(){org_html_manager.fold(""+h);};n.style.cursor="pointer";if(this.MOUSE_HINT){n.onmouseover=function(){org_html_manager.highlight_headline(""+h);
};n.onmouseout=function(){org_html_manager.unhighlight_headline(""+h);};}var l="javascript:org_html_manager.navigateTo("+h+")";
if(f>this.NODE.depth){this.NODE=new OrgNode(a,n,l,f,this.NODE,c);}else{if(f==2){this.NODE=new OrgNode(a,n,l,f,this.ROOT,c);
}else{var b=this.NODE;while(b.depth>f){b=b.parent;}this.NODE=new OrgNode(a,n,l,f,b.parent,c);
}}this.SECS.push(this.NODE);var k=n.getElementsByTagName("span");if(k){for(var e=0;
e<k.length;++e){if(k[e].className=="tag"){var m=k[e].innerHTML.split("&nbsp;");for(var d=0;
d<m.length;++d){if(!this.TAGS[m[d]]){this.TAGS[m[d]]=new Array();this.SORTED_TAGS.push(m[d]);
}this.TAGS[m[d]].push(h);}}else{if(k[e].className.match(this.SECNUM_REGEX)){this.SECNUM_MAP[this.trim(k[e].innerHTML)]=this.NODE;
}}}}this.NODE.hide();return(l);}return(o);},build:function(){var f=this.TITLE.innerHTML;
var e=0;for(var d=0;d<this.SECS.length;++d){this.SECS[d].idx=d;var c='<table class="org-info-js_info-navigation" width="100%" border="0" style="border-bottom:1px solid black;"><tr><td colspan="3" style="text-align:left;border-style:none;vertical-align:bottom;"><span style="float:left;display:inline;text-align:left;">Top: <a accesskey="i" href="javascript:org_html_manager.navigateTo(0);">'+f+'</a></span><span style="float:right;display:inline;text-align:right;font-size:70%;">'+this.LINKS+'<a accesskey="t" href="javascript:org_html_manager.toggleView('+d+');">toggle view</a></span></td></tr><tr><td style="text-align:left;border-style:none;vertical-align:bottom;width:22%">';
if(d>0){c+='<a accesskey="p" href="'+this.SECS[d-1].link+'" title="Go to: '+this.removeTags(this.SECS[d-1].heading.innerHTML)+'">Previous</a> | ';
}else{c+="Previous | ";}if(d<this.SECS.length-1){c+='<a accesskey="n" href="'+this.SECS[d+1].link+'" title="Go to: '+this.removeTags(this.SECS[d+1].heading.innerHTML)+'">Next</a>';
}else{c+="Next";}c+='</td><td style="text-align:center;vertical-align:bottom;border-style:none;width:56%;">';
if(d>0&&this.SECS[d].parent.parent){c+='<a href="'+this.SECS[d].parent.link+'" title="Go to: '+this.removeTags(this.SECS[d].parent.heading.innerHTML)+'"><span style="font-variant:small-caps;font-style:italic;">'+this.SECS[d].parent.heading.innerHTML+"</span></a>";
}else{c+='<span style="font-variant:small-caps;font-style:italic;">'+this.SECS[d].heading.innerHTML+"</span>";
}c+='</td><td style="text-align:right;vertical-align:bottom;border-style:none;width:22%">';
c+=(d+1)+"</td></tr></table>";this.SECS[d].buttons=document.createElement("div");
this.SECS[d].buttons.innerHTML='<div style="display:inline;float:right;text-align:right;font-size:70%;font-weight:normal;">'+this.LINKS+'<a accesskey="t" href="javascript:org_html_manager.toggleView('+d+');">toggle view</a></div>';
if(this.SECS[d].folder){this.SECS[d].div.insertBefore(this.SECS[d].buttons,this.SECS[d].heading);
}else{if(this.SECS[d].div.hasChildNodes()){this.SECS[d].div.insertBefore(this.SECS[d].buttons,this.SECS[d].div.firstChild);
}}if(!this.VIEW_BUTTONS){OrgNode.hideElement(this.SECS[d].buttons);}this.SECS[d].navigation=c;
if(0<this.SECS[d].children.length&&this.LOCAL_TOC){var a=document.createElement("div");
c="Contents:<br /><ul>";for(var b=0;b<this.SECS[d].children.length;++b){c+='<li><a href="'+this.SECS[d].children[b].link+'">'+this.removeTags(this.SECS[d].children[b].heading.innerHTML)+"</a></li>";
}c+="</ul>";a.innerHTML=c;if("above"==this.LOCAL_TOC){if(this.SECS[d].folder){this.SECS[d].folder.insertBefore(a,this.SECS[d].folder.firstChild);
}else{this.SECS[d].div.insertBefore(a,this.SECS[d].div.getElementsByTagName("h"+this.SECS[d].depth)[0].nextSibling);
}}else{if(this.SECS[d].folder){this.SECS[d].folder.appendChild(a);}else{this.SECS[d].div.appendChild(a);
}}}}this.SORTED_TAGS.sort();},set:function(eval_key,eval_val){if("VIEW"==eval_key){var pos=eval_val.indexOf("_");
if(-1!=pos){this.INNER_TITLE=eval_val.substr(pos+1);eval_val=eval_val.substr(0,pos);
}var overview=this.PLAIN_VIEW;var content=this.CONTENT_VIEW;var showall=this.ALL_VIEW;
var info=this.INFO_VIEW;var info_title_above=this.INFO_VIEW;var slide=this.SLIDE_VIEW;
eval("this."+eval_key+"="+eval_val+";");}else{if("HELP"==eval_key){eval("this.STARTUP_MESSAGE="+eval_val+";");
}else{if(eval_val){eval("this."+eval_key+"='"+eval_val+"';");}else{eval("this."+eval_key+"=0;");
}}}},convertLinks:function(){var f=(this.HIDE_TOC?0:1);var e;var a=this.SECS.length-1;
for(f;f<this.SECS.length;++f){var d=this.SECS[f].div.getElementsByTagName("a");for(e=0;
e<d.length;++e){var c=d[e].href.replace(this.BASE_URL,"");for(var b=0;b<this.SECS.length;
++b){if(this.SECS[b].isTargetFor[c]){d[e].href="javascript:org_html_manager.navigateTo("+b+")";
break;}}}}},showSection:function(c){var d=parseInt(c);var b=this.NODE;if(this.HIDE_TOC&&this.NODE==this.TOC&&!this.FIXED_TOC){OrgNode.hideElement(this.TOC.div);
if(this.PLAIN_VIEW==this.VIEW){this.ROOT.showAllChildren();for(var a=0;a<this.ROOT.children.length;
++a){this.ROOT.children[a].state=OrgNode.STATE_UNFOLDED;this.ROOT.children[a].fold();
}}}if("toc"==c||(!isNaN(d)&&this.SECS[d])){if("toc"==c&&this.HIDE_TOC){this.NODE=this.TOC;
this.ROOT.hideAllChildren();if(this.INFO_VIEW==this.VIEW){this.WINDOW.innerHTML=this.NODE.div.innerHTML;
}else{this.NODE.setState(OrgNode.STATE_UNFOLDED);}window.scrollTo(0,0);}else{this.NODE=this.SECS[d];
if(this.SLIDE_VIEW==this.VIEW||this.INFO_VIEW==this.VIEW){OrgNode.hideElement(this.NODE.buttons);
this.NODE.setState(OrgNode.STATE_UNFOLDED);for(var a=0;a<this.NODE.children.length;
++a){this.NODE.children[a].hide();}if(this.SLIDE_VIEW==this.VIEW){this.WINDOW.innerHTML=this.NODE.div.innerHTML;
}else{this.WINDOW.innerHTML=this.NODE.navigation+this.NODE.div.innerHTML;}this.NODE.hide();
window.scrollTo(0,0);}else{if(!this.VIEW_BUTTONS){OrgNode.hideElement(b.buttons);
}OrgNode.showElement(this.NODE.buttons);this.NODE.setState(OrgNode.UNFOLDED);this.NODE.show();
if(0<this.NODE.idx){this.NODE.div.scrollIntoView(true);}else{window.scrollTo(0,0);
}}}}},plainView:function(b){document.onclick=null;document.ondblclick=null;this.VIEW=this.PLAIN_VIEW;
OrgNode.hideElement(this.WINDOW);if(this.INNER_TITLE){OrgNode.hideElement(this.INNER_TITLE);
}OrgNode.showElement(this.TITLE);if(this.WINDOW.firstChild){this.WINDOW.removeChild(this.WINDOW.firstChild);
}this.ROOT.showAllChildren();for(var a=0;a<this.ROOT.children.length;++a){this.ROOT.children[a].state=OrgNode.STATE_UNFOLDED;
this.ROOT.children[a].fold();}this.showSection(b);if(this.POSTAMBLE){OrgNode.showElement(this.POSTAMBLE);
}if(this.NODE.idx==0){window.scrollTo(0,0);}else{this.NODE.div.scrollIntoView(true);
}},infoView:function(b,a){document.onclick=null;document.ondblclick=null;this.VIEW=this.INFO_VIEW;
this.unhighlight_headline(this.NODE.idx);if(this.INNER_TITLE&&!this.FIXED_TOC){OrgNode.showElement(this.INNER_TITLE);
OrgNode.hideElement(this.TITLE);}OrgNode.showElement(this.WINDOW);this.ROOT.hideAllChildren();
if(this.TOC&&!this.FIXED_TOC){OrgNode.hideElement(this.TOC.div);}if(this.POSTAMBLE){OrgNode.showElement(this.POSTAMBLE);
}if(!a){this.showSection(b);}},slideView:function(b,a){this.VIEW=this.SLIDE_VIEW;
this.unhighlight_headline(this.NODE.idx);OrgNode.hideElement(this.TITLE);if(this.INNER_TITLE){OrgNode.hideElement(this.INNER_TITLE);
}if(this.TOC){OrgNode.hideElement(this.TOC.div);}OrgNode.showElement(this.TITLE);
OrgNode.showElement(this.WINDOW);this.ROOT.hideAllChildren();OrgNode.hideElement(this.TOC.div);
if(this.POSTAMBLE){OrgNode.hideElement(this.POSTAMBLE);}this.adjustSlide(b);if(!a){this.showSection(b);
}},adjustSlide:function(f,g){var k=true;var e=true;var d=false;if(f>this.NODE.idx){d=true;
}if(null==g){d=true;}if(d){for(var a=this.SECS[f].folder.firstChild;null!=a;a=a.nextSibling){if("UL"==a.nodeName){var j=a.getElementsByTagName("li");
for(var c=1;c<j.length;++c){var b=j[c];OrgNode.hideElement(b);k=false;}}}}else{var h=this.WINDOW.getElementsByTagName("ul");
for(var a=0;a<h.length;++a){var j=h[a].getElementsByTagName("li");for(var c=1;c<j.length;
++c){var b=j[c];if(g>0){if(OrgNode.isHidden(b)){OrgNode.unhideElement(b);if(c<(j.length-1)){k=false;
}if(0<c){e=false;}break;}}else{if(!OrgNode.isHidden(b)){if(1<c){e=false;OrgNode.hideElement(j[c-1]);
break;}}}}}}if(k){document.onclick=function(){org_html_manager.scheduleClick("org_html_manager.nextSection(org_html_manager.NODE.idx + 1)");
};}else{document.onclick=function(){org_html_manager.scheduleClick("org_html_manager.adjustSlide(org_html_manager.NODE.idx, +1)");
};}if(e){document.ondblclick=function(){org_html_manager.scheduleClick("org_html_manager.previousSection()");
};}else{document.ondblclick=function(){org_html_manager.scheduleClick("org_html_manager.adjustSlide("+this.NODE.idx+", -1)");
};}},toggleView:function(a){this.removeWarning();if(this.VIEW==this.INFO_VIEW){this.plainView(a);
}else{this.infoView(a);}},fold:function(a){this.removeWarning();var b=parseInt(a);
this.SECS[b].fold();if(!this.VIEW_BUTTONS){OrgNode.hideElement(this.NODE.buttons);
}this.NODE=this.SECS[b];OrgNode.showElement(this.NODE.buttons);if(this.INPUT_FIELD){this.INPUT_FIELD.focus();
}},toggleGlobaly:function(){if(this.ROOT.dirty){this.ROOT.state=OrgNode.STATE_UNFOLDED;
}if(OrgNode.STATE_UNFOLDED==this.ROOT.state){for(var a=0;a<this.ROOT.children.length;
++a){this.ROOT.children[a].state=OrgNode.STATE_UNFOLDED;this.ROOT.children[a].fold(true);
}this.ROOT.state=OrgNode.STATE_UNFOLDED;this.ROOT.state=OrgNode.STATE_FOLDED;}else{if(OrgNode.STATE_FOLDED==this.ROOT.state){for(var a=0;
a<this.ROOT.children.length;++a){this.ROOT.children[a].fold(true);}this.ROOT.state=OrgNode.STATE_HEADLINES;
}else{for(var a=0;a<this.ROOT.children.length;++a){this.ROOT.children[a].fold();}this.ROOT.state=OrgNode.STATE_UNFOLDED;
}}this.ROOT.dirty=false;},executeClick:function(func){if(this.READING){this.endRead();
this.hideConsole();}else{if(this.MESSAGING){this.removeWarning();}}eval(func);if(null!=this.CLICK_TIMEOUT){this.CLICK_TIMEOUT=null;
}},scheduleClick:function(b,a){if(null==a){a=250;}if(null==this.CLICK_TIMEOUT){this.CLICK_TIMEOUT=window.setTimeout("org_html_manager.executeClick("+b+")",a);
}else{window.clearTimeout(this.CLICK_TIMEOUT);this.CLICK_TIMEOUT=null;}},nextSection:function(){var a=this.NODE.idx+1;
if(a<this.SECS.length){this.navigateTo(a);}else{this.warn("Already last section.");
}},previousSection:function(){var a=this.NODE.idx;if(a>0){this.navigateTo(a-1);}else{this.warn("Already first section.");
}},navigateTo:function(a){if(this.READING){this.endRead();this.hideConsole();}else{if(this.MESSAGING){this.removeWarning();
}}if(this.VIEW==this.SLIDE_VIEW){this.adjustSlide(a);}this.pushHistory(a,this.NODE.idx);
this.showSection(a);},pushHistory:function(b,a){if(!this.SKIP_HISTORY){this.HISTORY[this.HIST_INDEX]=new Array(b,a);
this.HIST_INDEX=(this.HIST_INDEX+1)%50;}this.SKIP_HISTORY=false;this.CONSOLE_INPUT.value="";
},popHistory:function(b){if(b){if(this.HISTORY[this.HIST_INDEX]){var a=parseInt(this.HISTORY[this.HIST_INDEX][0]);
if(!isNaN(a)||"toc"==this.HISTORY[this.HIST_INDEX][0]){this.showSection(this.HISTORY[this.HIST_INDEX][0]);
this.CONSOLE_INPUT.value="";}else{this.SKIP_HISTORY=true;this.CONSOLE_INPUT.value=this.HISTORY[this.HIST_INDEX][0];
this.getKey();}this.HIST_INDEX=(this.HIST_INDEX+1)%50;}else{this.warn("History: No where to foreward go from here.");
}}else{if(this.HISTORY[this.HIST_INDEX-1]){this.HIST_INDEX=this.HIST_INDEX==0?49:this.HIST_INDEX-1;
var a=parseInt(this.HISTORY[this.HIST_INDEX][1]);if(!isNaN(a)||"toc"==this.HISTORY[this.HIST_INDEX][1]){this.showSection(this.HISTORY[this.HIST_INDEX][1]);
this.CONSOLE_INPUT.value="";}else{this.SKIP_HISTORY=true;this.CONSOLE_INPUT.value=this.HISTORY[this.HIST_INDEX][1];
this.getKey();}}else{this.warn("History: No where to back go from here.");}}},warn:function(b,c,a){if(null==a){a="";
}this.CONSOLE_INPUT.value=a;if(!c){this.CONSOLE_LABEL.style.color="red";}this.CONSOLE_LABEL.innerHTML="<span style='float:left;'>"+b+"</span><span style='float:right;color:#aaaaaa;font-weight:normal;'>(press any key to proceed)</span>";
this.showConsole();window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.value=a;
},50);},startRead:function(d,b,c,a){if(null==c){c="";}if(null==a){a="";}this.READ_COMMAND=d;
this.READING=true;this.CONSOLE_LABEL.innerHTML="<span style='float:left;'>"+b+"</span><span style='float:right;color:#aaaaaa;font-weight:normal;'>("+a+"RET to close)</span>";
this.showConsole();document.onkeypress=null;this.CONSOLE_INPUT.focus();this.CONSOLE_INPUT.onblur=function(){org_html_manager.CONSOLE_INPUT.focus();
};window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.value=c;},50);},endRead:function(b,a){this.READING=false;
this.READ_COMMAND="";this.CONSOLE_INPUT.onblur=null;this.CONSOLE_INPUT.blur();document.onkeypress=OrgHtmlManagerKeyEvent;
},removeWarning:function(){this.CONSOLE_LABEL.style.color="#333333";this.hideConsole();
},showConsole:function(){if(!this.MESSAGING){if(this.VIEW==this.PLAIN_VIEW){this.BODY.removeChild(this.BODY.firstChild);
this.NODE.div.insertBefore(this.CONSOLE,this.NODE.div.firstChild);this.NODE.div.scrollIntoView(true);
this.MESSAGING=this.MESSAGING_INPLACE;}else{this.MESSAGING=this.MESSAGING_TOP;window.scrollTo(0,0);
}this.CONSOLE.style.marginTop="0px";this.CONSOLE.style.top="0px";}},hideConsole:function(){if(this.MESSAGING){this.CONSOLE.style.marginTop="-"+this.CONSOLE_OFFSET;
this.CONSOLE.style.top="-"+this.CONSOLE_OFFSET;this.CONSOLE_LABEL.innerHTML="";this.CONSOLE_INPUT.value="";
if(this.MESSAGING_INPLACE==this.MESSAGING){this.NODE.div.removeChild(this.NODE.div.firstChild);
this.BODY.insertBefore(this.CONSOLE,this.BODY.firstChild);if(this.NODE.idx!=0){this.NODE.div.scrollIntoView();
}}this.MESSAGING=false;}},getKey:function(){var b=this.CONSOLE_INPUT.value;if(0==b.length){if(this.HELPING){this.showHelp();
return;}if(this.MESSAGING&&!this.READING){this.removeWarning();}return;}if(this.MESSAGING&&!this.READING){this.removeWarning();
return;}else{if(this.HELPING){this.showHelp();this.CONSOLE_INPUT.value="";return;
}else{if(this.READING){return;}}}this.CONSOLE_INPUT.blur();if(this.HIDE_TOC&&this.TOC==this.NODE&&"v"!=b&&"V"!=b){b="b";
}else{b=this.trim(b);}if(1==b.length){if("b"==b){this.popHistory();}else{if("B"==b){this.popHistory(true);
}else{if("c"==b){this.removeSearchHighlight();if(this.VIEW==this.INFO_VIEW||this.VIEW==this.SLIDE_VIEW){this.showSection(this.NODE.idx);
}}else{if("i"==b){if(this.FIXED_TOC){this.TOC.folder.getElementsByTagName("A")[0].focus();
}else{if(this.HIDE_TOC){this.navigateTo("toc");}else{if(0!=this.NODE.idx){this.navigateTo(0);
}}}}else{if("m"==b){this.toggleView(this.NODE.idx);}else{if("x"==b){this.slideView(this.NODE.idx);
}else{if("n"==b){if(this.NODE.state==OrgNode.STATE_FOLDED&&this.VIEW==this.PLAIN_VIEW){this.showSection(this.NODE.idx);
}else{if(this.NODE.idx<this.SECS.length-1){this.navigateTo(this.NODE.idx+1);return;
}else{this.warn("Already last section.");return;}}}else{if("N"==b){if(this.NODE.idx<this.SECS.length-1){var c=this.NODE.depth;
var a=this.NODE.idx+1;while(a<this.SECS.length-1&&this.SECS[a].depth>=c){if(this.SECS[a].depth==c){this.navigateTo(a);
return;}++a;}}this.warn("No next sibling.");}else{if("p"==b){if(this.NODE.idx>0){this.navigateTo(this.NODE.idx-1);
return;}else{this.warn("Already first section.");return;}}else{if("P"==b){if(this.NODE.idx>0){var c=this.NODE.depth;
var a=this.NODE.idx-1;while(a>0&&this.SECS[a].depth>=c){if(this.SECS[a].depth==c){this.navigateTo(a);
return;}--a;}}this.warn("No previous sibling.");}else{if("q"==b){if(window.confirm("Really close this file?")){window.close();
}}else{if("<"==b||"t"==b){if(0!=this.NODE.idx){this.navigateTo(0);}else{window.scrollTo(0,0);
}}else{if(">"==b||"E"==b||"e"==b){if((this.SECS.length-1)!=this.NODE.idx){this.navigateTo(this.SECS.length-1);
}else{this.SECS[this.SECS.length-1].div.scrollIntoView(true);}}else{if("v"==b){if(window.innerHeight){window.scrollBy(0,window.innerHeight-30);
}else{if(document.documentElement.clientHeight){window.scrollBy(0,document.documentElement.clientHeight-30);
}else{window.scrollBy(0,document.body.clientHeight-30);}}}else{if("V"==b){if(window.innerHeight){window.scrollBy(0,-(window.innerHeight-30));
}else{if(document.documentElement.clientHeight){window.scrollBy(0,-(document.documentElement.clientHeight-30));
}else{window.scrollBy(0,-(document.body.clientHeight-30));}}}else{if("u"==b){if(this.NODE.parent!=this.ROOT){this.NODE=this.NODE.parent;
this.showSection(this.NODE.idx);}}else{if("f"==b){if(this.VIEW!=this.INFO_VIEW){this.NODE.fold();
this.NODE.div.scrollIntoView(true);}}else{if("F"==b){if(this.VIEW!=this.INFO_VIEW){this.toggleGlobaly();
this.NODE.div.scrollIntoView(true);}}else{if("?"==b||"¿"==b){this.showHelp();}else{if("C"==b){if(this.SORTED_TAGS.length){this.showTagsIndex();
}else{this.warn("No Tags found.");}}else{if("H"==b&&this.LINK_HOME){window.document.location.href=this.LINK_HOME;
}else{if("h"==b&&this.LINK_UP){window.document.location.href=this.LINK_UP;}else{if("l"==b){if(""!=this.OCCUR){this.startRead(this.READ_COMMAND_HTML_LINK,"Choose HTML-link type: 's' = section, 'o' = occur");
}else{this.startRead(b,"HTML-link:",'<a href="'+this.BASE_URL+this.getDefaultTarget()+'">'+document.title+", Sec. '"+this.removeTags(this.NODE.heading.innerHTML)+"'</a>","C-c to copy, ");
window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.select();},100);}return;
}else{if("L"==b){if(""!=this.OCCUR){this.startRead(this.READ_COMMAND_ORG_LINK,"Choose Org-link type: 's' = section, 'o' = occur");
}else{this.startRead(b,"Org-link:","[["+this.BASE_URL+this.getDefaultTarget()+"]["+document.title+", Sec. '"+this.removeTags(this.NODE.heading.innerHTML)+"']]","C-c to copy, ");
window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.select();},100);}return;
}else{if("U"==b){if(""!=this.OCCUR){this.startRead(this.READ_COMMAND_PLAIN_URL_LINK,"Choose Org-link type: 's' = section, 'o' = occur");
}else{this.startRead(b,"Plain URL Link:",this.BASE_URL+this.getDefaultTarget(),"C-c to copy, ");
window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.select();},100);}return;
}else{if("g"==b){this.startRead(b,"Enter section number:");return;}else{if("o"==b){if(""!=this.OCCUR){this.startRead(b,"Occur:",this.OCCUR,"RET to use previous, DEL ");
}else{this.startRead(b,"Occur:",this.OCCUR);}window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.value=org_html_manager.OCCUR;
org_html_manager.CONSOLE_INPUT.select();},100);return;}else{if("s"==b){if(""!=this.OCCUR){this.startRead(b,"Search forward:",this.OCCUR,"RET to use previous, DEL ");
}else{this.startRead(b,"Search forward:",this.OCCUR);}window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.value=org_html_manager.OCCUR;
org_html_manager.CONSOLE_INPUT.select();},100);return;}else{if("S"==b){if(""==this.OCCUR){b="s";
this.startRead(b,"Search forward:");}else{this.READ_COMMAND=b;this.evalReadCommand();
}return;}else{if("r"==b){if(""!=this.OCCUR){this.startRead(b,"Search backwards:",this.OCCUR,"RET to use previous, DEL ");
}else{this.startRead(b,"Search backwards:",this.OCCUR);}window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.value=org_html_manager.OCCUR;
org_html_manager.CONSOLE_INPUT.select();},100);return;}else{if("R"==b){if(""==this.OCCUR){b="r";
this.startRead(b,"Search backwards:");}else{this.READ_COMMAND=b;this.evalReadCommand();
}return;}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}this.CONSOLE_INPUT.value="";return;},evalReadCommand:function(){var g=this.READ_COMMAND;
var a=this.trim(this.CONSOLE_INPUT.value);this.endRead();if(""==g||""==a){this.hideConsole();
return;}if(g=="g"){var e=this.SECNUM_MAP[a];if(null!=e){this.hideConsole();this.navigateTo(e.idx);
return;}this.warn("Goto section: no such section.",false,a);return;}else{if(g=="s"){if(""==a){return false;
}if(this.SEARCH_HIGHLIGHT_ON){this.removeSearchHighlight();}var d=this.OCCUR;var j=0;
if(a==this.OCCUR){j++;}this.OCCUR=a;this.makeSearchRegexp();for(var b=this.NODE.idx+j;
b<this.SECS.length;++b){if(this.searchTextInOrgNode(b)){this.OCCUR=a;this.hideConsole();
this.navigateTo(this.SECS[b].idx);return;}}this.warn("Search forwards: text not found.",false,this.OCCUR);
this.OCCUR=d;return;}else{if(g=="S"){for(var b=this.NODE.idx+1;b<this.SECS.length;
++b){if(this.searchTextInOrgNode(b)){this.hideConsole();this.navigateTo(this.SECS[b].idx);
return;}}this.warn("Search forwards: text not found.",false,this.OCCUR);return;}else{if(g=="r"){if(""==a){return false;
}if(this.SEARCH_HIGHLIGHT_ON){this.removeSearchHighlight();}var d=this.OCCUR;this.OCCUR=a;
var j=0;if(a==this.OCCUR){j++;}this.makeSearchRegexp();for(var b=this.NODE.idx-j;
b>-1;--b){if(this.searchTextInOrgNode(b)){this.hideConsole();this.navigateTo(this.SECS[b].idx);
return;}}this.warn("Search backwards: text not found.",false,this.OCCUR);this.OCCUR=d;
return;}else{if(g=="R"){for(var b=this.NODE.idx-1;b>-1;--b){a=this.removeTags(this.SECS[b].heading.innerHTML);
if(this.searchTextInOrgNode(b)){this.hideConsole();this.navigateTo(this.SECS[b].idx);
return;}}this.warn("Search backwards: text not found.",false,this.OCCUR);return;}else{if(g=="o"){if(""==a){return false;
}if(this.SEARCH_HIGHLIGHT_ON){this.removeSearchHighlight();}var d=this.OCCUR;this.OCCUR=a;
this.makeSearchRegexp();var f=new Array();for(var b=0;b<this.SECS.length;++b){if(this.searchTextInOrgNode(b)){f.push(b);
}}if(0==f.length){this.warn("Occur: text not found.",false,this.OCCUR);this.OCCUR=d;
return;}this.hideConsole();if(this.PLAIN_VIEW!=this.VIEW){this.plainView();}this.ROOT.dirty=true;
this.toggleGlobaly();for(var b=0;b<this.SECS.length;++b){OrgNode.showElement(this.SECS[b].div);
OrgNode.hideElement(this.SECS[b].folder);}for(var b=(f.length-1);b>=1;--b){OrgNode.showElement(this.SECS[f[b]].folder);
}this.showSection(f[0]);}else{if(g==this.READ_COMMAND_ORG_LINK){var h=a.charAt(0);
if("s"==h){this.startRead(this.READ_COMMAND_NULL,"Org-link to this section:","[["+this.BASE_URL+this.getDefaultTarget()+"]["+document.title+", Sec. '"+this.removeTags(this.NODE.heading.innerHTML)+"']]","C-c to copy, ");
window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.select();},100);}else{if("o"==h){this.startRead(this.READ_COMMAND_NULL,"Org-link, occurences of <i>&quot;"+this.OCCUR+"&quot;</i>:","[["+this.BASE_URL+"?OCCUR="+this.OCCUR+"]["+document.title+", occurences of '"+this.OCCUR+"']]","C-c to copy, ");
window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.select();},100);}else{this.warn(h+": No such link type!");
}}}else{if(g==this.READ_COMMAND_HTML_LINK){var h=a.charAt(0);if("s"==h){this.startRead(this.READ_COMMAND_NULL,"HTML-link to this section:",'<a href="'+this.BASE_URL+this.getDefaultTarget()+'">'+document.title+", Sec. '"+this.removeTags(this.NODE.heading.innerHTML)+"'</a>","C-c to copy, ");
window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.select();},100);}else{if("o"==h){this.startRead(this.READ_COMMAND_NULL,"HTML-link, occurences of <i>&quot;"+this.OCCUR+"&quot;</i>:",'<a href="'+this.BASE_URL+"?OCCUR="+this.OCCUR+'">'+document.title+", occurences of '"+this.OCCUR+"'</a>","C-c to copy, ");
window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.select();},100);}else{this.warn(h+": No such link type!");
}}}else{if(g==this.READ_COMMAND_PLAIN_URL_LINK){var h=a.charAt(0);if("s"==h){this.startRead(this.READ_COMMAND_NULL,"Plain-link to this section:",this.BASE_URL+this.getDefaultTarget(),"C-c to copy, ");
window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.select();},100);}else{if("o"==h){this.startRead(this.READ_COMMAND_NULL,"Plain-link, occurences of <i>&quot;"+this.OCCUR+"&quot;</i>:",this.BASE_URL+"?OCCUR="+this.OCCUR,"C-c to copy, ");
window.setTimeout(function(){org_html_manager.CONSOLE_INPUT.select();},100);}else{this.warn(h+": No such link type!");
}}}}}}}}}}}},getDefaultTarget:function(b){if(null==b){b=this.NODE;}var c="#"+this.NODE.base_id;
for(var a in b.isTargetFor){if(!a.match(this.SIDREX)){c=a;break;}}return c;},makeSearchRegexp:function(){var a=this.OCCUR.replace(/>/g,"&gt;").replace(/</g,"&lt;").replace(/=/g,"\\=").replace(/\\/g,"\\\\").replace(/\?/g,"\\?").replace(/\./g,"[^<>]").replace(/\"/g,"&quot;");
this.SEARCH_REGEX=new RegExp(">([^<]*)?("+a+")([^>]*)?<","ig");},searchTextInOrgNode:function(b){var a=false;
if(null!=this.SECS[b]){if(this.SEARCH_REGEX.test(this.SECS[b].heading.innerHTML)){a=true;
this.setSearchHighlight(this.SECS[b].heading);this.SECS[b].hasHighlight=true;this.SEARCH_HIGHLIGHT_ON=true;
}if(this.SEARCH_REGEX.test(this.SECS[b].folder.innerHTML)){a=true;this.setSearchHighlight(this.SECS[b].folder);
this.SECS[b].hasHighlight=true;this.SEARCH_HIGHLIGHT_ON=true;}return a;}return false;
},setSearchHighlight:function(b){var a=b.innerHTML;b.innerHTML=a.replace(this.SEARCH_REGEX,'>$1<span class="org-info-js_search-highlight">$2</span>$3<');
},removeSearchHighlight:function(){for(var b=0;b<this.SECS.length;++b){if(this.SECS[b].hasHighlight){while(this.SEARCH_HL_REG.test(this.SECS[b].heading.innerHTML)){var a=this.SECS[b].heading.innerHTML;
this.SECS[b].heading.innerHTML=a.replace(this.SEARCH_HL_REG,"$2");}while(this.SEARCH_HL_REG.test(this.SECS[b].folder.innerHTML)){var a=this.SECS[b].folder.innerHTML;
this.SECS[b].folder.innerHTML=a.replace(this.SEARCH_HL_REG,"$2");}this.SECS[b].hasHighlight=false;
}}this.SEARCH_HIGHLIGHT_ON=false;},highlight_headline:function(b){var a=parseInt(b);
if(this.PLAIN_VIEW==this.VIEW&&this.MOUSE_HINT){if("underline"==this.MOUSE_HINT){this.SECS[a].heading.style.borderBottom="1px dashed #666666";
}else{this.SECS[a].heading.style.backgroundColor=this.MOUSE_HINT;}}},unhighlight_headline:function(b){var a=parseInt(b);
if("underline"==this.MOUSE_HINT){this.SECS[a].heading.style.borderBottom="";}else{this.SECS[a].heading.style.backgroundColor="";
}},showHelp:function(){if(this.READING){this.endRead();}else{if(this.MESSAGING){this.removeWarning();
}}this.HELPING=this.HELPING?0:1;if(this.HELPING){this.last_view_mode=this.VIEW;if(this.PLAIN_VIEW==this.VIEW){this.infoView(true);
}this.WINDOW.innerHTML='Press any key or <a href="javascript:org_html_manager.showHelp();">click here</a> to proceed.<h2>Keyboard Shortcuts</h2><table cellpadding="3" rules="groups" frame="hsides" style="margin:20px;border-style:none;" border="0";><tbody><tr><td><code><b>? / &iquest;</b></code></td><td>show this help screen</td></tr></tbody><tbody><tr><td><code><b></b></code></td><td><b>Moving around</b></td></tr><tr><td><code><b>n / p</b></code></td><td>goto the next / previous section</td></tr><tr><td><code><b>N / P</b></code></td><td>goto the next / previous sibling</td></tr><tr><td><code><b>t / E</b></code></td><td>goto the first / last section</td></tr><tr><td><code><b>g</b></code></td><td>goto section...</td></tr><tr><td><code><b>u</b></code></td><td>go one level up (parent section)</td></tr><tr><td><code><b>i / C</b></code></td><td>show table of contents / tags index</td></tr><tr><td><code><b>b / B</b></code></td><td>go back to last / forward to next visited section.</td></tr><tr><td><code><b>h / H</b></code></td><td>go to main index in this directory / link HOME page</td></tr></tbody><tbody><tr><td><code><b></b></code></td><td><b>View</b></td></tr><tr><td><code><b>m / x</b></code></td><td>toggle the view mode between info and plain / slides</td></tr><tr><td><code><b>f / F</b></code></td><td>fold current section / whole document (plain view only)</td></tr></tbody><tbody><tr><td><code><b></b></code></td><td><b>Searching</b></td></tr><tr><td><code><b>s / r</b></code></td><td>search forward / backward....</td></tr><tr><td><code><b>S / R</b></code></td><td>search again forward / backward</td></tr><tr><td><code><b>o</b></code></td><td>occur-mode</td></tr><tr><td><code><b>c</b></code></td><td>clear search-highlight</td></tr></tbody><tbody><tr><td><code><b></b></code></td><td><b>Misc</b></td></tr><tr><td><code><b>l / L</b></code></td><td>display HTML link / Org link</td></tr><tr><td><code><b>U</b></code></td><td>display Plain-URL link type</td></tr><tr><td><code><b>v / V</b></code></td><td>scroll down / up</td></tr></tbody></table><br />Press any key or <a href="javascript:org_html_manager.showHelp();">click here</a> to proceed.';
window.scrollTo(0,0);}else{if(this.PLAIN_VIEW==this.last_view_mode){this.plainView();
}else{if(this.SLIDE_VIEW==this.last_view_mode){this.slideView();}}this.showSection(this.NODE.idx);
}},showTagsIndex:function(){if(this.READING){this.endRead();}else{if(this.MESSAGING){this.removeWarning();
}}this.HELPING=this.HELPING?0:1;if(this.HELPING){this.last_view_mode=this.VIEW;if(this.PLAIN_VIEW==this.VIEW){this.infoView(true);
}if(null==this.TAGS_INDEX){this.TAGS_INDEX='Press any key or <a href="javascript:org_html_manager.showTagsIndex();">click here</a> to proceed.<br /><br />Click the headlines to expand the contents.<h2>Index of Tags</h2>';
for(var d=0;d<this.SORTED_TAGS.length;++d){var b=this.SORTED_TAGS[d];var e="org-html-manager-sorted-tags-"+b;
this.TAGS_INDEX+="<a href=\"javascript:OrgNode.toggleElement(document.getElementById('"+e+"'));\"><h3>"+b+'</h3></a><div id="'+e+'" style="visibility:hidden;display:none;"><ul>';
for(var c=0;c<this.TAGS[b].length;++c){var a=this.TAGS[b][c];this.TAGS_INDEX+='<li><a href="javascript:org_html_manager.showSection('+a+');">'+this.SECS[a].heading.innerHTML+"</a></li>";
}this.TAGS_INDEX+="</ul></div>";}this.TAGS_INDEX+='<br />Press any key or <a href="javascript:org_html_manager.showTagsIndex();">click here</a> to proceed.';
}this.WINDOW.innerHTML=this.TAGS_INDEX;window.scrollTo(0,0);}else{if(this.PLAIN_VIEW==this.last_view_mode){this.plainView();
}else{if(this.SLIDE_VIEW==this.last_view_mode){this.slideView();}}this.showSection(this.NODE.idx);
}}};function OrgHtmlManagerKeyEvent(b){var d;if(!b){b=window.event;}if(b.which){d=b.which;
}else{if(b.keyCode){d=b.keyCode;}}if(b.ctrlKey){return;}var a=String.fromCharCode(d);
if(b.shiftKey){org_html_manager.CONSOLE_INPUT.value=org_html_manager.CONSOLE_INPUT.value+a;
}else{org_html_manager.CONSOLE_INPUT.value=org_html_manager.CONSOLE_INPUT.value+a.toLowerCase();
}org_html_manager.getKey();}function OrgHtmlManagerLoadCheck(){org_html_manager.init();
}