#+TITLE:   Google Calendar Synchronization
#+AUTHOR:    Arun Persaud
#+EMAIL:     arun@nubati.net
#+DATE:      <2011-01-27 Thu>
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

* Overview
  To get a real synchronization between org-mode and Google Calendar
  you need to sync two ways. We cover one way of handling the
  synchronization in the next two sections and also mention some other
  ways of synchronization at the end.
* From Google Calendar into org using .ics files
  Google Calendar offers access to each calendar via a hidden/secret
  url. That is, a url that only you know about and is very hard to
  guess for other people. You can use this to download your calendar
  in an iCalendar (.ics) format, which we then can rewrite into
  something usable for org-mode. For this conversion there luckily
  already exists a script written by Eric S. Fraga[fn:1]. This is the latest version:

#+INCLUDE: "../code/awk/ical2org.awk" src sh

With this you can test your Google Calendar to org-mode
synchronization by following these steps:

1. Download the above script and save it as 'ical2org'.
   Make sure that the script is in your PATH and don't forget to set
   the executbale flag (chmod u+x ical2org). You can also customize the 
   script a bit by changing the variables in the config section of the script.
2. Find your private URL for your calendar
  + Log into Google Calendar
  + Goto Settings
  + Click on the calendar you want to export to org-mode
  + At the bottom of the page find the 'private address' section and your ical link 
    Use the 'reset private urls' if you need to, that is if you don't
    see a unique url.
3. Download the url
   This can be done for example using 'wget <url>'
4. Transform into org-file
   Use the downloaded script via 'ical2org < icsfile > orgfile'. Where
   icsfile is the path to the file you downloaded from google and
   orgfile is the org-mode file you want to create.
5. Add the orgfile to your agenda and test

If this all works you can automate the task via cron. Create a script
such as the following that will automatically download and convert
your calendar. Make sure that this file is only readable by you (chmod
700 <file>), since it will contain the url to your google calendar.

#+begin_src sh
#!/bin/bash

# customize these
WGET=<path to wget>
ICS2ORG=<path to ical2org>
ICSFILE=<path for icsfile>
ORGFILE=<path to orgfile>
URL=<url to your private google calendar>

# no customization needed below

$WGET -O $ICSFILE $URL
$ICS2ORG < $ICSFILE > $ORGFILE
#+end_src

automate this via cron by adding something like the following to your
crontab:

#+begin_example
5,20,35,50 * * * * <path to above script> &> /dev/null #sync my org files
#+end_example

This will sync every 15 minutes starting at 5 minutes past the hour.

* From org to Google Calendar
  'still needs editing'

  possible paths
  1. export from org mode to .ics; upload .ics to a public web server
     giving it a hidden/secret name; tell google to import this .ics
     file
  2. use googlecl to import event when you create them into google
     calendar (update entries won't be reflected in google). See [fn:2]

* Footnotes
[fn:1] http://article.gmane.org/gmane.emacs.orgmode/26848
[fn:2] http://article.gmane.org/gmane.emacs.orgmode/27214
