#+OPTIONS:    H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) NEW(n)
#+TITLE:      Org-mode Contributed Packages
#+AUTHOR:     Worg people
#+EMAIL:      bzg AT altern DOT org
#+LANGUAGE:   en
#+CATEGORY:   worg

#+LINK: repofile http://repo.or.cz/w/org-mode.git?a=blob_plain;f=%s;hb=HEAD

[[file:../index.org][{Back to Worg's index}]]

This page lists the contributed packages to Org-mode, with links to
available documentation.  Most of these packages are located in the
/contrib/ directory of the Org distribution.  Some have made it into
the core by now, but we keep the documentation here because it is more
extensive than what is available in the manual.  If no documentation
link is present, see the file header of the package -- it will
hopefully have some documentation.

- /org-annotate-file.el/ -- annotate a file with org syntax ::
  The annotation is in a separate file, with links back to the
  annotated file.  Written by /Philip Jackson/.
  [[repofile:contrib/lisp/org-annotate-file.el][Link to raw file]].

- [[file:org-annotation-helper.org][org-annotation-helper.el -- managing browser bookmarks]] ::
  Org-annotation-helper allows to create Org-mode links and
  annotations while working in a browser, by simply clicking a
  bookmarklet.
  Written by /Bastien Guerry/ and /Daniel M German/.
  [[repofile:contrib/lisp/org-annotation-helper.el][Link to raw file]].

- [[file:org-annotation-quicksilver.org][org-annotation-quicksilver -- linking and annotation from OS X applications]] ::
  org-annotation-quicksilver allows you to link, annotate and file
  away in an org-mode buffer, all without leaving the application you
  are working with.
  Written by /Christopher Suckling/
  [[repofile:contrib/packages/?????][Link to raw file]]. ?????
  
- /org-bookmark.el/ -- support for links to Emacs bookmarks ::
  Written by /Tokuya Kameshima/.
  [[repofile:contrib/lisp/org-bookmark.el][Link to raw file]].

- /org-browser-url.el/ --  bookmark from a browser into org links ::
  Written by /Ross Patterson/.
  [[repofile:contrib/lisp/org-browse-url.el][Link to raw file]].

- /org-checklist.el/ -- org functions for checklist handling ::
  Reset checklists in repeating entries.  Written by /James TD Smith/.
  [[repofile:contrib/lisp/org-checklist.el][Link to raw file]].

- [[file:org-choose.org][org-choose.el -- decision management for org-mode]] ::
  Org-choose helps documenting a decision-making process by using
  TODO keywords for different degrees of /chosenness/, and by
  automatically keeping a set of alternatives in a consistent state.
  Writen by /Tom Breton/.
  [[repofile:contrib/lisp/org-choose.el][Link to raw file]].

- /org-collector.el/ -- collect properties into tables ::
  Collect and process properties into a table.
  Written by /Eric Schulte/.
  [[repofile:contrib/lisp/org-collector.el][Link to raw file]].

- [[file:org-depend.org][/org-depend.el/ -- TODO dependencies for Org-mode]] ::
  Make TODO state changes in one entry trigger changes in another, or
  be blocked by the state of another entry.  Also, easily create
  chains of TODO items with exactly one active item at any time.
  Written by /Carsten Dominik/.
  [[repofile:contrib/lisp/org-depend.el][Link to raw file]].

- /org-elisp-symbol.el/ -- Org links to emacs-lisp symbols. ::
  This can create annotated links that exactly point to the definition
  location of a variable of function.
  Written by /Bastien Guerry/.
  [[repofile:contrib/lisp/org-elisp-symbol.el][Link to raw file]].

- /org-eval.el/ -- show evaluation result of code ::
  The =<lisp>= tag, adapted from Emacs Wiki and Emacs Muse, allows
  text to be included in a document that is the result of evaluating
  some code.  Other scripting languages like /perl/ can be
  supported with this package as well.
  Written by /Carsten Dominik/.
  [[repofile:contrib/lisp/org-eval.el][Link to raw file]].

- [[file:org-eval-light.org][org-eval-light.el -- display result of evaluating code in various languages (light)]] ::
  Org-eval-light allows the execution of source code embedded in an
  org-mode file.  The results of the execution are placed into the
  org-mode file.  It is a reworking of Carsten's org-eval with the
  goals of a more uniform syntax, safer default execution rules, and
  increased ease of execution.
  Written by /Eric Schulte/.
  [[repofile:contrib/lisp/org-eval-light.el][Link to raw file]].

- /org-exp-bibtex.el/ -- Export bibtex fragments ::
  Written by /Taru Karttunen/.
  [[repofile:contrib/lisp/org-exp-bibtex.el][Link to raw file]].

- [[file:org-exp-blocks.org][org-exp-blocks.el --- pre-process blocks when exporting org files]] ::
  Org-export-blocks allows for the pre-processing or blocks in
  org-mode files to create images, or specially formatted HTML or
  LaTeX output.  Written by /Eric Schulte/.
  [[repofile:contrib/lisp/org-exp-blocks.el][Link to raw file]].

- /org-expiry.el/ -- expiry mechanism for Org entries ::
  Written by /Bastien Guerry/.
  [[repofile:contrib/lisp/org-expiry.el][Link to raw file]].

- [[file:org-feed.org][/org-feed.el/ -- add RSS feed items to Org files]] ::
  Read RSS feeds from the web, add new items to Org files, and trigger
  actions when items have changed.
  Written by /Carsten Dominik/.
  [[repofile:lisp/org-feed.el][Link to raw file]].

- /org-indent.el/ -- dynamic indentation of Org outlines ::
  The plan is to indent an outline according to level, but so far this
  is too hard for a proper and stable implementation.  Still, it works
  somewhat.  Written by /Carsten Dominik/.
  [[repofile:contrib/lisp/org-indent.el][Link to raw file]].

- /org-interactive-query.el/ -- interactive modification of tags queries ::
  After running a general query in Org, this package allows to narrow
  down the results by adding more tags or keywords.  Written by
  /Christopher League/.
  [[repofile:contrib/lisp/org-interactive-query.el][Link to raw file]].

- /org-mairix.el/ -- hook mairix search into Org for different MUAs ::
  Written by /Georg C. F. Greve/.
  [[repofile:contrib/lisp/org-mairix.el][Link to raw file]].

- /org-man.el/ -- support for links to manpages in Org-mode. ::
  Written by /Carsten Dominik/.
  [[repofile:contrib/lisp/org-man.el][Link to raw file]].

- [[file:org-mac-message.org][org-mac-message.el --- linking to messages in OS X Mail.app]] ::
  Create links to selected or flagged messages in Mail.app
  Written by /John Wiegley/ and /Christopher Suckling/
  [[repofile:lisp/org-mac-message.el][Link to raw file]]

- /org-mtags.el/ -- support for some Muse-like tags in Org-mode ::
  This package allows you to write =<example>= and =<src>= and other
  syntax copied from Emacs Muse, right inside an Org file.  The goal
  here is to make it easy to publish the same file using either
  org-publish or Muse.  Written by /Carsten Dominik/.
  [[repofile:contrib/lisp/org-mtags.el][Link to raw file]].

- /org-panel.el/ -- simplified and display-aided access to some Org commands ::
  Written by /Lennart Borgman/.
  [[repofile:contrib/lisp/org-panel.el][Link to raw file]].

- [[file:../org-tutorials/org-R/org-R.org][org-R.el --- Computing and data visualisation in Org-mode using R]] ::
  Written by /Dan Davison/.
  [[repofile:contrib/lisp/org-R.el][Link to raw file]].

- /org-registry.el/ -- a registry for Org links ::
  Find out from where links point to a given file or location.
  Written by /Bastien Guerry/.
  [[repofile:contrib/lisp/org-registry.el][Link to raw file]].

- /org2rem.el/ -- Convert org appointments into reminders for /remind/ ::
  Written by /Bastien Guerry/ and /Sharad Pratap/.
  [[repofile:contrib/lisp/org2rem.el][Link to raw file]].

- /org-screen.el/ -- visit screen sessions through Org-mode links ::
  Written /Andrew Hyatt/.
  [[repofile:contrib/lisp/org-screen.el][Link to raw file]].

- /org-toc.el/ -- table of contents in a separate buffer ::
  With fast access to sections and easy visibility cycling.
  Written by /Bastien Guerry/.
  [[repofile:contrib/lisp/org-toc.el][Link to raw file]].

- [[http://orgmode.org/worg/org-tutorials/multitarget-tables.php][/orgtbl-sqlinsert.el/ -- convert Org-mode tables to SQL insertions]] ::
  Written by /Jason Riedy/.
  [[repofile:contrib/lisp/orgtbl-sqlinsert.el][Link to raw file]].

- [[file:org-protocol.org][org-protocol.el -- Trigger actions through URLs]] ::
  org-protocol intercepts calls from emacsclient to trigger custom actions without
  external dependencies. Only one protocol has to be configured with your external
  applications or the operating system.
