#+TITLE:   org-track.el -- Keep current with Org-mode development: M-x org-track-update
#+OPTIONS:    H:3 num:nil toc:t \n:nil ::t |:t ^:{} -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc author:nil
#+STARTUP: odd

# This file is released by its authors and contributors under the GNU
# Free Documentation license v1.3 or later, code examples are released
# under the GNU General Public License v3 or later.

[[file:index.org][{Back to Worg's contibutions index}]]

*Note that this package might need to be updated to work with the new
Org repo starting 2018. See [[http://lists.gnu.org/r/emacs-orgmode/2017-12/msg00578.html][here]] for the announcement.*

=org-track.el= aims to add a simple interface to track Org-mode's git
repository on https://code.orgmode.org/bzg/org-mode.git. For non-git
users, an =org-latest.tar.gz= archive is provided and will be downloaded
from https://orgmode.org/org-latest.tar.gz.

The idea was born in a thread on the emacs-orgmode mailing list on [[https://orgmode.org/list/D5AB1A81-4B00-4B4F-9A1C-A2995AE297FA@nf.mpg.de][a
request from Stefan Vollmar]].

If you run into trouble, drop us a mail on the [[mailto:emacs-orgmode@gnu.org][emacs-orgmode mailing
list]].

# <<usage>>

* Usage

  You will need an initial version of the Org-mode distribution in
  your load path:

  #+begin_src emacs-lisp
    (add-to-list load-path "/path/to/org-mode/lisp")
    (require org)
    (require org-track)
  #+end_src

  You will also need to clone the =org-contrib= repository from [[https://git.sr.ht/~bzg/org-contrib][here]],
  and to require =org-track=:

  #+begin_src emacs-lisp
    (add-to-list load-path "/path/to/org-contrib/lisp")
    (require org-track)
  #+end_src

  Adjust at least the variable =org-track-directory=. You can use
  customize for this:

  : M-x customize-variable RET org-track-directory RET

  From now on, to update and compile the current development version
  of Org-mode is just a matter of typing:

  : M-x org-track-update RET

  This will download the current =org-latest.tar.gz= and (optionally) compile the sources.

# <<org-git-directory>>
* org-track-directoy Layout

  The =org-track-directory= is the only variable you'll need to
  adjust. This is the directory where your local copy of Org-mode will
  live. I.e., a sub directory 'org-mode/' will be added here. Also the
  file =org-latest.tar.gz= will be put here (and deleted after updates):

  : org-track-directory
  :         |-- org-latest.tar.gz (if you download archives)
  :         `-- org-mode
  :             |-- ...
  :             |-- lisp          (add this dir to your loadpath)
  :             |-- contrib
  :             |   `-- lisp       (add this dir to your loadpath)
  :             `-- ...

* Fine-tuning

  To see and/or change all the related variables, do:

  : M-x customize-group RET org-track RET

  Here is a list of all variables the script uses:

  - =org-track-directory= :: The directory, where the sub-directory
    =org-mode/= lives. Default: =~/.emacs.d/org/lisp=
  - =org-track-compile-sources= :: Compile the sources after
    downloading? Defaults to =t=.
  - =org-track-org-url= :: The package is downloaded from this URL. This
    denotes the folder actually (i.e. the URL without the basename
    =org-latest.tar.gz=).
  - =org-track-org-package= :: The name the package itself. Default:
    =org-latest.tar.gz=.
  - =org-track-remove-package= :: Remove the downloaded package after
    unpacking?  The default is to keep the archive.

* How it works

  The `*.tar.gz' version is extracted without external dependencies
  (tar-mode).  To make sure that =org-latest.tar.gz= is opened in
  tar-mode, the code modifies your `auto-mode-alist':

  #+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("org-latest\\.tar\\.gz\\'" . tar-mode))
  #+end_src

  The downloaded package can be removed. See the option
  =org-git-remove-package=.  Default is not to remove =org-latest.tar.gz=.
