#+TITLE:     org-mac-message.el -- linking to messages in OS X Mail.app
#+OPTIONS:   ^:{} author:nil
#+STARTUP: odd

  The org-mac-message.el library provides various methods for linking
  to OS X Mail.app messages from within org-mode.

* Installation
  - To load org-mac-message.el by default:

    : (add-to-list 'org-modules 'org-mac-message)

    Note that =org-modules= must be set before org-mode is loaded.

  - Configure the default Mail.app account you would like to use:

    : (setq org-mac-mail-account "account")

  - If you have [[http://growl.info][Growl]] installed and would like visual feedback whilst
    AppleScript searches for message, please uncomment lines 126 to
    131.

* Usage
  org-mac-message.el will create links with the format:

  : [[message://message-ID][Subject]]

  When followed, these links will open the relevant message in
  Mail.app.

** New functions

   - =(org-mac-message-insert-link)=
     Inserts formatted list of links at point to selected messages in
     Mail.app.
   - =(org-mac-create-flagged-mail)=
     Searches for flagged mail in the Mail.app account specified by
     =org-mac-mail-account=.
     Creates a formatted list of these links and copies them to the
     kill-ring.
   - =(org-mac-insert-flagged-mail (org-buffer org-heading))=
     Asks for an org buffer and heading within it.  If the heading does
     not exist, create it at `point-max'.  

     *Warning: the next step is destructive* 
     
     Delete all =message://= links within the heading's first level.
     Search for flagged mail in Mail.app and insert a formatted list of
     links under the specified heading.

** Examples of usage
   The following function will search the account =Gmail= for flagged
   messages and insert them in the org-mode buffer =taskpool.org= under
   the heading =Flagged mail=.
  
#+BEGIN_SRC emacs-lisp
(defun my-mail-import ()
  (let ((org-mac-mail-account "Gmail"))
    (org-mac-insert-flagged-mail ("taskpool.org" "Flagged mail"))))   
#+END_SRC

    This function could then be linked to from an org-mode buffer:
    
    : [[elisp:(my-mail-import)][Flagged%20Gmail]]

    or set as a command in the agenda dispatcher:

#+BEGIN_SRC emacs-lisp
(setq org-agenda custom-commands
      '(("F" "Import links to flagged mail" agenda ""
	 ((org-agenda-mode-hook
	   (my-mail-import))))))
#+END_SRC

   


   
