#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+TITLE:      Google Summer of Code 2012
#+AUTHOR:     Thorsten Jolitz
#+EMAIL:      tj[at]data-driven[dot]de
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    ./index.html
#+LINK_HOME:  http://orgmode.org/worg/
#+EXPORT_EXCLUDE_TAGS: noexport


#+name: banner
#+begin_html
  <div id="subtitle" style="float: center; text-align: center;">
  <p>
  Org Mode info-page for GNU's application to  <a href="http://www.google-melange.com/gsoc/homepage/google/gsoc2012">GSoC 2012</a>
  </p>
  <p>
  <a href="http://www.google-melange.com/gsoc/homepage/google/gsoc2012"/>
  <img src="http://t1.gstatic.com/images?q=tbn:ANd9GcRbAgQorAr3evNbItUq1iaF53LzPknqMme1frngxXS4XHpP1LWsBw" />
  </a>
  </p>
  </div>
#+end_html


* Org Mode GSoC 2012 Student Page

#+BEGIN_QUOTE
This page is selected content copied&pasted from Google's excellent [[http://www.google-melange.com/document/show/gsoc_program/google/gsoc2012/faqs][faq]]
page. It summarizes all the information relevant for GSoC 2012
students. "We" in the following text stands for "Google",
not for "Org Mode" or "GNU". 
#+END_QUOTE

The student application period begins March 26, 2012 and ends April
6th at 19:00 UTC. 

** How does a student apply?

Students can submit their applications via the Google Summer of Code
2012 site from March 27 - April 9, 2012. We hear almost universally
from our mentoring organizations that the best applications they
receive are from students who took the time to interact and discuss
their ideas before submitting an application, so make sure to check
out each organization's Ideas list to get to know a particular open
source organization better. In addition to an application, students
will be required to sign a Student Participation Agreement.

** What should a student application look like?

Your application should include the following: your project proposal,
why you'd like to execute on this particular project, and the reason
you're the best individual to do so. Your proposal should also include
details of your academic, industry, and/or open source development
experience, and other details as you see fit. An explanation of your
development methodology is a good idea, as well. It is always helpful
to include contact information as well, as it will not be
automatically shared with your would-be mentors as part of the
application process. If the organization you want to work with has a
specific application template they would like you to use, it will be
made available to you to fill in when submitting your proposal via the
Google Summer of Code web app. [note: the PicoLisp community has not
specific application template]

** Can a student submit more than one application?

Yes, each student may submit up to twenty applications. However, only
one application will be accepted. We've heard from our mentoring
organizations that quality is better than quantity.

** Can students already working on an open source project continue to work on it as part of Google Summer of Code?

Yes, as long as they meet all other requirements for program
eligibility. Students should be sure to note their previous
relationship with the project in their applications. New work will
need to be done for the project as part of participation in Google
Summer of Code.

** Should students begin working on their applications before Google begins accepting program applications?

That's up to you. Keep in mind, though, that our mentoring
organizations will be publishing a list of proposed project ideas, so
you may find that you'll want to revamp your application later, or
create an entirely new one to address one of those ideas.

** Can a student work on more than one project?

No, each participant may only work on one project and is only eligible
for one stipend.

** Can a group apply for and work on a single proposal?

No, only an individual may work on a given project.

** What happens if two students are accepted to work on the same project, e.g. from an organization's Ideas list?

That's fine, a little duplication is par for the course in open
source.

** Are proposals for documentation work eligible for Google Summer of Code?

While we greatly appreciate the value of documentation, this program
is an exercise in developing code; we can't accept proposals for
documentation-only work at this time.

** How do payments work?

Google will provide a stipend of 5500 USD per accepted student
developer, of which 5000 USD goes to the student and 500 USD goes to
the mentoring organization.

Accepted students in good standing with their mentoring organization
will receive a 500 USD stipend shortly after coding begins on May
21, 2012. Students who receive passing mid-term evaluations will
receive a 2250 USD stipend shortly after the mid-term evaluation
deadline, July 13, 2012. Students who receive passing final
evaluations and who have submitted their final program evaluations
will receive a 2250 USD stipend shortly after the final evaluation
deadline, August 24, 2012. Mentoring organizations must request their
payments of 500 USD per student mentored by November 5, 2012.
