#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+TITLE:      LinuxTag - The Day `O'
#+AUTHOR:     Worg people
#+EMAIL:      emacs-orgmode AT gnu DOT org
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   worg
#+OPTIONS:    H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc

[[file:../index.org][{Back to Worg's index}]]

We plan to attend the the /LinuxTag/ 2010 in the
#+ATTR_HTML: target="blank" title="Open Google map in new window: Fairground Berlin."
[[http://maps.google.com/maps?f=q&source=s_q&hl=de&geocode=&q=Funkturm+Berlin&sll=52.505019,13.278233&sspn=0.017554,0.043688&ie=UTF8&hq=&hnear=Funkturm+Berlin,+Masurenallee+14,+Charlottenburg+14057+Berlin,+Deutschland&t=h&z=15][Berlin]]
from the 9nth to the 12th of June.

*NOTE:* A certain number of [[#volunteers][volunteers]] and a sponsored booth are essential
prerequisites for our attendance. Both of which are not met yet. Call for
projects should start in January. We aim to have constantly 5 people running the
stand.


* About LinuxTag

  The German homepage of LinuxTag is [[http://www.linuxtag.org]], the English
  homepage can be found on [[http://www.linuxtag.org/2009/en/]]

  The program for 2010 is not online yet.  Find Download Slides and handouts for
  items on the agenda 2009 from
  http://www.linuxtag.org/2009/en/program/conference-material.html to get a clue
  of what was happening there this year. Note, that most but not all tutorials
  were held in English.

  See also to http://wiki.linuxtag.org/ vor more on LinuxTag 2010 ([[http://wiki.linuxtag.org/w/fp:FAQ][FAQ]]).

  Last year's Call For Projects started in February. But the FAQ states, that it
  starts in January ([[http://wiki.linuxtag.org/w/fp:FAQ]]).


* Volunteers
  :PROPERTIES:
  :CUSTOM_ID: volunteers
  :END:

  Please don't forget to tell us how you would like to help, if you will manage
  it to come to Berlin. There's no need to stay for the entire 4 days. Every
  helping hand is very much appreciated.

  Remember: Wednesday 09 Jun 2010 - Saturday 12 Jun 2010


  =F= = Full Day \\
  =M= = Morning \\
  =A= = Afternoon \\

#+CAPTION: List of volunteers
#+ATTR_HTML: style="border:2px solid black;"
  |   | Name           | Short | Wed | Thu | Fri | Sat | What                               |
  |---+----------------+-------+-----+-----+-----+-----+------------------------------------|
  | / | <              | >     | <   |     |     | >   | <                                  |
  |   | Sebastian Rose | SR    | M   | F   | F   | A   | Organization, Demos, Installations |

